### ISSUE TITLE
http to https redirect when SSL is enabled

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#100]
Possible? 
when using http:// mstream is not responding or redirecting towards the SSL https:// connection, would be nice to have a redirect available that redirects towards the safe connection.

**Comment by IrosTheBeggar** [comment]
I already made a ticket for this a while ago.  Unfortunately idk if there is any way to actually do this without using a proxy like nginx

https://github.com/IrosTheBeggar/mStream/issues/70

**Comment by IrosTheBeggar** [comment]
Closing this ticket since it's a duplicate.  I updated the description of the the other ticket too
