### ISSUE TITLE
scan of database throwing error

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#102]
This part consist of several small issues or things I saw during the use of the json file

stderr: (node:18636) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/media/music/TOP40-65-2009/Complete Top 40 Van 1965/001 - Beatles - I Feel Fine.mp3'
    at Object.fs.statSync (fs.js:948:11)
    at parseFile (/home/mStream/modules/db-management/database-default-manager.js:124:21)
    at scanDirectory (/home/mStream/modules/db-management/database-default-manager.js:59:11)
    at scanDirectory.next (<anonymous>)
    at /home/mStream/modules/db-management/database-default-manager.js:153:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

stderr: (node:18636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17268)
(node:18636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

child process exited with code 0

the file is there and the folder as well. it seems to stop the scan as other folders and files are not showing the album-art

maybe not related, but I see an aweful lot of these console messages now

stdout: Warning: failed to parse file '/media/music/12 inches A-Z/0-9/20 Fingers ft_ Roula - Lick It (1995) (CDM)/(05) Lick It (Onofrio Club Mix).flac': Cannot read property 'no' of undefined

stdout: Warning: failed to parse file '/media/music/12 inches A-Z/0-9/20 Fingers ft_ Roula - Lick It (1995) (CDM)/(06) Lick It (J.J. 'S Bass Radio Mix).flac': Cannot read property 'no' of undefined

stdout: Warning: failed to parse file '/media/music/12 inches A-Z/0-9/3rd Nation - I Believe CDM/01. 3rd Nation - I Believe (Our Tribe Radio Edit).wav': Cannot read property 'no' of undefined

it might be that there is no id3tag, but is it necessary to output these? When I see this for hours in my console I am getting scared if my db with files are ok yes/no ;) Even after a restart it keeps outputting these (slowly)
it looks like this is caused by using the json file. and the way the json is created cause when i do not use json anymore I see the db (same filename) has 0 files again and it is rescanning again. 

I hope this can be made more intelligent. I want to rely on the db if it is used. with my 147.000 songs and 4TB I do not want to have to recreate the db every day.

**Comment by IrosTheBeggar** [comment]
Can you post your json config file here?

Works keeping me really busy this week, I'll look into all this during the weekend.

**Comment by aroundmyroom** [comment]
of course I can post it ..  take your time. I am just a new user analyzing this software suddenly disturbing you in your daily life ;) 
`{
  "port": 3000,
  "database_plugin":{
    "dbPath":"/home/mStream-data/mstream_052018.db"
  },
  "folders": {
    "AroundMyMusic": "/media/music/"
  },
  "users": {
    "myuser": {
      "password":"mypwd",
      "vpaths": ["AroundMyMusic"]
  }
},
  "ssl": {
    "key": "/home/mStream-data/ssl/privkey.pem",
    "cert": "/home/mStream-data/ssl/cert.pem"
      }
   }
`
or more readable
{
  "port": 3000,
  "database_plugin":{
    "dbPath":"/home/mStream-data/mstream_052018.db"
  },
  "folders": {
    "AroundMyMusic": "/media/music/"
  },
  "users": {
    "myser": {
      "password":"mypwd",
      "vpaths": ["AroundMyMusic"]
  }
},
  "ssl": {
    "key": "/home/dennis/mStream-data/ssl/privkey.pem",
    "cert": "/home/dennis/mStream-data/ssl/cert.pem"
      }
   }



Very 'simple' json based on your example

**Comment by aroundmyroom** [comment]
just found the reason mstream is 'crashing and stopping indexing' 

stderr: (node:4058) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/media/music/12 inches A-Z/D/D Shake - Interstellar Overdrive/01. Interstellar Overdrive (Like A Faxmachine).flac'
    at Object.fs.statSync (fs.js:948:11)
    at parseFile (/home/dennis/mStream/modules/db-management/database-default-manager.js:124:21)
    at scanDirectory (/home/dennis/mStream/modules/db-management/database-default-manager.js:59:11)
    at scanDirectory.next (<anonymous>)
    at /home/dennis/mStream/modules/db-management/database-default-manager.js:153:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

stderr: (node:4058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4579)

stderr: (node:4058) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Reason is that when you do maintenance on your folders with music (ie. delete a song as it is ie. double)
than the error about the file will stop the scan. It keeps running but no other caching of files is seen.

WIth +4TB of music it gives a little problem keeping scanning and make sure the 'db' is up to date

**Comment by IrosTheBeggar** [comment]
that's an interesting place for an error to occur. Are you editing your library while the DB scan is happening?

**Comment by aroundmyroom** [comment]
Actually: I was, but at that time I did not know that it was still scanning ;)

One of the reasons why I am was doing this was to see why the scan of the library is not complete
I have a bunch of folders not being indexed. I know that as I do not see any ID3tag on the player even not the cover. If I only index that particular folder it is working fine. the console does not show me why it is not scanning a folder (or folders). at a certain time it says exiting status 0 and thats it.. 

It looks like it is skipping those folders. To find out where it fails is a problem ..
