### ISSUE TITLE
Empty album songs when the album title is only a number

### ISSUE THREAD

**Issue by theof** [IrosTheBeggar/mStream#103]
When I browse an album whose title is only a number, I get an empty song list.
It seems that the database lookup is done with a "number" type. 

As I am not really comfortable with what exactly is the API and at which level should the number be converted / type checked, I will just post my patch here instead of PR:
```diff
diff --git a/public/js/mstream.js b/public/js/mstream.js
index f87aef8..10a1131 100755
--- a/public/js/mstream.js
+++ b/public/js/mstream.js
@@ -683,6 +683,8 @@ $(document).ready(function () {
   // Load up album-songs
   $("#filelist").on('click', '.albumz', function () {
     var album = $(this).data('album');
+    if (typeof(album) === "number")
+         album = album.toString();
     getAlbumSongs(album);
   });
```

**Comment by IrosTheBeggar** [comment]
I pushed a fix that standardize all the albums/artists/title values to strings
