### ISSUE TITLE
add filepath in info screen when playing song

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#105]
![image](https://user-images.githubusercontent.com/250108/40911387-f0c803ee-67ee-11e8-8df9-95e6115b0b6d.png)

WOuld it be possible to add the filepath in the music info screen?
when it is playing the song?
I know it is available in the debug part of the browser through the console, but when In the GUI I could more easily determine if an existing Id3tag is indexed yes/no

![image](https://user-images.githubusercontent.com/250108/40911506-3ca9dbb6-67ef-11e8-8d1e-091c97b7db48.png)

**Comment by IrosTheBeggar** [comment]
I wouldn't put it there, in order to keep the design clean.  I can add a modal that has all the ID3 info, and have a show more link added to the UI

**Comment by aroundmyroom** [comment]
as long as there is an id to see if an song is indexed it is fine ;)
ie. a * is enough to see and find out where the indexing was stopped or gave an issue. The wierd thing is that the console shows me the last alphabetical folder with its songs, but than I am missing id3tags when playing songs from certain folders like explained earlier. so indexing does everything, but in between there is something happening not giving me the id3tags and covers from certain folders, if indexed alone those folders than I have all id3tags and covers.

**Comment by aroundmyroom** [comment]
will close this as my index issue is solved probably due to empty folders..
