### ISSUE TITLE
Can't build stream url properly?

### ISSUE THREAD

**Issue by WiseNN** [IrosTheBeggar/mStream#108]
Trying to simply test the streaming endpoint. 
my url: `http://localhost:3000/media/MotorSport.mp3`

I think this has something to do with the vPath.  I

Can someone please point me in the right direction. (Not using user accounts)

**Comment by IrosTheBeggar** [comment]
The vPath will default to 'media' in this case.  Your file path should look like:

```
http://localhost:3000/media/media/MotorSport.mp3
```

**Comment by WiseNN** [comment]
Thanks. Is there anyway to list the songs? I am trying to use `dirparser` but I am getting an error back. When I try to load songs using the playlist name `http://localhost:3000/playlist/load/:secondOne` I get an empty array back.

**Comment by IrosTheBeggar** [comment]
Hey, I'm going to refresh the demo sites soon.  The easiest way to see how calls work is to use the Chrome Dev Tools on the demo site to see the entire API calls
