### ISSUE TITLE
Music performance

### ISSUE THREAD

**Issue by MaxLeiter** [IrosTheBeggar/mStream#11]
Unsure if this can be improved, but the time to play a song/switch songs is pretty slow - can this be fixed by preloading the next queued song?

**Comment by IrosTheBeggar** [comment]
I'm actually working on this now.  It will  be a few weeks before it's done

**Comment by IrosTheBeggar** [comment]
This feature is done and I'm testing it now.   Should be released soon

**Comment by MaxLeiter** [comment]
Is it on master?

**Comment by IrosTheBeggar** [comment]
You can find it on this branch: 
https://github.com/IrosTheBeggar/mStream/tree/next-webapp

There's a lot of changes on that branch which is why it's taking so long

**Comment by IrosTheBeggar** [comment]
It's on the master branch now.

**Comment by MaxLeiter** [comment]
Fantastic - will check it out. Thanks

**Comment by IrosTheBeggar** [comment]
I pushed the new media player to the npm repository.  Closing ticket
