### ISSUE TITLE
new error starting mStream

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#115]
I see that mstream is eating resources of my VM ..
after updating to latest release and restarting with a fresh 'loki' database 

stderr: fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/mStream/image-cache/b185a8a8660878c1cfba76169e2bae29dbb1ad00ef378d2d91aecb0e170339f5.image/jpeg'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at ReadStream.<anonymous> (/home/mStream/modules/db-management/database-default-manager.js:200:14)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

child process exited with code 1

**Comment by IrosTheBeggar** [comment]
This is an interesting one, looks like the file extension is being set to 'image/jpeg' which is invalid.  Need some time to dig into why this is happening.  I'll also add some code to prevent this from crashing the scan thread

**Comment by aroundmyroom** [comment]
ok .. right now not able to use it ;) but can help debug ;)

**Comment by IrosTheBeggar** [comment]
This problem is caused by a change to the metadata library mStream uses.  I'm raised an issue there to get it fixed.  If I don't hear back soon, I'll add in my own workaround

**Comment by aroundmyroom** [comment]
is there a way to disable the metadata part? ;) 
its not that important for me at all ;) as files are played from folders the image or id3tag is not that interesting ;)
just tried the 2.6.0 version . damn .. not working as well ;)

**Comment by IrosTheBeggar** [comment]
Yea, I could add an option to disable all metadata scanning

**Comment by IrosTheBeggar** [comment]
Ok, this bug has been fixed.  Can you to see if your other DB tickets have improved at all.  Theres been a lot of small fixes to the DB code.  Still need to work on moving eveything to it's own thread though.

I'll work on adding the do not scan feature as well

**Comment by aroundmyroom** [comment]
will check the output of the screen ;) and what has been indexed.. A lot of music has been added / changed (will be every week) so will keep checking this .. 

First save to db has been done now

Access mStream on your local network: https://10.1.1.159:3000
stdout: database saved.
;)

**Comment by IrosTheBeggar** [comment]
BTW you still need to scan and parse metadata if you want AutoDJ to work.  It makes clever use of LokiJS to prevent songs from being played repeatedly.

Do you still want a skip scan feature?
