### ISSUE TITLE
Password for opening database doesnt work

### ISSUE THREAD

**Issue by AlGrande** [IrosTheBeggar/mStream#116]
I'm trying to open mstream.db or mstreamXdb.lite in an sqlite viewer but it asks for a password but the password I have set doesn't work.

**Comment by IrosTheBeggar** [comment]
mStream uses [lokiJS](https://github.com/techfort/LokiJS/stargazers) as it's database.  You can open the mstream.db in any text editor and see the contents, since they're all stored in JSON.
