### ISSUE TITLE
Add date/timestamp in cli for debug purposes?

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#119]
stdout: database saved.
please add date/timestamp so that I can track how long it take at certain moments to index files
With my amount of music files it can almost take (I guess) 24 hours for the total index of the db.
I have the feeling that after a certain point it goes slower. Also I do not see in the gui and update (right now 3200 items, but that cannot be 'true' 

Scan In Progress
3200 files in DB and is not updating

and I see that db is updated
22275699 Aug 19 06:53 mstream.db
22337463 Aug 19 06:57 mstream.db

**Comment by IrosTheBeggar** [comment]
Moving this to ticket https://github.com/IrosTheBeggar/mStream/issues/52, logging has always been a problem with mStream. Right now it just dumps everything to the console.  Needs a real log engine to replace that
