### ISSUE TITLE
db issue with memory? 

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#120]
after +36 hours it seems the indexing has become very slow

root   root   48507580 Aug 20 06:07 mstream.db
root   root   48569285 Aug 20 06:21 mstream.db

it took around 14 minutes to index 500 ? songs (which is probably one run of the output)
stdout: database saved.

load is also heavy.  So less issues seen what i have mentioned before but not the expected speed in indexing yet ;)

**Comment by IrosTheBeggar** [comment]
To solve all the memory/speed issues, I need to move all the DB code to it's own thread. It's the next big thing on my todo list, and it will also help solve https://github.com/IrosTheBeggar/mStream/issues/77

**Comment by aroundmyroom** [comment]
no probs , latest updates seems to have improved the GUI speed. Before the indexing was causing issues with the GUI performance now much less (but that can also be due to the initial db scan still not finished (that has be slown down dramatically) so in the ed this is already a win-win. and with your fix for a new thread it wil probably solve all ;)

**Comment by IrosTheBeggar** [comment]
I'm going to close the other DB tickets you have open, since it sounds like the only thing left to do the the threading rewrite.  let me know if there's any other issues I'm missing

**Comment by aroundmyroom** [comment]
update
db is now 78MB and not finished indexing yet (woowww !!) ;)
(only 145,790 songs in 4TB) LOL

**Comment by aroundmyroom** [comment]
Will close this issue for now, The app is super stable in playing the music, much better and the UI is also better responsive on clicks., 
Index ready yes/no no issue for me. I only probably want a feature to turn off the indexing cause the load is high on that VM box. if 4TB takes days to index, no issue but a re-scan must not go into high load at the end. And I think I will go into a loop at a certain point ;)
