### ISSUE TITLE
Indexing fails?

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#121]
stdout: Warning: failed to parse file '/media/music/Only 12 inches 7/Whitburn - 1988 (1 tm 50)/d1988_004a - Natalie Cole - Pink Cadillac (Club Vocal).mp3': Index out of range

stdout: Warning: failed to parse file '/media/music/Only 12 inches 7/Whitburn - 1988 (1 tm 50)/d1988_004c - Natalie Cole - Pink Cadillac (Radio Edit).mp3': Index out of range

child process exited with code 0

Dunno why there is a index out of range

**Comment by IrosTheBeggar** [comment]
Can you email me the files?

**Comment by aroundmyroom** [comment]
Just sent the files, I was a weekend away.

**Comment by aroundmyroom** [comment]
sent it to you gmail

**Comment by IrosTheBeggar** [comment]
Sorry, I've been really busy lately and let this slip. I tried the download link and it was expired.  Can you send them one more time?

**Comment by aroundmyroom** [comment]
Here once again https://we.tl/t-ztgkVJUtII
(no problem) ;)

**Comment by aroundmyroom** [comment]
I was using Ubuntu and saw still high loads, updated the box, saw issues with cloud-init, disabled those stuff and rebooted the machine. 

Initial index is stopping on Pink Caddilac, but is at that point within a few minutes. exited status 0
and no high load 
put the indexing on 0 (not 24) and will see what happens the next few days.
