### ISSUE TITLE
Load on server

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#124]
first of all using latest code:
when my dedicated VM for mStream is started and mStream is started all is ok.
I even see that when the indexinging stopps (exit status 0) mStream is running fine, all is quick and responsive. Still after 1 or 2 hours.

But overnight.. the box is doing nothing (really nothing) the load goes to 5.xx (right now 3.x after a restart) and mStream becomes unresponsive.  Even afters stopping / starting mStream it seems like memory is not cleared enough so it will get a high load quick after that again. Only a reboot seems to solve it for a couple of hours.

Dunno how to trace, track and debug this part .. 

![image](https://user-images.githubusercontent.com/250108/45469911-d6cc7380-b72b-11e8-90dd-2b2d93c042e6.png)

**Comment by IrosTheBeggar** [comment]
Sounds like a memory leak in the DB scan thread.  Did this just start happening after pulling the latest updates?

**Comment by aroundmyroom** [comment]
With this update. Before this update it was not 100% fast when I was remote, but it was possible to stream the whole day to my office. thats not possible anymore.

Right now the load is ok, but playing almost impossible
![image](https://user-images.githubusercontent.com/250108/45489197-f1224380-b763-11e8-9c53-0591cb41b22b.png)
I can see this as the loading of the 'folder' icons at the left is really slow as the loading of the intial 2 songs when using the DJ option (which I really like and use for this test).

Also in some situations the play button at the bottom left cannot load its svg .. so I get time-outs
Selecting another song (next in playlist), the update of the id3 image is slow, takes 10 to 20 seconds

just after start
![image](https://user-images.githubusercontent.com/250108/45489921-0ac48a80-b766-11e8-9e38-cbdebb425cf0.png)

timeouts
![image](https://user-images.githubusercontent.com/250108/45489983-33e51b00-b766-11e8-9ebb-a54f5211b177.png)

after 1 minute the song starts playing

scanning really quick stopped
![image](https://user-images.githubusercontent.com/250108/45490041-5d05ab80-b766-11e8-9d98-341c8bb88ae6.png)

after the scan the device becomes responsive. the slow loading with timeouts is over (but after x hours it is 'dead' .. 

![image](https://user-images.githubusercontent.com/250108/45490126-9b02cf80-b766-11e8-8dfc-1254b81b6558.png)

now it is playing fine
![image](https://user-images.githubusercontent.com/250108/45490938-b40c8000-b768-11e8-80ef-5d93fa4f5be7.png)

no load. Perfect ! .. 
but after x hours .. no go . .

in my config.json I have
 "interval": 0

as I do not want to scan it after the initial scan, but that is no solution ;)

**Comment by aroundmyroom** [comment]
here you see what happens after 16 hours not using the box

![image](https://user-images.githubusercontent.com/250108/45535818-0187fc00-b800-11e8-9d71-857719755f43.png)

Loading very slow and icons not loaded

![image](https://user-images.githubusercontent.com/250108/45535856-18c6e980-b800-11e8-8d28-ff44add1c237.png)

Actually load is dropping from 3.xx to below one

![image](https://user-images.githubusercontent.com/250108/45535968-5af02b00-b800-11e8-9f92-537c79a9b930.png)

Reload of GUI is missing icons
![image](https://user-images.githubusercontent.com/250108/45536015-7d824400-b800-11e8-82f5-33f56b225b8e.png)

Than starting DJ service gives more load

![image](https://user-images.githubusercontent.com/250108/45536088-b3bfc380-b800-11e8-90d4-d0bace30b525.png)

than after x seconds I see time-outs

![image](https://user-images.githubusercontent.com/250108/45536157-e8337f80-b800-11e8-90af-9396c4a99667.png)

In the end it will play but it takes 'ages' again to load the next song again

![image](https://user-images.githubusercontent.com/250108/45536269-3779b000-b801-11e8-9d46-6e1851c93881.png)

**Comment by IrosTheBeggar** [comment]
Ok, this is really interesting.  Just curious, when exactly did this start happening?  If we can find the commit that caused this we can see what went wrong.

Also can you tell me the last time it was working correctly?  I pushed a lot of updated for mStream dependencies and I'm wondering if that caused this

**Comment by IrosTheBeggar** [comment]
You can checkout an old version of mStream by specifying the commit number:

```
git checkout de4163bdacce016c2c4931413365b4878f9c8932  .
```

That will take you back a version to before the dependency updates.  You will have to delete you node_modules folder and re-run npm install


You can return to the most recent commits later by running

```
git reset --hard 
```

Can you try running that version and see if you have the same problem?

**Comment by aroundmyroom** [comment]
I believe it happend after
webapp better error handling commit
so the changes that (commits >=7 sep

**Comment by aroundmyroom** [comment]
I've installed mStream now on a debian image and gave it a little bit more memory (this image is meant for other stuff what can run in docker, but no experiment came by yet)
installation took some effort as under debian electron gives some trouble

sudo npm link and sudo npm install will not succeed 

you need
for electron you need
sudo npm install -g electron --unsafe-perm=true --allow-root
and for the npm link you need
sudo npm link --unsafe-perm=true --allow-root
otherwise it keeps failing

(nb, maybe it works with the --only-production flag, as I forgot that one from the guide

I do not like ubuntu as it comes with too much unused stuff for a 'server' like this.
So maybe my terrabytes of music is not handled by Ubuntu as like Debian, will now check the difference

See node info when starting 
dennis@docker:~/mStream-data$ /usr/bin/mstream -j /home/dennis/mStream-data/config.json
Donate to our Patreon: https://www.patreon.com/mstream
Access mStream locally: https://localhost:3000
Access mStream on your local network: https://10.1.1.131:3000
(node:10268) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

![image](https://user-images.githubusercontent.com/250108/45594867-13a1a000-b9a2-11e8-9071-1e15bd33ef55.png)

node and npm versions
dennis@docker:~/mStream-data$ npm -v
6.4.1
dennis@docker:~/mStream-data$ node -v
v10.10.0
dennis@docker:~/mStream-data$

**Comment by IrosTheBeggar** [comment]
Ok.  Just to be clear, did you install the old version of mStream (before Sept 7th)on this Debian image?

And electron is an optional dependancy.  I use it to compile the binary versions of mStream.  Using the --only-production prevents electron from being installed as a dependancy.

**Comment by aroundmyroom** [comment]
nope did not install the old version on the debian image
I did that on the ubuntu image, and the VM did not react as I wanted. it had the same issues.
 So all my complain could be related to a f*cked up server rather than something to blame the software.
So thats why I choose the other VM to be used.. 

Although I have still some 'scanning' issues for the db the system is very responsive. 
the db is now 46MB and still growing .. so will see what happens overnight.

**Comment by aroundmyroom** [comment]
so this new vm .. 
![image](https://user-images.githubusercontent.com/250108/45607557-7dc34f00-ba4d-11e8-83bf-dcc4b37e82c5.png)

indexing ready (1 time fail due to 'suddenly missing files what was existing', but did not care about that, restarted and now it looks all fine, including previous (nicole - pink caddilac) 



memory released and no load, mStream still responsive.

Will check later today (if possible) remote if all is working as expected

I say: ubuntu >/dev/null

ah after restart of mStream I started it again and .. 

stdout: Warning: failed to parse file '/media/music/Only 12 inches 7/Whitburn - 1988 (1 tm 50)/d1988_004a - Natalie Cole - Pink Cadillac (Club Vocal).mp3': The value of "offset" is out of range. It must be >= 0 and <= 2. Received 5

stdout: Warning: failed to parse file '/media/music/Only 12 inches 7/Whitburn - 1988 (1 tm 50)/d1988_004c - Natalie Cole - Pink Cadillac (Radio Edit).mp3': The value of "offset" is out of range. It must be >= 0 and <= 2. Received 5

child process exited with code 0
there is my Natalie again ;) now with more info ;)

**Comment by IrosTheBeggar** [comment]
I just pushed an update to mStream. It should help free up some memory usage during scans.  There's also some new options, such as the `skipImg` command.  It prevents the file scan from loading album art, which will save time and free up memory. You can see it in the docs https://github.com/IrosTheBeggar/mStream/blob/master/docs/json_config.md

I haven't tested the skipImg flag yet, everything else works.  Let me know if that helps at all

**Comment by aroundmyroom** [comment]
perfect
Will check it first with saveInterval: 500

Just saw that the machine was on a full load again with 100% memory usage of mStream
Did a remote git pull and changed the config.json accordingly
so I will check it again.

**Comment by aroundmyroom** [comment]
![image](https://user-images.githubusercontent.com/250108/45691854-afc1d780-bb59-11e8-9869-9c233fd94e35.png)
even more high load now.
mmm
I removed my db .. to see what happens .. 

dennis@docker:~/mStream-data$ /usr/bin/mstream -j /home/dennis/mStream-data/config.json
Donate to our Patreon: https://www.patreon.com/mstream
Access mStream locally: https://localhost:3000
(node:12875) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Access mStream on your local network: https://10.1.1.131:3000
stdout: File scan started at 1537279034163

no mstream.db is created ..

**Comment by IrosTheBeggar** [comment]
Just to be clear, is the mstream.db file being created in the older version of mStream?  What happens if you try running mStream on a folder with less than 10 files?

Also did it work as expected on the older versions (with no memory or CPU spike)?  Because if it did, it means one of the dependency upgrades is what's causing the problem.  If this it the case, I'll just roll back all the dependancies to the previous versions and things should go back to normal

**Comment by aroundmyroom** [comment]
mstream.db was created, I had removed the old(er) version, so a rescan

I will check it with a small folder
66 files

stdout: File scan started at 1537289740230
GMT: Tuesday 18 September 2018 16:55:40.230
stdout: database saved
true
stdout: File scan successfully finished at 1537289839074
GMT: Tuesday 18 September 2018 16:57:19.074
file scan completed with code 0

so it took 1 minute and 39 seconds for 66 files
with the skipimg function

rescan very quick
stdout: File scan started at 1537290374551
stdout: database saved
true
stdout: File scan successfully finished at 1537290374602
file scan completed with code 0

I will keep the db on 66 files for a few days to see if same issues happen as well
But I think it is the large number of files I have, 
the previous version (before you changed some db stuff) was indexing fine and was working fine for 1 or 2 days until a rescan (probably) caused high CPU usage.  I believe CPU <> Memory ;)

**Comment by IrosTheBeggar** [comment]
Ok, do you know which version was working as expected for you?  Commit number or date would be fine.  I can see what changes were made since then and figure out what's causing the CPU spike

**Comment by aroundmyroom** [comment]
ups.. put my replies in the other thread..

**Comment by aroundmyroom** [comment]
Will close this
Observation:
- Do not play music during initial scan
use
"saveInterval": 250,
    "skipImg": true
indexing of around 140.000 songs (around 4.5TB) takes 18 / 20 hours or so.
although the load is high during initial scan the db is created and accessible
Load goes to normal again after initial scan

Interval is set to
 "interval": 1
I see the db being 'saved' every hour (new timestamp)
rescan is very quick (1 or 2 minutes)

Very impressive behaviour right now.

**Comment by IrosTheBeggar** [comment]
@aroundmyroom 

I added a new database_plugin param called pause.  It sets a pause (in milliseconds) between fie parsing during the scan.  It will lengthen the length of the scan, but should prevent mStream from hogging all the system resources
