### ISSUE TITLE
child exited with status 0 after scan, db not released?

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#125]
Just an observation,

I saw that after a child exited with status 0 (end of scan?) the db was not given free?

mStream is responsive but songs where not shown with its id3tag.
restart mStream solved that issue. the same songs now with id3tag being played

hard to reproduce I believe, therefor an observation, it might be something in the process.

**Comment by aroundmyroom** [comment]
Oei .. difficult .. 
1. d8654ba175b6acd60d489890d35c86e6a6c3dd1c was working fine for 1 day during scan and play music
after that spikes in CPU usage and mStream unresponsive

2. d8654ba175b6acd60d489890d35c86e6a6c3dd1c
was working ok, but between those 2 version: nope

this version
fb11c072a535f549af428b9202b3c058d93fe551
kept on working but slow, 

So the scan is saving around 80MB of data, than the exit and I have no idea my music has been scanned totally.

So I believe that the scanning is causing issues.  I can handle a no scan of the db as long as DJ service can be kept running ;)

I even believe that after the scan has been stopped with the error, it might causing a loop and than spiking the CPU

**Comment by aroundmyroom** [comment]
I have now 166 files in 1 folder .. with the error file(s) as well

Donate to our Patreon: https://www.patreon.com/mstream
Access mStream locally: https://localhost:3000
Access mStream on your local network: https://10.1.1.131:3000
(node:13594) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
stdout: File scan started at 1537297651567
stderr: Warning: failed to parse file /media/music/test/d1988_004a - Natalie Cole - Pink Cadillac (Club Vocal).mp3: The value of "offset" is out of range. It must be >= 0 and <= 2. Received 5

stderr: Warning: failed to parse file /media/music/test/d1988_004c - Natalie Cole - Pink Cadillac (Radio Edit).mp3: The value of "offset" is out of range. It must be >= 0 and <= 2. Received 5

will see what happens with mStream

**Comment by aroundmyroom** [comment]
is this hash normal?

 {
          "title": "undefined",
          "artist": "undefined",
          "album": "undefined",
          "filepath": "/media/music/test/d1988_003c - Will To Power - Say It's Gonna Rain (808 Capella).mp3",
          "format ": "mp3",
          "track": null,
          "disk": null,
          "filesize": 4755578,
          "modified": 1505763766000,
          "created": 1537297507957,
          "hash": "59e22b6b0398947ccbb68f2544b5d8fa38b8b6f113691dd161afc55c85 b1754d",
          "vpath": "AroundMyMusic",
          "rating": 0,
          "lastPlayed": 0,
          "meta": {
            "revision": 0,
            "created": 1537297656110,
            "version": 0
          },
          "$loki": 9
        },

with the space?

**Comment by aroundmyroom** [comment]
aha .. nice .. do not start playing music when indexing.. 2 threads eating up everything.. 
![image](https://user-images.githubusercontent.com/250108/45713061-5627d000-bb8e-11e8-8542-39f5b61b5697.png)
this looks better..  mstream not serving music files through browser.. 

keeping fingers crossed ;)

**Comment by IrosTheBeggar** [comment]
Ok, are you running this on a "single core" VM?   mStream offloads all the scanning to a seperate thread to prevent the main thread from being slowed to a crawl.  But if there's only one core, than it's possible the second thread is hogging all the CPU resources preventing the main thread from responding to requests

**Comment by aroundmyroom** [comment]
nope .. 

![image](https://user-images.githubusercontent.com/250108/45732064-ee4ba680-bbda-11e8-850e-7e0c6a335ef9.png)

![image](https://user-images.githubusercontent.com/250108/45732230-9f524100-bbdb-11e8-828f-263bba0b45eb.png)

i see that the box has still a fair amount of load which seems to me similar to 8 hours ago (logon to the box caused a little spike, so I do not take that into account).

Its almost half way through now so I will check it later .. Testing with small amounts of files have no issues ..

**Comment by aroundmyroom** [comment]
dot not apply anymore as it seems the issues are related between

- initial scan
- playing music during initial scan
this is causing high load and than my system went nuts
now after initial scan not playing music and the latest updates the cpu load seems ok
