### ISSUE TITLE
New Error during scan

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#126]
`
lid characters
Warning: failed to parse file /media/music/Only 12 inches #Uitzoeken#/Nile Rodgers - 2013 - Presents The Chic Organization Up All Night (The Greatest Hits) Disc 2/Nile Rodgers - 2013 - Presents The Chic Organization Up All Night (The Greatest Hits) Disc 2/12 - Diana Ross - My Old Piano.wav: FourCC contains invalid characters
Warning: failed to parse file /media/music/Only 12 inches #Uitzoeken#/Nile Rodgers - 2013 - Presents The Chic Organization Up All Night (The Greatest Hits) Disc 2/Nile Rodgers - 2013 - Presents The Chic Organization Up All Night (The Greatest Hits) Disc 2/13 - Chic - Chic Cheer.wav: FourCC contains invalid characters
Warning: failed to parse file /media/music/Only 12 inches #Uitzoeken#/PC1/01 – Mega Phil Collins & Genesis Part 1.wav: FourCC contains invalid characters
Warning: failed to parse file /media/music/Only 12 inches #Uitzoeken#/PC1/02 – Mega Phil Collins & Genesis Part 2.wav: FourCC contains invalid characters

stdout: {"msg":"database saved","loadDB":true}{"msg":"File scan successfully finished at 1537368146788"}
/home/dennis/mStream/modules/db-management/database-master.js:77
      if(json.loadDB === true) {
              ^

TypeError: Cannot read property 'loadDB' of undefined
    at Socket.forkedScan.stdout.on (/home/dennis/mStream/modules/db-management/database-master.js:77:15)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

`

**Comment by aroundmyroom** [comment]
rescan .. 

stderr: Warning: failed to parse file /media/music/test/d1988_004c - Natalie Cole - Pink Cadillac (Radio Edit).mp3: The value of "offset" is out of range. It must be >= 0 and <= 2. Received 5

stdout: database saved
true
stdout: File scan successfully finished at 1537376114086
file scan completed with code 0

no clue if this db is now fully initialized ( I think so)
subsonic says: 143,464 songs
mstream says: 141,312 songs .. 

Ok lets see what is happening now ;)

oh oh .. 
this
tderr: Warning: failed to parse file /media/music/test/d1988_004c - Natalie Cole - Pink Cadillac (Radio Edit).mp3: The value of "offset" is out of range. It must be >= 0 and <= 2. Received 5

stdout: {"msg":"database saved","loadDB":true}{"msg":"File scan successfully finished at 1537376221239"}
/home/dennis/mStream/modules/db-management/database-master.js:77
      if(json.loadDB === true) {
              ^

TypeError: Cannot read property 'loadDB' of undefined
    at Socket.forkedScan.stdout.on (/home/dennis/mStream/modules/db-management/database-master.js:77:15)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

2 times restart, now it keeps running.

**Comment by IrosTheBeggar** [comment]
Ok, found the problem with this. It's related to some of the changes I made.  Will have a patch out later tonight

**Comment by IrosTheBeggar** [comment]
Ok, the fix for this has been pushed

**Comment by aroundmyroom** [comment]
solved !
