### ISSUE TITLE
Failed to play song

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#127]
![image](https://user-images.githubusercontent.com/250108/45812110-26ccac80-bccf-11e8-94d1-8494edbaeada.png)

Adding a whole folder with songs in random mode is causing this behaviour .. ;-)
No idea why the songs cannot be played. Other flac files no issue. as seen in the image, the Id3tag is a valid one ;)

**Comment by IrosTheBeggar** [comment]
What's the error that shows in the console?

**Comment by aroundmyroom** [comment]
thats this .. 
it is repeated time after time due to the 'random' selection, if not than 1 time
in the console

![image](https://user-images.githubusercontent.com/250108/45836334-d6743f80-bd0c-11e8-870a-1be4b5477076.png)

**Comment by aroundmyroom** [comment]
When in DJ mode when there is a song error, playback is stopped

![image](https://user-images.githubusercontent.com/250108/45881058-54d2ef00-bdaa-11e8-89ec-525f1d834033.png)

**Comment by aroundmyroom** [comment]
need to manually select the next song.  no reason why there is a song error ;)

**Comment by aroundmyroom** [comment]
latest version in DJ mode stopped playing

![image](https://user-images.githubusercontent.com/250108/45945083-9fdc4480-bfec-11e8-95f7-e2cbf055a27b.png)

the song is not played, when selecting the next song I see the red part and the next song is played
but no reason other than 'nope' is put in the console

**Comment by IrosTheBeggar** [comment]
I'm having no luck reproducing this bug on my system.  Any chance you can send me a video ?

**Comment by aroundmyroom** [comment]
Ive removed the whole wrong album,
but try this
https://we.tl/t-v7owpbRJMu

its the rozalla number it will fail. But no idea why. It might be with the flac decoder?

**Comment by IrosTheBeggar** [comment]
I checked out that song and it won't play in chrome or firefox.  Weirdly, it plays just fine in safari.   I tested this by just making a blank page with an `<audio>` tag with that file.  It's not an mStream problem, it's a Chrome/Firefox bug.

I submitted this the Chrome's bug log: https://bugs.chromium.org/p/chromium/issues/detail?id=891179

**Comment by IrosTheBeggar** [comment]
Also submitted it to Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1495648

**Comment by aroundmyroom** [comment]
Great! .. Wonder what the main cause is ;) 
So in short the bahaviour from mstream is expected, it cannot play the song. It should move on to the next song if such error occurs ;) But of course "we" want to have those files played .. .

extremely happy with the stability right now. Almost no load and hourly my db is being indexed correctly !

**Comment by IrosTheBeggar** [comment]
If other have files that won't play, you can drag and drop them into a new browser tab.  If they play with this method, it's an mStream problem.  If they don't play, then it's a browser problem
