### ISSUE TITLE
request: show filename if id3tag is empty

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#128]
Title: undefined
Artist: undefined
Album: undefined
if possible: when Id3tag is empty the info is stored this way in the db, but if possible if title and artist is undefined show the filename in the play field
maybe with an * in front so that you know that mStream did actually notice it had no id3tag (show difference between indexed and non indexed files)

![image](https://user-images.githubusercontent.com/250108/45862744-6a78f200-bd73-11e8-9907-4f3f33b700d9.png)

**Comment by IrosTheBeggar** [comment]
This is fixed now

**Comment by aroundmyroom** [comment]
ok, that seems to me a rescan of de db is needed. Lets do that and test ;)

**Comment by aroundmyroom** [comment]
db indexed, music playing as wanted .. no info in de id3tag field en the playbar gives me the name of the file

![image](https://user-images.githubusercontent.com/250108/45938564-634c2100-bfcb-11e8-9473-1d1f20012721.png)

great!
