### ISSUE TITLE
skipImg": true to false gives no new indexing images

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#129]
it looks like if you set

"skipImg": false
than a restart of the application will not start indexing the images again.m (if there is a database already)

**Comment by IrosTheBeggar** [comment]
This expected. Scanning for images requires a complete rescan from scratch (since you have to parse the metadata of each file).  When rescanning the files, mStream will only parse for metadata if the file is not in the DB or if the file has been modified since the last scan.

**Comment by aroundmyroom** [comment]
check!
than I will test the build of the database again with skipImg=false as I am really satisfied with the indexing and playing of songs with this latest version. Almost no load after the initial scan is finished
Will check if the write / read of id3tag can be 'the' issue (if still there), but that is why I'm testing ;) will close this issue as it is intended l)
