### ISSUE TITLE
Experience indexing with img

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#130]
Indexing with Img:
it looks like the server (for playing the music) itself did not run until the scan was completed.
no issue here for me, I wait .. . Initial scan seemed to have stopped in the morning, no output at all in my shell console. Restart of the application solved that and around 20 minutes ago the whole system has been indexed

140383 files now in the db .. every hour the index will be refreshed and the load is ok now..

So far I am really happy with the updates made. 4.78TB of music ..

**Comment by IrosTheBeggar** [comment]
I added a `pause` option for the indexing:

```
  "database_plugin":{
    "pause": 50
  },
```

This will add a 50 millisecond pause between each file during the scan. It will make the scan longer, but it might free up enough system resoruces to make mStream usable during this period

**Comment by aroundmyroom** [comment]
I've seen it and was using it ;)

{
  "port": 3000,
  "database_plugin":{
    "dbPath":"/home/dennis/mStream-data/mstream.db",
    "interval": 1,
    "saveInterval": 250,
    "skipImg": false,
    "pause": 50

but to test it again I have to re-index for more than 1 day again .. (only when necessary) ;)
