### ISSUE TITLE
[Feature Request] add single song to a playlist

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#131]
Add a single song from the file list to a playlist (and if possible from the playmenu as well)
When in DJ mode, you will hear a lot of nice songs. If you can select it during play and add it to a playlist it is directly stored.

Now you have to load a playlist, add the song, and resave the playlist again
(you can only add a directory to a playlist. I want to be able  to have single songs added to a playlist)

**Comment by IrosTheBeggar** [comment]
Done
