### ISSUE TITLE
Password Store

### ISSUE THREAD

**Issue by jugendhacker** [IrosTheBeggar/mStream#133]
Im not sure, but as I can see the passwords are stored as plain text in the config file, right? Wouldn't it be better to store it as a kind of hash and in some kind of database so that useres can easily change their own password and admin can't see it?

**Comment by IrosTheBeggar** [comment]
You can use the --adduser flag to programmatically add user to the config file.  This will hash the password automatically:
```
mstream -j config.json --adduser
```

**Comment by jugendhacker** [comment]
Ok thank you that was the option I was searching for
