### ISSUE TITLE
Request feature: remove single song from playlist

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#134]
adding song from playlist was added (yeah!) in one of latests commits, but we need also a removal of a single song from that saved playlist .. 

sometimes you make mistake so you add, but want to remove it, now not possible (or it is possible, but I do not see that feature.

Put this request in the commit of the add part, but that was wrong ;)

**Comment by IrosTheBeggar** [comment]
Side  note: the playlist objet needs to be repopulated after saving/deleting a new playlist

**Comment by IrosTheBeggar** [comment]
Done

**Comment by aroundmyroom** [comment]
Looking great !.. 
important: refresh cache of browser due to various js changes.  just did a quick test this morning..
