### ISSUE TITLE
info needed: logfile

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#135]
the new option -L logfile is great
but question, is it saving the data in several logfiles and/or wil it gzip it?

every hour my logfile will show data of files not being indexed so,  +230Kb worth of info ;)
If the logfile will be too big it will be hard to look for as the log seems in json as well.

Feature is + !! love it

**Comment by IrosTheBeggar** [comment]
The logging is pretty simple right now.  It just writes everything to the file you specify
