### ISSUE TITLE
is Microsoft Edge supported? 

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#138]
I had some issues with Chrome today so I tried to see if it was related to the browser
under Microsoft Edge I get an script error and do not see the login page

![image](https://user-images.githubusercontent.com/250108/46859947-7b1b0600-ce0f-11e8-902a-9f6884a324e7.png)

File dropzone.js

for (let tagName of ["div", "form"]) {
        var fallback;
        if (fallback = getFallback(this.element.getElementsByTagName(tagName))) {
          return fallback;
        }
      }
    }

**Comment by IrosTheBeggar** [comment]
I haven't tested on edge in a long time. It used to work.  Looks like adding dropzone for file uploading broke something.  I'll look into at some point

**Comment by IrosTheBeggar** [comment]
I updated dropzone and this has ben fixed.  Works on internet explorer too (though it's slow as shit on IE)
