### ISSUE TITLE
Add to playlist not loaded correctly

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#139]
Initial start of browser
I want to add a file to a playlist, my existing playlist does not exist
![image](https://user-images.githubusercontent.com/250108/46954516-1bcc2880-d091-11e8-950c-e2fd33d4d933.png)

I refresh my browser .. 
Now I can 
![image](https://user-images.githubusercontent.com/250108/46954561-38686080-d091-11e8-9db0-9de12564ad59.png)

**Comment by IrosTheBeggar** [comment]
Yea, need to fix that. You can also hit the playlist button on top to get around this.  That way you don't need to refresh the app

**Comment by IrosTheBeggar** [comment]
Fixed
