### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jugendhacker** [IrosTheBeggar/mStream#140]
I get a assign to constant variable error [on this line](https://github.com/IrosTheBeggar/mStream/blob/master/modules/file-explorer.js#L126) this shouldn't be right?

**Comment by IrosTheBeggar** [comment]
Fixed it.

It's doing string concatenation which means the variable is being reassigned.  Turns out the webapp calls it in such a way that the if condition is never hit, so I just never saw the error.
