### ISSUE TITLE
error code 

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#144]
2018-10-26T06:39:48.783Z info: Access mStream on your local network: https://10.1.1.131:3000
TypeError: Cannot read property 'find' of undefined
    at getPlaylists (/home/dennis/mStream/modules/db-read/database-public-loki.js:210:39)
    at mstream.get (/home/dennis/mStream/modules/db-read/database-public-loki.js:96:23)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dennis/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/dennis/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/dennis/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/dennis/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dennis/mStream/node_modules/express/lib/router/index.js:275:10)
    at jwt.verify (/home/dennis/mStream/modules/login.js:149:7)
TypeError: Cannot read property 'find' of undefined
    at getPlaylists (/home/dennis/mStream/modules/db-read/database-public-loki.js:210:39)
    at mstream.get (/home/dennis/mStream/modules/db-read/database-public-loki.js:96:23)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dennis/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/dennis/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/dennis/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/dennis/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dennis/mStream/node_modules/express/lib/router/index.js:275:10)
    at jwt.verify (/home/dennis/mStream/modules/login.js:149:7)

updated to latest commit
initially: mStream starts quickly and I can login
DJ mode gives an error 500 on the random part (access denied)
trying to browse my folders goes ok and I am playing a song. So far so good
Trying to start DJ mode again, no go...
than I notice that after 1 or 2 minutes the webserver (UI) is again unresponsive and I see above error in my console.

**Comment by aroundmyroom** [comment]
a restart shows me that mStream is not serving me a webUI, so webserver is locked up again. and is slow
no further output in the console.
and as expected after around 9 minutes my load drops again and the webserver is responsive and mStream is running as expected.

**Comment by IrosTheBeggar** [comment]
that error has been fixed in the latest commit

**Comment by aroundmyroom** [comment]
Paul, 

I am still having following issue

![image](https://user-images.githubusercontent.com/250108/47600610-74ba8b80-d9c4-11e8-8125-ab794f198faa.png)

What you see is: mStream comes up with the UI after I restarted the prg in my console.
You see I am unauthorized as I enter an invalid password, all expected, you see that I am getting error 500s again, this is when pressing the DJ button at the bottom right. During these errors I am able to scroll to my folders and select 1 or 2 songs and play them.

Than after avg 2 minutes the webUI again is unresponsive and does not react to any of my requests
I do not see any info in the log what is happening direct after the start and what is causing after 2 minutes the lockup

{"message":"Access mStream locally: https://localhost:3000","level":"info","timestamp":"2018-10-27T06:40:36.468Z"}
{"message":"File scan started on /media/music/","level":"info","timestamp":"2018-10-27T06:40:37.402Z"}
{"message":"Access mStream on your local network: https://10.1.1.131:3000","level":"info","timestamp":"2018-10-27T06:40:37.691Z"}

this log part is just normal output i see in my console as well, so not shocking.
It would be nice to see in the log at what part in the process the UI is getting locked up (Probably for 9 minutes still).

Cause this high load is probably causing the webserver to become unavailable

![image](https://user-images.githubusercontent.com/250108/47600648-278ae980-d9c5-11e8-98c1-8e53ed26a792.png)

and indeed after 9 minutes my DJ mode is again working fine

![image](https://user-images.githubusercontent.com/250108/47600683-91a38e80-d9c5-11e8-933f-aa41a1612619.png)

but now after one minute a timeout again

![image](https://user-images.githubusercontent.com/250108/47600698-ba2b8880-d9c5-11e8-98a2-8673d31bc655.png) (probably due to a sudden high load again, which is solved very quickly).

no 'write' to the db, also no need as there is no changing of files

![image](https://user-images.githubusercontent.com/250108/47600730-168ea800-d9c6-11e8-8131-4f9aa5f600d7.png)

**Comment by IrosTheBeggar** [comment]
I think what's going on is the server doesn't have enough resources for the initial boot.  It looks like the the program is dipping into SWAP memory which is slow (and since SWAP is on the filesystem that's being scanned, it's just that much slower).  This causes the server to stall until all the boot scan is done.

I'll create a branch to work on solutions to reduce to boot load.  I see some area for improvements but it's going to take some time to implement.  In the mean time can you try throwing some more resources at the VM?  Even an extra gig of memory might make a noticeable difference

**Comment by aroundmyroom** [comment]
I will try to test this paul .. will give it a Gig more but I do not fully understand why .. 

![image](https://user-images.githubusercontent.com/250108/47634722-cf81ed80-db52-11e8-9974-604a57079381.png)

this is on the rebooted machine, just a minute after the console says the server is available.

during that time I do not see swap being used

![image](https://user-images.githubusercontent.com/250108/47634808-0eb03e80-db53-11e8-9887-7fcd58b61218.png)

In fact I already gave the machine 1Gig more for some time and did not had this issue before for some time. giving it 3G would be a little too much in my opinion, but I will check if this will solve it.. *but I wanted first to see if the issue would be different after rebooting the VM (now around 7 min)

**Comment by aroundmyroom** [comment]
new memory

![image](https://user-images.githubusercontent.com/250108/47635159-51264b00-db54-11e8-976d-4d85a4c43b1b.png)

but indeed .. with 3G .. it solved the issue .. 

![image](https://user-images.githubusercontent.com/250108/47635297-c7c34880-db54-11e8-8ce1-63879e05ab97.png)

Here we see some more info .. 

![image](https://user-images.githubusercontent.com/250108/47635398-225ca480-db55-11e8-9f83-9e1d6228ef32.png)

Initially there is no info about the file scan after start .. last attempt really quick with 1G more

here with 10 min
![image](https://user-images.githubusercontent.com/250108/47635526-90a16700-db55-11e8-83c4-88b72ebfe881.png)

![image](https://user-images.githubusercontent.com/250108/47635609-e5dd7880-db55-11e8-8463-25feb82290f6.png)

So top does not show me why I would need 1G more as I still have 'enough memory free.
but ok .. for now I can live with it, all is 3Gb too much which I actually do not have available within the VM (sniff)

**Comment by IrosTheBeggar** [comment]
The problem is mStream uses a lot of memory on boot due to several things happening at once.  The biggest offender here is the scan thread which.   I will be making some improvements here as my next project.

I'll also add a a function to holds of the first scan for a period of time.  That way the server has time to recover all the memory during the boot so it can be reused for the scan thread

**Comment by IrosTheBeggar** [comment]
Ok the latest version has an option called `bootScanDelay`, you can see more about it here:https://github.com/IrosTheBeggar/mStream/blob/master/docs/json_config.md

The config file structure is changing slightly during the next major release.  You might see some depreciation warnings because of this

**Comment by aroundmyroom** [comment]
Update went successfull, have altered my json before the update so no deprecation warnings ;)

**Comment by aroundmyroom** [comment]
This can be closed as mStream is now starting and playing directly after start.
