### ISSUE TITLE
scanning 

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#146]
It seems that after the update of the config.json my db is not scanned at the time interval set

this is the log .. 
from start of mStream I only have these log entries:
{"message":"File scan started on /media/music/","level":"info","timestamp":"2018-11-02T13:13:51.640Z"}
{"message":"File scan message: database saved","level":"info","timestamp":"2018-11-02T13:14:31.106Z"}
{"message":"File scan completed with code 0","level":"info","timestamp":"2018-11-02T13:14:31.329Z"}
{"message":"File scan started on /media/music/","level":"info","timestamp":"2018-11-03T13:14:04.013Z"}
{"message":"File scan message: database saved","level":"info","timestamp":"2018-11-03T13:29:24.996Z"}
{"message":"File scan completed with code 0","level":"info","timestamp":"2018-11-03T13:29:25.401Z"}
{"message":"File scan started on /media/music/","level":"info","timestamp":"2018-11-04T13:13:59.430Z"}
{"message":"File scan message: database saved","level":"info","timestamp":"2018-11-04T14:02:37.189Z"}
{"message":"File scan completed with code 0","level":"info","timestamp":"2018-11-04T14:02:38.911Z"}
{"message":"File scan started on /media/music/","level":"info","timestamp":"2018-11-05T13:14:03.939Z"}
{"message":"File scan message: database saved","level":"info","timestamp":"2018-11-05T15:15:25.426Z"}
{"message":"File scan completed with code 0","level":"info","timestamp":"2018-11-05T15:15:27.517Z"}
{"message":"File scan started on /media/music/","level":"info","timestamp":"2018-11-06T13:13:56.365Z"}
{"message":"File scan message: database saved","level":"info","timestamp":"2018-11-06T13:35:10.051Z"}
{"message":"File scan completed with code 0","level":"info","timestamp":"2018-11-06T13:35:16.814Z"}
dennis@docker:~/mStream-data$ more config.json

This is the part of the config .. 
dennis@docker:~/mStream-data$ more config.json
{
  "port": 3000,
  "userinterface":"public",
  "scanOptions":{
    "scaninterval": 2,
    "saveInterval": 250,
    "skipImg": false,
    "pause": 50,
    "bootScanDelay": 60
  },

scaninterval is 2 but what the log shows is something different

**Comment by IrosTheBeggar** [comment]
try `scanInterval` with the i capitalized

**Comment by aroundmyroom** [comment]
ugh so simple? ..... changed it and restarted .. lets see .. I am convinced this is it ;)
