### ISSUE TITLE
CLI Remote

### ISSUE THREAD

**Issue by jugendhacker** [IrosTheBeggar/mStream#147]
Would it easily be possible to build into the node JS cli that it can play audio and that you can control it like the other remotes?

**Comment by IrosTheBeggar** [comment]
Are you talking about a separate CLI program that can search/stream/etc from the server.  It's totally possible.  And   Difficulty wise it wouldn't be too hard to build, though it would take time to get it with feature parity to the webapp.

I won't have time to start this until the mobile apps are done (there's a lot of people asking for those).  Someone else would need to lead this project

**Comment by jugendhacker** [comment]
What I talked about was: I have mstream running on a raspberry pi and this PI is connected to my speaker system. My current way to hear music in my room is streaming it to my PC via WLAN and then streaming it back to the RPI via Bluetooth. That isn't optimal and I thought about how cool it would be to control the PI via Webinterface and let him play the music directly on the speakers...

**Comment by IrosTheBeggar** [comment]
Yea, that's also possible.  It would need to be written as a separate server process that uses whatever audio playback system the computer has.  NodeJS can't play audio files by itself

**Comment by jugendhacker** [comment]
Didn't tested but found those two librarys that look pretty cool via a quick research:
https://www.npmjs.com/package/audio-play
https://github.com/TooTallNate/node-speaker

**Comment by jugendhacker** [comment]
Tommorow after 2PM UTC I could try to play around with those and eventually produce a PR if you want...

**Comment by IrosTheBeggar** [comment]
You're welcome to take a shot.  Test some libraries and let me now how it goes

**Comment by IrosTheBeggar** [comment]
Moving this to the Projects board:

https://github.com/IrosTheBeggar/mStream/projects/1
