### ISSUE TITLE
Podcast/audiobook support

### ISSUE THREAD

**Issue by IrosTheBeggar** [IrosTheBeggar/mStream#148]
I had this idea a while back.  Leave a comment if you're interested in this feature

**Comment by jugendhacker** [comment]
It sounds nice to fetch them via RSS and also with the android app you could sync them to your phone! It would be also cool to have a kind of local RSS Feed that you can fetch the pre downloaded podcast with your podcast reader/viewer

**Comment by aroundmyroom** [comment]
nope.. not needed.

**Comment by IrosTheBeggar** [comment]
Moved to projects page

**Comment by wuast94** [comment]
would love this feature. Audiobook support is the big thing that stops me from using this as my main audio player :) 

EDIT: Main features would be marked as played. and noticed where stops hearing.
