### ISSUE TITLE
Permission issue with --only=production

### ISSUE THREAD

**Issue by spff** [IrosTheBeggar/mStream#150]
I first do `npm install --only=production`
and error occurs when running `sudo npm link`
```
> electron@3.0.7 postinstall /home/spff/Desktop/mStream/node_modules/electron
> node install.js

/home/spff/Desktop/mStream/node_modules/electron/install.js:49
  throw err
  ^

Error: EACCES: permission denied, mkdir '/home/spff/Desktop/mStream/node_modules/electron/.electron'
```

It works if I do `npm install` instead.

I'm using fedora28, SHA1==a42cbe6

**Comment by IrosTheBeggar** [comment]
Thanks for the heads up.  I removed electron from the dev dependencies to avoid this problem in the future.  Electron is only there to compile the Express versions, and it not needed for regular usage.

I also just pushed the v4 update which improves a lot of frontend stuff,  you'll need to rerun `npm link` after upgrading.  Let me know if you have any more problems
