### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#155]
Logging is removed from Json, but how to enable it now? 
I do not see the CLI info written to the log folder 
even not when using the -L 

Not that I used it but I wondered how long it took for my system to index my +4TB of music (around 138K music files), it looks like just under 24h ;)

**Comment by IrosTheBeggar** [comment]
set the `writeLogs` option in the config

**Comment by aroundmyroom** [comment]
check!. That solved it.
