### ISSUE TITLE
Request: loading icon when loading artists and albums

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#156]
When I press artists or albums it takes around 15 tot 30 seconds before the page is being made
a user can think it is not loading, a load icon or 'please wait a moment .. would give some information that the select action was succesful.

Able to disable these menu function would also be ok for me ;)

**Comment by IrosTheBeggar** [comment]
There should that show up while loading now.  I'm keeping this ticket open because that kind of load time is way to long and can be reduced

**Comment by IrosTheBeggar** [comment]
I just pushed a change that should speed up the lookup time for artists/albums.  Let me know if it works for you.

**Comment by aroundmyroom** [comment]
yeah, that is working fine, within seconds I have the info ..
