### ISSUE TITLE
Download Song: access denied

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#157]
I See the arrow down, I do press it, I see an access deined
the element tells me this

Code d="M1803 960q0 53-37 90l-651 652q-39 37-91 37-53 0-90-37l-651-652q-38-36-38-90 0-53 38-91l74-75q39-37 91-37 53 0 90 37l294 294v-704q0-52 38-90t90-38h128q52 0 90 38t38 90v704l294-294q37-37 90-37 52 0 91 37l75 75q37 39 37 91z" code

**Comment by IrosTheBeggar** [comment]
Turns out it was only working for FLAC files. Should be fixed now

**Comment by aroundmyroom** [comment]
This has been fixed
