### ISSUE TITLE
feature request: ui buttons that allow the user to speed up or slow down audio track

### ISSUE THREAD

**Issue by 21eleven** [IrosTheBeggar/mStream#158]
Being able to play the audio faster (1.1x, 1.2x, etc) would be a boon to audiobook/podcast users.

**Comment by IrosTheBeggar** [comment]
I've thought about adding more support for audio books and podcasts.  There's another thread about it here: https://github.com/IrosTheBeggar/mStream/issues/148

**Comment by IrosTheBeggar** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/playbackRate

**Comment by IrosTheBeggar** [comment]
@NoahLidell The latest commit adds a button on the top nav bar to control playback speed.  It works on everything except Firefox.  Not sure why it's not working on Firefox, but this isn't the first firefox only audio bug

**Comment by 21eleven** [comment]
Just pulled down your latest changes, works like a charm on chrome for me. Thank you!
