### ISSUE TITLE
Add last.fm scrobbling

### ISSUE THREAD

**Issue by mateossh** [IrosTheBeggar/mStream#16]

**Comment by IrosTheBeggar** [comment]
I like this idea but  just don't have time to work on it in the foreseeable future.  Got a lot of other projects in the pipeline for now (like an Android App).  

I will start working on documenting mStream in case anyone else is interested in forking it and adding this

**Comment by IrosTheBeggar** [comment]
I'm finally getting around to working on this.  I will hopefully have it done within a week

**Comment by IrosTheBeggar** [comment]
LastFM scrobbling has been added to the master branch

You can set it up in the command line with the `-l` and `-z` flags 

```
mstream -l username -z password
```
