### ISSUE TITLE
Sound goes wrong with 24/192 flac

### ISSUE THREAD

**Issue by spff** [IrosTheBeggar/mStream#161]
I've tested couple files, the sound goes wrong.  

commit 7cc1b98

**Comment by IrosTheBeggar** [comment]
@spff Just to be clear, these files were working ok before the recent commits?

**Comment by spff** [comment]
Yes

**Comment by IrosTheBeggar** [comment]
@spff can you send me a file that's not working?

**Comment by spff** [comment]
http://111.251.40.45/
spff/superfrenchfries

This is a dynamic IP so it's safe to leave here ^ ^

you may try the /音樂/vivaldi

**Comment by IrosTheBeggar** [comment]
@spff 

what browser and OS are you using?

**Comment by spff** [comment]
Client
mac: mojave
Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by IrosTheBeggar** [comment]
@spff 

I've done some testing and this is a bug with Chrome, not mStream.  If you rollback mStream several commits, you will still see this problem.

I also tested those files on Firefox and Safari and they worked just fine.  I'm guessing chrome pushed an update recently that caused the problems

**Comment by spff** [comment]
Oh~~~ I confirm this by testing with Chrome on Windows and it works fine. 
Sorry for wasting your time. = =
