### ISSUE TITLE
missing icon and error in webamp (winamp)

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#162]
![image](https://user-images.githubusercontent.com/250108/49357950-343fe300-f6d1-11e8-91c8-3549c736f85e.png)

when in winamp mode I do not see an icon, as the path is not there .. (anymore)

and I see an error in the console mode of the browser (chrome)

![image](https://user-images.githubusercontent.com/250108/49358020-6e10e980-f6d1-11e8-82b3-a0cbd1aa775c.png)

**Comment by IrosTheBeggar** [comment]
Webamp took a hit for the v4 redesign.  You are right it needs some work
