### ISSUE TITLE
Pressing the back button on android exits the app

### ISSUE THREAD

**Issue by V1an** [IrosTheBeggar/mStream#166]
It would be lovely to assign another action (than leaving the app) to the back button on android.
Thanks a lot !

**Comment by IrosTheBeggar** [comment]
I'm working on a new version of the App using Flutter: https://github.com/IrosTheBeggar/mstream-flutter.  Progress has been quick, so hopefully this will replace the current app in a month or so.

I'll keep this in mind when making it

**Comment by IrosTheBeggar** [comment]
This has been resolved in the latest release: https://github.com/IrosTheBeggar/mstream-flutter/releases
