### ISSUE TITLE
Reverse Proxy with apache

### ISSUE THREAD

**Issue by floviolleau** [IrosTheBeggar/mStream#170]
Hi,

I would like to configure mstream behind a reverse proxy configured with apache.

My issue looks like what is mentionned in #64.

I have apache set up to serve everything through https but it gets messed up if I try to map it to a URL path and not a subdomain. The page will partially load because the formatting and graphics are not loaded due to the usage in the code of absolute paths.

I would like to use a /mstream path so that I can run this in parallel with other services. I just started to investigate apache configurations to see if there's a way to capture the missing resources in my reverse proxy set up.

If someone has a good configuration, please post it there.

Thanks for your help :) and the job done in mstream!

**Comment by IrosTheBeggar** [comment]
@floviolleau 

Got some bad news on this one. I had to make a hard decision about URL structure and mStream will not be able to support reverse proxying through path mapping.  It will only support reverse proxy through sub domains.  This has to do with the new RPN service that's being attached to mStream.

I can help you get mstream setup with an NGINX subdomain reverse proxy if you want
