### ISSUE TITLE
Shows 'null' instead of album name in the artists section

### ISSUE THREAD

**Issue by ghost** [IrosTheBeggar/mStream#171]

**Comment by IrosTheBeggar** [comment]
Thanks for pointing this out. Will look into it soon.

How's the performance on the Raspberry Pi Zero?  I added some optimizations for low powered board a while back, but I never tested is on a zero yet.

**Comment by PhoenixDiscord** [comment]
It takes a while (about two minutes) to build the database, but then it runs great. The CPU usage gets up to 40-50% while clicking on a song for 2 seconds.

**Comment by IrosTheBeggar** [comment]
Can you send me a file that is causing this bug?

**Comment by PhoenixDiscord** [comment]
What file? 
I think mStream dosen't have the enough metadata to display the album. What about making files like this hidden from the artists section or replacing "albums" with "songs"?

**Comment by IrosTheBeggar** [comment]
I'm traveling for work right now so I don't really have much to test with.  If you can send me a file where it shows up as a 'null' album, I can use it to see what's going on and write some code to improve it.

I might be able to figure it out without a file to test on, but I don't like committing changes without doing a real world test first.

**Comment by IrosTheBeggar** [comment]
Sorry for the delay, working on this now

**Comment by IrosTheBeggar** [comment]
Done!
