### ISSUE TITLE
Request to add an extra step to the installation process

### ISSUE THREAD

**Issue by LordZero25** [IrosTheBeggar/mStream#174]
Can you add the step to open the port online? This is a step that i spent the whole day searching in order to open my library online.

`[root@centos7 ~]# firewall-cmd --permanent --add-port=<portNo>/tcp
success

[root@centos7 ~]# firewall-cmd --reload
success`

**Comment by IrosTheBeggar** [comment]
@LordZero25 

Thanks for reporting this. This appears to be CentOS specific so I don't want to add it to the general install instructions.  I do think it is worth adding some OS specific instructions to the docs and linking them to the readme.

Would you mind writing up a doc on installing mStream from scratch for CentOS?  I'm traveling  for work right now so it will be a bit before I get to this.
