### ISSUE TITLE
how to debug mstream when not starting?

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#175]
just  installed nodejs 11 (?) after a VM died and the vm could not be repaired (shame on me)

Now installed nodejs did the npm install npm link but mstream will not give output or start at all.
what is wrong? and how to debug this?

**Comment by IrosTheBeggar** [comment]
I'll have to look into this, but for now you should stick to using node v10 since it's the current long term stable release

**Comment by aroundmyroom** [comment]
found it .. 
the cli-boot-wrapper.js got 0 bytes when pulled in one strange way
when I used npm start I saw some commandline passing and tought to try it and than I saw this file was 0 bytes which is the essential part of it all .. dueh .. 

can now go further installing it .. this afternoon
