### ISSUE TITLE
Feature request: add menu item: recently added xx items

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#176]
I would love to have a recently added feature for xx items. In this way I can quickly see which songs are added to my collection. A lot of times they are 'lost' in the +100.000 songs and I have to know the artist where I have stored it. With recently added for ie. the last 100 items I can see what is indexed and than I would love to play the new songs.

**Comment by IrosTheBeggar** [comment]
Working on this now

**Comment by aroundmyroom** [comment]
yes!!

**Comment by IrosTheBeggar** [comment]
done

**Comment by aroundmyroom** [comment]
Working fine !! .. Thanks for this feature !
