### ISSUE TITLE
Feature Request: LDAP Authentication

### ISSUE THREAD

**Issue by army1349** [IrosTheBeggar/mStream#177]
Please, add support for user authentication against LDAP backend.

**Comment by IrosTheBeggar** [comment]
Good idea. I don't have any experience with LDAP and could use some help with this

**Comment by army1349** [comment]
Sure, do you have abstract layer for user backend functionality?

**Comment by IrosTheBeggar** [comment]
Yea, all the user/login functionality is handled in `/modules/login.js`

The login functionality is pretty simple.  All user info is stored in the `program.users` variable. A user object looks something like this:

```javascript
program.users = {
  dave: {
    password: 'some_really_long_hash',
    salt: 'another_really_long_string',
    vpaths: ['...']
  }
}
```

At the bottom of the file there is some middleware that validates a users JWT and then adds that users info to the request variable so endpoints fro here out now the users info.  The middleware is  optional, and mStream can be booted without it (this allows anyone to access the server).  

Let me know if you have any more questions

**Comment by army1349** [comment]
OK, here is how could login.js look like for LDAP user backend: [login-ldap.zip](https://github.com/IrosTheBeggar/mStream/files/3057765/login-ldap.zip)
There is a question how to manage media directories with LDAP setup.

**Comment by IrosTheBeggar** [comment]
I'm moving this into the Project Ice Box.  It's a project I started for features I don't have the time to implement.  Hopefully someone else can pick them up and submit a pull request: https://github.com/IrosTheBeggar/mStream/projects/6

If you're interested in working on this further, you can check out the discord server to ask questions: https://discord.gg/AM896Rr
