### ISSUE TITLE
You need to make sure that /opt/mstream/chrome-sandbox is owned by root 

### ISSUE THREAD

**Issue by gerroon** [IrosTheBeggar/mStream#181]
HI

I am getting this with mStreamExpress-Linux-x64.tar.gz  v0.15

766:0501/192545.578434:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/mstream/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

I made sure it is owned by root and mode 4755 , still throwing the issue.

I am on Debian Buster.

**Comment by IrosTheBeggar** [comment]
@gerroon do you get the same error with previous versions?  I wonder if one of the dependancies I updated is causing this

**Comment by gerroon** [comment]
No, I did not with the previous version. I deleted the old version copied the new files and I have this issue. Sounds like an upstream Chrome thing maybe?

**Comment by IrosTheBeggar** [comment]
I'll be releasing a new version in the next few days that rolls back the dependency that's having problems

**Comment by IrosTheBeggar** [comment]
I just published v0.16. Let me know if that works for you

**Comment by gerroon** [comment]
Hi

This seems to be fixed
