### ISSUE TITLE
FR: Single click play

### ISSUE THREAD

**Issue by gerroon** [IrosTheBeggar/mStream#184]
Hi

It would be nice if there was an option to play the clicked song right away, atm it adds to the existing play list which is fine but that is not what the listener might want from that click behavior.

**Comment by pinkfloydFR** [comment]
Strongly agree, one button to play & one button to add in playlist will be much better :D

**Comment by IrosTheBeggar** [comment]
I finally got around to this and added a 'Play Now' button

**Comment by pinkfloydFR** [comment]
Finally found the problem, don't know why but process like "s6 lookup" was locked in memory, full restart of docker solved the problem !

Sorry for the issue opening...
