### ISSUE TITLE
Request: add content within 1 single folder with multiple sub folders to be played

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#187]
Right now you can only add the content from a singe folder to the playlist to be played

I have many folders where I have

[artist]
album 1
songs
album 2
songs
album 3
songs

I am unable to put the artist folder into the playlist to have all songs under the album1/2/3 to be played.

I would love to have that supported

**Comment by IrosTheBeggar** [comment]
Good idea, will add is as another button alongside the download button

**Comment by IrosTheBeggar** [comment]
This is working in the latest commit

**Comment by aroundmyroom** [comment]
Working fine !
