### ISSUE TITLE
Electron-builder ?

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#191]
what goes wrong here?

I tried to do a npm link but got an error
npm WARN lifecycle mstream@4.3.0~postinstall: cannot run in wd mstream@4.3.0 electron-builder install-app-deps (wd=/home/dennis/mStream) 

npm install did not help either
> electron-builder install-app-deps

sh: 1: electron-builder: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mstream@4.3.0 postinstall: `electron-builder install-app-deps`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mstream@4.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by lukaswozniak** [comment]
try `npm install electron-builder`, I guess there is a dependency missing

**Comment by aroundmyroom** [comment]
Installing is fine.. but when calling: npm link I still get

npm WARN lifecycle mstream@4.3.0~postinstall: cannot run in wd mstream@4.3.0 electron-builder instal|
l-app-deps (wd=/home/dennis/mStream)

**Comment by BeautyyuYanli** [comment]
the same problem

**Comment by IrosTheBeggar** [comment]
Just some growing pains while the compiled versions get moved over to a new build pipeline.  In the meantime you can run it by calling the boot script directly:

```
node cli-boot-wrapper.js -j /path/to/config.json
```

**Comment by IrosTheBeggar** [comment]
@aroundmyroom This should be fixed in the latest commit

**Comment by aroundmyroom** [comment]
yep .. npm link .. renew to the minor version, fix some security stuff .. it works now ;)
