### ISSUE TITLE
Request: search box: keep existing search keyword when returning

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#192]
Right now when searching a song within folders I type

'Armin' .. to search folders / songs of Armin .... 
the system shows me the folders matching the keyword. Now I select a folder and can select the song what I want
now I select 'back', I am back into the orignal (master) folder but without keyword, so I have to retype it to search for a 2nd folder with the same keyword.

It would be nice to keep your previous selection available so that you can search again with the same keyword. if you do not want it you can retype another keyword or make it 'clean' again.

**Comment by IrosTheBeggar** [comment]
This should be fixed and scroll position should be kept as well.  Give it a test and let me know if there's any problems

**Comment by aroundmyroom** [comment]
works fine !
