### ISSUE TITLE
Images are serving without resizing

### ISSUE THREAD

**Issue by pando85** [IrosTheBeggar/mStream#193]
First of all, thanks for share your work.

When you serve images from album-art it is serving with full size.
E.g.: 3MB images are served when 200KB images could do the same work.

**Comment by IrosTheBeggar** [comment]
A good idea, but it's not going to happen anytime soon.  Image libraries for node are usually C/C++ addons and I try to avoid those for maintence reasons.  They tend to not compile correctly on some hardware and I get all the bug reports.

I'm moving this to the Ice Box: https://github.com/IrosTheBeggar/mStream/projects/6#card-28353568
