### ISSUE TITLE
Android app: self-signed SSL cert support?

### ISSUE THREAD

**Issue by druexmachina** [IrosTheBeggar/mStream#195]
My mStream server can be accessed successfully via https://domainName:portNo (self-signed SSL cert) on both desktop and mobile browsers. Before I added the self-signed cert to the configuration, the mStream Android app had no issues connecting, but after adding the cert I get a 'could not connect to server' error within the app. The server can be accessed via mobile browser on the same device.

Is use of a self-signed cert supported in the app currently? If so, are connection attempts logged within the app backend somewhere that I can get a more specific error?

Thanks!

**Comment by jugendhacker** [comment]
I guess you'll need to import the self signed cert into androids trust
store...

**Comment by druexmachina** [comment]
Tried that as well - manually exported the cert from a desktop browser that was able to access the site and imported into the user-trusted store...same issue.

**Comment by IrosTheBeggar** [comment]
This sounds like it has something to do with the Flutter framework that’s used to build the app. It’s prob not respecting the imported certs on android for some reason.

I’ll see if I can raise a ticket on their git project

**Comment by IrosTheBeggar** [comment]
I released v0.0.6 of the new mobile app that has support for SSL certs

https://github.com/IrosTheBeggar/mstream_music/releases/tag/v0.0.6
