### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LordZero25** [IrosTheBeggar/mStream#197]
It says syntax error on [this line](https://github.com/IrosTheBeggar/mStream/blob/master/modules/ddns.js#L35)

[Screenshot](https://imgur.com/e0gbFF2)

**Comment by IrosTheBeggar** [comment]
@LordZero25 I've had no luck replicating this issue. What version of nodeJS are you using?

**Comment by LordZero25** [comment]
v6.17.1, The current version in CentOS.

I fixed this by including a Repo (https://rpm.nodesource.com/setup_10.x) and updating to v10.16.0.

**Comment by IrosTheBeggar** [comment]
I figured it was a problem with an old node version. I started using async/await which means you need v8 or greater.

I added a min version to the package json file.  It should give a clearer error next time someone runs into this
