### ISSUE TITLE
Make webamp an seperate page?

### ISSUE THREAD

**Issue by TETYYS** [IrosTheBeggar/mStream#201]
Would it be possible to emulate webamp to actually look like winamp? Maybe make it a seperate page? Not sure if you can hide browser titlebar and stuff

**Comment by IrosTheBeggar** [comment]
You'll have to talk to the guys who make webamp: https://github.com/captbaritone/webamp

I know thy have been working on a desktop application that does this.  Not sure what the progress is on that though.

You can also check out WACUP, a fork of the original Winamp: https://getwacup.com/
