### ISSUE TITLE
https trough android app not possible

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#202]
Got an older Samsung Galaxy tab today .. tried to connect to mStream over https (lets encrypt cert) but cannot connect to server is the message
When I change config to non ssl than the server is added and accessible.

2nd question, not rather bug report, is it correct I do miss the DJ play option in the android app?

**Comment by metasystem** [comment]
same problem here...
It would be cool that ssl works on android device...

**Comment by IrosTheBeggar** [comment]
@aroundmyroom @metasystem  there's a new android app available here:

https://github.com/IrosTheBeggar/mstream_music/releases/tag/v0.0.0

This has the latest network libraries and should work with SSL. Let me know if it works for you.

**Comment by IrosTheBeggar** [comment]
I'm closing this ticket since the new app is on Google play. If you still have a problem open up a new issue
