### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by clawoflight** [IrosTheBeggar/mStream#203]
How do playlists work?
My library contains .m3u lists with relative paths generated by beets, and mstream doesn't see them.

**Comment by aroundmyroom** [comment]
you have to select the songs what you want to have in a playlist save that and than you can play that list as a set.

I dunno if m3u can be supported cause the location of the file(s) must be accessible by mStream in order to be able to play the songs

**Comment by clawoflight** [comment]
Oh, I see.

What's the difference to normal playback though? Any files in the library already need to be accessible, no?

I think mstream could simply try to add tracks relative to the playlist file or relative from the library root. That shouldn't be hard.

**Comment by aroundmyroom** [comment]
could be ;) we will see wat the dev can answer ;)

**Comment by ghost** [comment]
would love to have some news on this too.

**Comment by IrosTheBeggar** [comment]
Hey, playlist support is a good idea for a for a feature.  Currently all playlists are stored in the local database.

**Comment by lukaswozniak** [comment]
Hey, I implemented playing and downloading m3u playlists, feel free to test my PR #214

**Comment by IrosTheBeggar** [comment]
This feature has been added. You can now see m3u files in the file explorer.  There are also some convenience functions for downloading and quick-adding m3u playlists to the queue.

And thanks to @lukaswozniak for working on this
