### ISSUE TITLE
Uninstall mStream from command line on Ubuntu

### ISSUE THREAD

**Issue by kalak-sudo** [IrosTheBeggar/mStream#204]
Hi!

I just installed mStream on Ubuntu following the cli-guide (https://github.com/IrosTheBeggar/mStream/blob/master/docs/install.md) and something went wrong. 

I would like to uninstall it and try a new fresh install. 

How do I uninstall using command line in Ubuntu Server?

Thanks in advanced!

Kalak

**Comment by IrosTheBeggar** [comment]
Hey Kalak,

That guide is out of date. You should install node v12, not v6.  The latest version of mStream doesn't even work with v6.

```shell
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
```

To uninstall mStream, you just need to delete the mStream folder

```shell
sudo rm -R mStream
```

All the installed files are put in the mstream folder you cloned from github.  This makes modifying and deleting mstream as easy as possible. To re-install mstream just you just have to start from scratch:

```shell
git clone https://github.com/IrosTheBeggar/mStream.git

cd mStream

# Install without dev dependencies
npm install --only=production

sudo npm link
```

**Comment by kalak-sudo** [comment]
Thanks @IrosTheBeggar  now everything is perfect. 

I suggested a new pull editing the node version from the tutorial, so nobody else with have this issue. 

Cheers!
