### ISSUE TITLE
Failed To Load JSON

### ISSUE THREAD

**Issue by linsui** [IrosTheBeggar/mStream#206]
When I run mstream on Windows from cli, I always get Failed To Load JSON even without any options. I can't pass any  parameters to mstream.

**Comment by IrosTheBeggar** [comment]
@linsui can you post a copy of the output.  Also is this for the UI version (express) or the cli version?

**Comment by linsui** [comment]
```
> mstreamExpress
 Failed To Load JSON
```

I run the gui version.

**Comment by IrosTheBeggar** [comment]
@linsui the the gui versions is not meant to be launched throuh the CLI.  The purpose of it is to be terminal free!  Params are passed in with the GUI interface

Also the `Failed to Load JSON` happens the first time you launch the app.  It looks for a JSON config, and makes one if it doesn't find it.

If you want to launch the app with the CLI, you should run the headless version with NodeJS

**Comment by linsui** [comment]
Thanks!
