### ISSUE TITLE
Database scan runs into "JavaScript heap out of memory" error and cancels the process

### ISSUE THREAD

**Issue by Nixbligger** [IrosTheBeggar/mStream#208]
Hello there,

I am picking up an issue from my other, meanwhile solved issue #200, where I run into these kinds of problems while scanning my music collection: 

> <--- Last few GCs --->
> re[2726:0x2649ab0]  5461327 ms: Mark-sweep 296.9 (299.1) -> 296.9 (299.1) MB, 1805.9 / 0.0 ms  (+ 0.0 ms in 1 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1808 ms) (average mu = 0.078, current mu = 0.002) finalize incre[2726:0x2649ab0]  5463095 ms: Mark-sweep 296.9 (299.1) -> 296.9 (299.1) MB, 1765.8 / 0.0 ms  (+ 0.0 ms in 1 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1767 ms) (average mu = 0.040, current mu = 0.001) finalize incre
> 
> <--- JS stacktrace --->
> 
> 
> 2019-09-27T11:22:46.325Z error: File scan error: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> 
> 2019-09-27T11:22:46.485Z info: File scan completed with code null

As a consequence, the scan process is stopped at some more than 2250 entries. I can see and play those through mstream without issues, but ~2250 is less than an fifth of my entire collection, unfortunately.

I repeat my questions from #200 here for convenience:

@IrosTheBeggar and others:
As I presume the database error might be related to some bad quality music files or tags - is there a way to check which of the files exactly causes the hangs? Is there some kind of logging?

Cheers,
Nix

PS: I attached a report file of a scan for debugging.
[report.20190817_edt.txt](https://github.com/IrosTheBeggar/mStream/files/3663120/report.20190817_edt.txt)

**Comment by IrosTheBeggar** [comment]
This is a new one.  I will ask the dev behind the metadata parser to see if he can help too.

I have some questions:

* What OS are you on?
* How much memory are you working with?
* What are ` Last few GCs` logs from.  That looks like it might have some useful information, but I've never seen anything like it before

And sorry for the late response.  I was taking some personal time away from development

**Comment by IrosTheBeggar** [comment]
@Nixbligger I updated the metadata parser for mstream.  Give it anther try and see if it works

**Comment by Nixbligger** [comment]
> This is a new one. I will ask the dev behind the metadata parser to see if he can help too.
> 
> I have some questions:
> 
>     * What OS are you on?
> 
>     * How much memory are you working with?
> 
>     * What are ` Last few GCs` logs from.  That looks like it might have some useful information, but I've never seen anything like it before
> 
> 
> And sorry for the late response. I was taking some personal time away from development

Hello Paul,
now it is me who likes to apologize for not being more responsive. I'll give the new build a try asap.
Regarding your questions:
- My OS:

**Comment by Nixbligger** [comment]
Hmmm, that was weird - used some hotkey combination to insert text and I was ending up with the thread being closed and a new comment opened. Sorry folks!!

Regarding your questions:
My OS is Raspbian stretch on a RasberryPi 2

```
$ uname -a
Linux raspi 4.14.27-v7+ #1100 SMP Fri Mar 16 13:51:48 GMT 2018 armv7l GNU/Linux

$ free
              total        used        free      shared  buff/cache   available
Mem:        1000212      641388       32348       21008      326476      405656
Swap:       1048572      597760      450812
```
'Last few GCs' was the cli output after the db scan cancelled, I think - I'll double check and report if it was something else. Then I check out your new build.

Thanks and best regards,
Nix

**Comment by Nixbligger** [comment]
> @Nixbligger I updated the metadata parser for mstream. Give it anther try and see if it works

Hey, 
it's me again - I realized that I might not be able to check out the new build with the updated metadata parser as I was using the relative_urls branch while experiencing the lock-ups. Without it I experience issue #200 :-) 

Cheers,
Nix

**Comment by IrosTheBeggar** [comment]
The Raspberry Pi 2 has 1 gig of somewhat slow RAM. Are you running servers other than mStream as well?

You can change some of the `scanOptions` paramaters in your config so reduce memory usage:

```
  "scanOptions": {
    "skipImg": true,
    "scanInterval": 24,
    "pause": 200,
    "saveInterval": 2000,
    "bootScanDelay": 30
  },
```

`bootScanDelay` will delay when the scan starts after boot (in seconds) . This gives the system time to garbage collect memory after boot

`pause` adds a pause (in millesconds) between each file scan.  This again gives the system time to do garbage collection

`skipImp` simply skips al image handling and disables album art.  Give this a try if nothing else works

`saveInterval`  sets how many records should be scanned before updating the DB on the main thread. Reloading the DB on the main thread takes memory, so set this to a really high number to avoid it

**Comment by IrosTheBeggar** [comment]
I know this thread is pretty old. But there's a new issue for improving memory usage here: https://github.com/IrosTheBeggar/mStream/issues/317

**Comment by IrosTheBeggar** [comment]
The new scan code in v5 is much more memory efficient. Closing ticket
