### ISSUE TITLE
added to another list

### ISSUE THREAD

**Issue by Riajyuu** [IrosTheBeggar/mStream#21]
Hi, I'm maintainer of  https://github.com/EMLVIRUS/Amazing-Windows-Apps
Can I list you job into my list as well?

**Comment by IrosTheBeggar** [comment]
Yea, that's fine

**Comment by Riajyuu** [comment]
I have create the [issue](https://github.com/EMLVIRUS/Amazing-Windows-Apps/issues/81) and if you don't mind I'm listing it into [Audio](https://github.com/EMLVIRUS/Amazing-Windows-Apps/blob/master/audio.md) category

If any other request, just let me know
