### ISSUE TITLE
mstreamExpress-win32-x32

### ISSUE THREAD

**Issue by xlab25** [IrosTheBeggar/mStream#210]
Is there a 32bit portable version of mstream. Indeed I would like to install it on a windows 7 32bits embedded.

**Comment by IrosTheBeggar** [comment]
No, I might release one for the next version.  I'm switching to a new build pipeline now that might support it.  Need to dig into it further.

You can try installing the CLI version.  It requires some extra work to get the boot on startup feature working, but it runs even leaner than the binary version

**Comment by xlab25** [comment]
hello Paul
 i found this solution at this address : https://github.com/electron/electron-packager/issues/444
Could it work with mstream

Thanks

________________________________
De : Paul <notifications@github.com>
Envoyé : vendredi 11 octobre 2019 18:20
À : IrosTheBeggar/mStream <mStream@noreply.github.com>
Cc : xlab25 <xlab25@msn.com>; Author <author@noreply.github.com>
Objet : Re: [IrosTheBeggar/mStream] mstreamExpress-win32-x32 (#210)


No, I might release one for the next version. I'm switching to a new build pipeline now that might support it. Need to dig into it further.

You can try installing the CLI version. It requires some extra work to get the boot on startup feature working, but it runs even leaner than the binary version

**Comment by IrosTheBeggar** [comment]
Good news, this is both possible and automatic now: https://www.electron.build/configuration/nsis#32-bit-64-bit

I'll be releasing a new version soon

**Comment by IrosTheBeggar** [comment]
@xlab25 

Try this release and let me know if it works for you:
https://github.com/IrosTheBeggar/mStream/releases/download/v4.5.1/mStream.Server.Setup-4.5.1.exe

**Comment by xlab25** [comment]
Thanks

Le 4 nov. 2019 06:13, Paul <notifications@github.com> a écrit :

Good news, this is both possible and automatic now: https://www.electron.build/configuration/nsis#32-bit-64-bit

I'll be releasing a new version soon

**Comment by IrosTheBeggar** [comment]
The official v4.5.1 with x32 bit support is here:

https://github.com/IrosTheBeggar/mStream/releases/tag/v4.5.1
