### ISSUE TITLE
cli_argguments.md has wrong switch for logs

### ISSUE THREAD

**Issue by RoyceTheBiker** [IrosTheBeggar/mStream#211]
The documentation section for 'Choose Log Directory' has the documentation for setting the DB path.

Reading modules/config/configure-commander.js shows the option should be -A to set the log path.

**Comment by IrosTheBeggar** [comment]
That's correct. I tested it just to make sure.  Let me know if it's causing a bug on your machine

**Comment by RoyceTheBiker** [comment]
The default path for logs is mStream/save/logs, according to the README.md there. No log files were showing up so I used '-A' to set ~/tmp/ for logs but no logs were created there either.

It could be that there is nothing to log, but I am trying to work out why only some of my music plays and some give an error #212 

I will keep tinkering with it.

Thank you.

**Comment by IrosTheBeggar** [comment]
Did you use `-L -A /path/to/logs`?  The -L tells it to write logs and -A tells it where.

**Comment by RoyceTheBiker** [comment]
I missed that at the bottom on the docs page. The -L switch works. 

Thanks.
