### ISSUE TITLE
Failed to play song

### ISSUE THREAD

**Issue by RoyceTheBiker** [IrosTheBeggar/mStream#212]
Howl is giving an error. It is just like issue #127 

This only happens with about half of the songs, the rest are working just fine. 

I cannot get any logs to be generated on the server-side. I don't think it is server related, permissions are all identical. I can use the mStream WSI to download songs that will not play in the browser and then they can be played locally using VLC. Issue #127 had a note about testing by dragging the track to the browser location bar to see if it plays but I tried dragging object off the mStreamer page but cannot get anything draggable. 

I added some extra console.log lines to see if I could find where the problem was but I have not used [Howler](https://github.com/goldfire/howler.js) before so I don't know what to look for. 

This is the console log.
```
song.url = '/media/music/Alphabetical/3/3 Doors Down/2001 - Now, Vol. 8/3 Doors Down - Kryptonite.mp3?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJveWNlIiwiaWF0IjoxNTcxMDEzODE3fQ.UVab6LRgbx6ZKeq9SkJhouTfiq9tZEo9fIrIj2NPYr4'
mstream.player.js:639 SONG ERROR
mstream.player.js:434 DOMException: Failed to execute 'createMediaElementSource' on 'AudioContext': HTMLMediaElement already connected previously to a different MediaElementSourceNode.
    at goToSong (http://asus-rog-vm.bighouse:3000/public/js/mstream.player.js:429:31)
    at goToNextSong (http://asus-rog-vm.bighouse:3000/public/js/mstream.player.js:350:12)
    at onloaderror (http://asus-rog-vm.bighouse:3000/public/js/mstream.player.js:651:11)
    at o.<anonymous> (http://asus-rog-vm.bighouse:3000/public/js/lib/howler.core.js:2:18777)
mstream.player.js:617 song.url = '/media/music/Alphabetical/3/3 Doors Down/2002 - Away from the Sun/3 Doors Down - Here Without You.mp3?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJveWNlIiwiaWF0IjoxNTcxMDEzODE3fQ.UVab6LRgbx6ZKeq9SkJhouTfiq9tZEo9fIrIj2NPYr4'
mstream.player.js:637 song.url = '/media/music/Alphabetical/3/3 Doors Down/2002 - Away from the Sun/3 Doors Down - When I'm Gone.mp3?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJveWNlIiwiaWF0IjoxNTcxMDEzODE3fQ.UVab6LRgbx6ZKeq9SkJhouTfiq9tZEo9fIrIj2NPYr4'
mstream.player.js:639 SONG ERROR
mstream.player.js:434 DOMException: Failed to execute 'createMediaElementSource' on 'AudioContext': HTMLMediaElement already connected previously to a different MediaElementSourceNode.
    at goToSong (http://asus-rog-vm.bighouse:3000/public/js/mstream.player.js:429:31)
    at goToNextSong (http://asus-rog-vm.bighouse:3000/public/js/mstream.player.js:350:12)
    at Object.mstreamModule.nextSong (http://asus-rog-vm.bighouse:3000/public/js/mstream.player.js:144:12)
    at HTMLDivElement.<anonymous> (http://asus-rog-vm.bighouse:3000/public/js/mstream.vue-player-controls.js:353:19)
mstream.player.js:637 song.url = '/media/music/Alphabetical/3/3 Doors Down/2002 - Away from the Sun/3 Doors Down - When I'm Gone.mp3?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJveWNlIiwiaWF0IjoxNTcxMDEzODE3fQ.UVab6LRgbx6ZKeq9SkJhouTfiq9tZEo9fIrIj2NPYr4'
mstream.player.js:639 SONG ERROR
mstream.player.js:434 DOMException: Failed to execute 'createMediaElementSource' on 'AudioContext': HTMLMediaElement already connected previously to a different MediaElementSourceNode.
    at goToSong (http://asus-rog-vm.bighouse:3000/public/js/mstream.player.js:429:31)
    at goToNextSong (http://asus-rog-vm.bighouse:3000/public/js/mstream.player.js:350:12)
    at onloaderror (http://asus-rog-vm.bighouse:3000/public/js/mstream.player.js:651:11)
    at o.<anonymous> (http://asus-rog-vm.bighouse:3000/public/js/lib/howler.core.js:2:18777)
mstream.player.js:617 song.url = '/media/music/Alphabetical/5/50 Cent/2003 - Get Rich or Die Tryin'/50 Cent  - P.I.M.P.(not clean).mp3?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJveWNlIiwiaWF0IjoxNTcxMDEzODE3fQ.UVab6LRgbx6ZKeq9SkJhouTfiq9tZEo9fIrIj2NPYr4'
mstream.player.js:637 song.url = '/media/music/Alphabetical/5/50 Cent/2003 - Get Rich or Die Tryin' [Clean]/50 Cent - 21 Questions.mp3?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJveWNlIiwiaWF0IjoxNTcxMDEzODE3fQ.UVab6LRgbx6ZKeq9SkJhouTfiq9tZEo9fIrIj2NPYr4'
mstream.player.js:639 SONG ERROR
```

I was thinking about what could cause this on the server-side and noticed that the ffmpeg directory that has a readme stating the ffmpeg binary goes here and the js file uses it for transcodeing, but there is no binary in the directory. Maybe transcoding is needed for some of my MP3 files.

Also, I noticed that of the MP3 files I looked at, the ones that play have a full ID3 tag, while the ones that do not play only have the basic information. If this could possibly be the cause of the problem, I could do some more research into the tags.

**Comment by IrosTheBeggar** [comment]
What browser and OS are you using?

**Comment by RoyceTheBiker** [comment]
At first, I tried using Chrome. Now I have tried with IE and it gives an error 
Line: 425
Error: 'VIZ' is undefined

I enabled logging. No issues on the server-side. 

Something about these files is not compatible with the client-side player. 

I will do more testing.

**Comment by IrosTheBeggar** [comment]
This might be because of the visualizer. Try removing these three lines from the mstream.html file and see if it works

```
  <script src="/public/js/lib/butterchurn.min.js"></script>
  <script src="/public/js/lib/butterchurn-presets.min.js"></script>
  <script src="/public/js/lib/butterchurn-presets-extra.js"></script>
```

**Comment by RoyceTheBiker** [comment]
I commented those lines out and I get the exact same error as before. No change in Chrome or IE.

**Comment by RoyceTheBiker** [comment]
I created my own simple music player with ExpressJS [JukeBox](https://gitlab.com/SiliconTao-open-source/JukeBox) and it is doing the same thing. 

I do not think this is a bug in mStream, I think some of my MP3 files are not really MP3. I need a tool that can diagnose the files and if possible correct errors it finds. If you know of such a thing please let me know.

If you want, you can close this issue. If you keep it open, I will update it when I find a solution.

**Comment by IrosTheBeggar** [comment]
I'm going to close the ticket.  Open another one if it turns out there is an issue on mstream's side

For analyzing music files you can check out [Picard](https://picard.musicbrainz.org/).  Or for a javascript tool you can try [music-metadata](https://github.com/borewit/music-metadata).  That's what mstream uses.

And nice project.  It looks a lot like mstream in the early days.  Let me know if you want to collaborate.   I made Discord recently but haven't made it public yet: https://discord.gg/AM896Rr
