### ISSUE TITLE
Transcoding Bugs

### ISSUE THREAD

**Issue by IrosTheBeggar** [IrosTheBeggar/mStream#213]
An early versions of transcoding has been added.  It works well enough in most cases, but it's not bug free yet.  This ticket is to track all issues related to transcoding:

- Doesn't work in Safari
- Duration and Seek don't work in webapp

**Comment by aroundmyroom** [comment]
will this feature, if enabled detect if you are on mobile yes/no ?
I see this feature in the menu now and its disabled, but it is not in the config to be enable/disable yet correct?

**Comment by IrosTheBeggar** [comment]
There is no mobile detection.  You manually enable it.

You can enable it wit hthe `-t` flag or in the config with 
```
  "transcode": {
    "enabled": true,
    "defaultCodec": "opus",
    "defaultBitrate": "128k"
  },
```

**Comment by laduke** [comment]
Hi! I was messing with something similar; I hadn't found this project yet. 

Here's what I know about making it work in safari:
- need 206 status code
- need content range header
- need to be able to send an arbitrary range (for example: 0-1 or 16384-32767)

unfortunately, the content range header needs the total size, so you have to guess (bitrate * track length). 
The guess will be a little off, you you have to pad some 0's onto the end of the stream. 
So, the browser will make 3 or 4 requests for the same song, and you'll have to transcode the file that many times, or figure out some caching of the stream. Have fun!

**Comment by romjeans** [comment]
Hi,
Do you know a way to permanently enable transcoding ? After enabling transcoding, when I close the browser and open again mstream web page, the transcoding option becomes "disabled".
Thanks
Rom

**Comment by jimthedj65** [comment]
I have checked this app in 

> Safari Version 14.1.1 (16611.2.7.1.4) Big sur 11.4 on MacBook Pro (15-inch, 2017)

> Google Chrome Mac Version 91.0.4472.114 (Official Build) (x86_64), 

> Vivaldi | 4.0.2312.33 (Stable channel) (x86_64), Revision | 75595d1359deaec4b68624c45e95be53e1e6ad13
OS | macOS Version 11.4 (Build 20F71), JavaScript | V8 9.1.269.36, User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

I enabled transcoding and all works great, Vivaldi plays the songs but doesn't show the seek and time for the track.

I have this working in a proxmox VM running Rocky minimal install 8.4
```
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8" 
```
with 

```
ffmpeg version N-102799-g49e3a8165c Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 8 (GCC)
configuration:
libavutil      57.  0.100 / 57.  0.100
libavcodec     59.  2.100 / 59.  2.100
libavformat    59.  3.101 / 59.  3.101
libavdevice    59.  0.100 / 59.  0.100
libavfilter     8.  0.103 /  8.  0.103
libswscale      6.  0.100 /  6.  0.100
libswresample   4.  0.100 /  4.  0.100

```
hope it helps, as per the previous post, the transcode option when checked resets to unchecked on all browsers when refreshed.  However the setting remains enabled in the default.json in the save dir.  Not sure if enable transcode on the gui is a feature to turn on off easily, I assumed it would be saved until unchecked manually.

hope it helps.

**Comment by jimthedj65** [comment]
I have also tested this on Android Chrome 91.0.4472.101 Android 10 :SM-G965F Build/OPTA.190711.020  when transcode is enabled it also doesnt enable the seek and time function of whats being played, if the transcode is turned off on this version also doesn't work, everything plays ok.  My whole library is flac and wav hence why the transcode option is useful for me when on mobile.

**Comment by henrikp** [comment]
Running mStream in a docker, on a Raspberry Pi 4 (8GB) with a 64-bit OS, Debian 10 on aarch64. I had to download the "arm64" static binaries from [](https://johnvansickle.com/ffmpeg/) to get transcoding running (no complaints so far), otherwise I got silence and an error in the logs:

`{"stack":{"errno":-2,"code":"ENOENT","syscall":"spawn /opt/mstream/bin/ffmpeg/ffmpeg","path":"/opt/mstream/bin/ffmpeg/ffmpeg","spawnargs":["-formats"]},"level":"error","message":"Transcoding Error!","timestamp":"2021-08-14T16:37:42.193Z"}`

There was only a README.md in the `/opt/mstrean/bin/ffmpeg` directory.  Can the extra platform be included in the future somehow or I just have to stay with my `ffmpegDirectory` path modification?

**Comment by IrosTheBeggar** [comment]
I've updated the transcoding feature to fix these bugs. The new transcoding algorithm is slower to load but works on every device and seeking will always work.

I added an option in the config file to use the old algorithm as well.

**Comment by IrosTheBeggar** [comment]
I added all the UI changes for transcoding. This includes remembering if you enabled transcoding previously.

@henrikp can you post some instructions on how you solved your issue on this thicket: https://github.com/IrosTheBeggar/mStream/issues/233

There's an ongoing issue specifically with Docker and ffmpeg. Any help solving it would be appreciated

**Comment by henrikp** [comment]
The transcoding with seeking is working on my end, but would it be possible to keep the quick transcoding (with no seeking) as an alternative option? The delay with Raspberry Pi 4 currently is a minute of transcoding with an 5 minute track and I personally don't care for seeking when I'm listening over mobile data.

**Comment by infocilla** [comment]
> The transcoding with seeking is working on my end, but would it be possible to keep the quick transcoding (with no seeking) as an alternative option? The delay with Raspberry Pi 4 currently is a minute of transcoding with an 5 minute track and I personally don't care for seeking when I'm listening over mobile data.

Look into the admin panel, you can choose between buffer (new feature with seeking working) and stream (old behavior with no seeking but faster)

**Comment by henrikp** [comment]
I apologize, I looked over your commits a while ago and I didn't see that modification. Maybe somesort of status to the "Utilities->Transcording" page would be nice, like only even a word "buffering" or "streaming"? In terms of listening to a set playlist the next track transcoding in the background seems to be working fine, but I tend to hit next quite often ... :)

**Comment by infocilla** [comment]
Not really a bug, but now with v5.7.0 the transcoding page shows only the codec & the check box.
![image](https://user-images.githubusercontent.com/80051789/135849439-d74c127d-bebc-48dd-b5c0-cd28f348d632.png)

**Comment by henrikp** [comment]
> Running mStream in a docker, on a Raspberry Pi 4 (8GB) with a 64-bit OS, Debian 10 on aarch64. I had to download the "arm64" static binaries from to get transcoding running (no complaints so far), otherwise I got silence and an error in the logs:
> 
> `{"stack":{"errno":-2,"code":"ENOENT","syscall":"spawn /opt/mstream/bin/ffmpeg/ffmpeg","path":"/opt/mstream/bin/ffmpeg/ffmpeg","spawnargs":["-formats"]},"level":"error","message":"Transcoding Error!","timestamp":"2021-08-14T16:37:42.193Z"}`
> 
> There was only a README.md in the `/opt/mstrean/bin/ffmpeg` directory. Can the extra platform be included in the future somehow or I just have to stay with my `ffmpegDirectory` path modification?

This issue is now fixed for my situation. Correct binaries are downloaded and non-transcoding/stream transcoding/buffer transcoding work like intended.
