### ISSUE TITLE
ValidationError: "folders.library" must be of type object 

### ISSUE THREAD

**Issue by NoxInmortus** [IrosTheBeggar/mStream#215]
Hello,

I opened a ticket on Linuxserver.io but I was told to go here.
Original ticket: https://github.com/linuxserver/docker-mstream/issues/2

The generated json config :
```
{
  "port": 3000,
  "webAppDirectory": "public",
  "writeLogs": false,
  "noUpload": true,
  "scanOptions": {
    "skipImg": false,
    "scanInterval": 1.5,
    "pause": 50,
    "saveInterval": 500,
    "bootScanDelay": 15
  },
  "storage": {
    "albumArtDirectory": "/config/album-art",
    "dbDirectory": "/config/db"
  },
  "folders": {
    "library": "/music"
  },
  "users": {
    "admin": {
      "password":"password",
      "vpaths": "library",
      "lastfm-user": "username",
      "lastfm-password": "password"
      }
  }
}
```

I did not touch the generated json configuration, and after trying to delete the container and the volume, then to create it again, the json was generated the same.

I did try to edit library and vpaths to look like more than the example on the front page of this repository but the container then only logged ```ERROR: Failed to parse JSON file```
And wasnt starting.

Thanks for your insights.

**Comment by IrosTheBeggar** [comment]
What program was used to generate it?  The format 

There are two problems I see:

`folders` is now an object. In the future there will be a second param which can tag a folder as audiobooks or podcasts.

```json
"folders": {
  "library": {"root":"/music"},
}
```

`user.vpaths` needs to be an array

```json
"users": {
  "admin": {
    "password":"password",
    "vpaths":["library"]
  }
}
```

**Comment by NoxInmortus** [comment]
Hello,

Well I did not generate anything myself, I just started the container with `USE_JSON: true` and that's all.

**Comment by IrosTheBeggar** [comment]
I submitted a pull request to the docker repository updating their default config.  

You should make you own config. The one they provide has an insecure password and a non-working lastFM account attached to it.

**Comment by NoxInmortus** [comment]
Ok, thanks for your help.
