### ISSUE TITLE
m3u cannot load files, times out

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#218]
Loading icon keeps turning .. gives:
![image](https://user-images.githubusercontent.com/250108/67796282-0c433600-fa80-11e9-8723-0819a0aa0df9.png)

issue is with this folder with music
https://we.tl/t-1o9R4EmAL3
also another folder, same issue
https://we.tl/t-qsahLxc6Mw

m3u can be played when using PotPlayer .. ?
other m3u does work

**Comment by lukaswozniak** [comment]
This happens because m3u files can appear in two formats, simple and extended. Seems the library I used for parsing supported only one of those. I already fixed it: #219

**Comment by aroundmyroom** [comment]
ok, purffect, when it is merged I will test again ;)
happy to find again some stuff ;)

**Comment by IrosTheBeggar** [comment]
I merged the change.  This should be fixed now

**Comment by aroundmyroom** [comment]
Fixed
