### ISSUE TITLE
update checking

### ISSUE THREAD

**Issue by Riajyuu** [IrosTheBeggar/mStream#22]
Hi, Could you add such ability to do that as I don't see any option to check update.

**Comment by pakmanbozz1** [comment]
Hi  I'm new to this so I'm just trying to learn as I gobut sounds like. Great idea

**Comment by IrosTheBeggar** [comment]
Yea, I'm working on it now.  It's a lot harder than it sounds so it's going to take a while

**Comment by Riajyuu** [comment]
@IrosTheBeggar for now. A simple notice without auto installing will be enough. That should be much easier

**Comment by IrosTheBeggar** [comment]
Ok, the next version will have an option that auto checks for updates and posts alerts in the tray icon.

**Comment by IrosTheBeggar** [comment]
v0.3 has this feature. Closing ticket
