### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by lxnunorodrigues** [IrosTheBeggar/mStream#224]
Hi 
How make it startup
I checked , appears the app but dont start automatic !

thanks

**Comment by IrosTheBeggar** [comment]
Auto start is only available in the GUI version.


 You can use PM2 to start automatically: https://github.com/IrosTheBeggar/mStream/blob/master/docs/booting_cli.md

**Comment by lxnunorodrigues** [comment]
hi my pc "windows" i restarted but only appears gui , i have to push button
to start , i would like start automatic , for example , service

thanks

**Comment by IrosTheBeggar** [comment]
What OS are you using?

**Comment by IrosTheBeggar** [comment]
Ok I'll look into it.  have you downloaded the latest version?

v4.5.2 available here: https://github.com/IrosTheBeggar/mStream/releases/download/v4.5.2/mStream-Server-Setup-4.5.2.exe

**Comment by lxnunorodrigues** [comment]
I have that version , when i restarted my computer i only seen the GUI , i see is checked "Boot on Startup" , but i see to click "boot server" , why dont launch automatic !

sugestion : 15 seconds or we put any time  to launch , its possible add this config !

i have my own server at home i have a clock program to restart because the windows updates to local network ...

**Comment by IrosTheBeggar** [comment]
I just finished a new release that should fix this. Let me know if it fixes it for you:

https://github.com/IrosTheBeggar/mStream/releases/tag/v4.5.3

**Comment by lxnunorodrigues** [comment]
Hi , good work , thanks its Work
I Just install ( update it )
Restart my Server
and boot automatic :)

OS : MS Windows Server 2016 Standard | Version : 1607


Any question or i would like to be a BetaTester , contact me 

Thanks Again
