### ISSUE TITLE
pull issues?

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#226]
error: Your local changes to the following files would be overwritten by merge:
        package.json
Please commit your changes or stash them before you merge.

I do not make changes, but some weeks ago i had same issues, than a few pulls ago it was fine, but now its back
of course I can do git stash but I rather do not have this issue ;)

**Comment by lukaswozniak** [comment]
Try `git checkout package.json` Before pull

**Comment by IrosTheBeggar** [comment]
Hmm that's odd.  You can reset all the source files to a default state with `git reset`

```shell
git reset --hard HEAD
```

If you haven't fixed it yet, try running these commands to find out what files have been changed:

```shell
git diff --name-only

git status
```

**Comment by aroundmyroom** [comment]
right now no info, but will check with next change and pull ;)

**Comment by IrosTheBeggar** [comment]
Closing this since it hasn't happened in several months.  Please open a new ticket with a diff log if it happens again
