### ISSUE TITLE
Issue with Mstream web App on Android

### ISSUE THREAD

**Issue by romjean** [IrosTheBeggar/mStream#229]
Hi,
Playback on Android Chrome doesn't work. I see well the web app, I can choose the songs or playlists and put them in the listening queue, but when I try to play the music, nothing happens, even the remaining time is not decreasing, meaning the play back has not started.
Everything works well on the web app on a computer or in the Android dedicated app.

I would want to use the web app on Android because I love the DJ feature which is not present in the Android App.

Thanks !
Rom

**Comment by romjean** [comment]
Any ideas ?

**Comment by IrosTheBeggar** [comment]
What phone are you using?  I cannot replicate this bug

**Comment by romjean** [comment]
Samsung J5 2016 with Android 7.1.1 and chrome mobile version 78. It doesn't work either with Samsung internet V10.2

**Comment by romjean** [comment]
I cleaned up Chrome's app cache and data and it work now. Sorry about that.
