### ISSUE TITLE
Android lock screen 

### ISSUE THREAD

**Issue by skanga** [IrosTheBeggar/mStream#23]
Brilliant stuff. Thanks!

Currrently, on the Android lock screen, I can play/pause the mStream app.
I am wondering if you can add support for prev/next song also.

Thanks again
shiraz

**Comment by IrosTheBeggar** [comment]
I'll look into it.  

It seams to be a chrome specific feature.  If anyone knows where to find docs on this, post them here.

**Comment by ewnd9** [comment]
Here we go https://developers.google.com/web/updates/2017/02/media-session

**Comment by IrosTheBeggar** [comment]
Just a heads up.

I've decided not to implement any chrome for android specific features.  Instead I'm working on a Android App that will have all of these features.  You can see the progress here:

https://github.com/IrosTheBeggar/mstream-android-app

It's currently usable and has lock screen controls implemented.
