### ISSUE TITLE
Remove your token/keys from this repository and allow users to use their own LAST.FM api keys

### ISSUE THREAD

**Issue by b0nk** [IrosTheBeggar/mStream#231]
https://github.com/IrosTheBeggar/mStream/blob/931ca65e74465e8d25bc5eda38c480172bf7fac2/modules/scrobbler.js#L2

**Comment by IrosTheBeggar** [comment]
This is now possible.  You can set the api key and secret in the config file. If you don't provide your own it will default to the ones I provided
