### ISSUE TITLE
Validation Error: “secret” is not allowed to be empty

### ISSUE THREAD

**Issue by nickchen120235** [IrosTheBeggar/mStream#232]
Just updated to ver. 4.5.3 from 4.3.0 using git pull. Can’t start mStream, receiving error that “secret” shouldn’t be empty, but  I remembered that if “secret” is empty in config.json file, it will generate by itself whenever the app starts or restarts.

**Comment by IrosTheBeggar** [comment]
I pushed a change that should fix that.  Config validation got a lot stricter on v4.5.x and I forgot to add an exception for empty secret strings

**Comment by nickchen120235** [comment]
Working! Thank you very much.
