### ISSUE TITLE
patreon? 

### ISSUE THREAD

**Issue by samayo** [IrosTheBeggar/mStream#239]

**Comment by IrosTheBeggar** [comment]
It's really out of date, and the  awards tiers don't exist anymore:

https://www.patreon.com/mstream

**Comment by samayo** [comment]
Ok I have subbed for $10. I think thats the highest. I havent even tried mstream yet :) but i like it so far, and hopefully i will contribute if I choose to go with it

**Comment by IrosTheBeggar** [comment]
Thanks so much!  Once I have the RPN service running again I will set you up with an account. 

An RPN account comes with a domain + SSL encryption for your server.  It's completly optional, but makes getting online as easy as possible.

**Comment by samayo** [comment]
It's ok, I don't really need it. Currently, I am trying to make mstream work on digitalocean. I will let you know if I run into some bugs
