### ISSUE TITLE
[Feature Request] Search in all library instead of the current folder

### ISSUE THREAD

**Issue by pinkfloydFR** [IrosTheBeggar/mStream#241]
Hi,

Currently the search focus only in the current directory. It's sad because mstream has a database.

So, am i stupid ? or this can be include in a next release ?

Thk :)

**Comment by IrosTheBeggar** [comment]
Yea, it's one of those features that's long overdue.  Development is just slow lately because I'm working on another project right now.

**Comment by pinkfloydFR** [comment]
No problem, thanks for the job anyway !

**Comment by IrosTheBeggar** [comment]
I pushed some changes that add a search feature.  The database had to be restructured so mStream will have to rescan the library.  Also song ratings will be 'reset' (the ratings still exist in the old DB file, so they're not gone forever)

I will be releasing this as v5 sometime soon.  And there will be a tool for moving all your ratings to the new DB

**Comment by pinkfloydFR** [comment]
Great job ! Thanks a lot !
