### ISSUE TITLE
Latest version(s?) no longer allow mounted music folders

### ISSUE THREAD

**Issue by druexmachina** [IrosTheBeggar/mStream#245]
I've been running v4.2.1 since I first installed it with no issues via docker-compose (arm32v7). My music folder is a directory on an exFAT-formatted SSD mounted via /etc/fstab at boot. I decided to pull the latest image today (v4.6.0) and got this error trace with no changes to the docker-compose file:

/opt/mstream/modules/defaults.js:78
     throw new Error(error);
     ^
 
 Error: ValidationError: "folders.music" must be of type object
     at Object.exports.setup (/opt/mstream/modules/defaults.js:78:11)
     at Object.exports.serveIt (/opt/mstream/mstream.js:18:28)
     at Object.<anonymous> (/opt/mstream/cli-boot-wrapper.js:41:7)
     at Module._compile (internal/modules/cjs/loader.js:959:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
     at Module.load (internal/modules/cjs/loader.js:815:32)
     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
     at internal/main/run_main_module.js:17:11

I reverted to the old image and it works fine. Given the error, I assume the new version no longer accepts mounted directories as valid objects. If so, can this functionality be re-added?

Thank you!

**Comment by IrosTheBeggar** [comment]
mStream still supports mounted images.  What happened here is the config validation got a lot stricter in v4.5 to support the federation feature.

Your new config needs to be structured like
```json
{
  "folders":{
    "music": {root: "/path/to/music"}
  }
}
```

What docker image are you using?

**Comment by druexmachina** [comment]
Ah, sorry about that, I should have scanned through the documentation before updating. Modifying the config accordingly resolved the issue. Thanks!

```
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
linuxserver/mstream   arm32v7-latest      ea1ce2417362        4 days ago          257MB
linuxserver/mstream   old                 badae0b3d559        5 months ago        150MB
```

**Comment by IrosTheBeggar** [comment]
@druexmachina 

No problem.  That error is really vague for such a common problem.  I'll have to update the messaging to more human readable.
