### ISSUE TITLE
Multi-disc track order support

### ISSUE THREAD

**Issue by druexmachina** [IrosTheBeggar/mStream#246]
After recently adding a multi-disc album to my library, I've found that the album/artist views in the web app appear to sort the tracks by track number (i.e. 1-1, 2-1, 3-1, 1-2, 2-2, 3-2) without looking at the disc number (desired sort order: 1-1, 1-2, 2-1, 2-2, 3-1, 3-2). Is adding this additional sorting layer possible or do tracks need to be tagged a certain way? Thanks!

**Comment by IrosTheBeggar** [comment]
I just release v4.7.0 which should fix this.  Let me know if it works for you.

**Comment by druexmachina** [comment]
Verified - thanks for the quick response!
