### ISSUE TITLE
Failed to Play Song

### ISSUE THREAD

**Issue by aksm** [IrosTheBeggar/mStream#247]
Seems like it might be browser-related. One song from an album (the rest of which plays fine in Chrome) with same metadata and file type won't play on Chrome (console error says "SONG ERROR") but plays fine in Firefox. Not sure if it's relevant, but it's an M4A.

**Comment by IrosTheBeggar** [comment]
That does sound browser related.  You can test it by opening the file with chrome to see if chrome can play it.

**Comment by aksm** [comment]
Yup, doesn't play. Any idea why it's happening?

**Comment by IrosTheBeggar** [comment]
It's a bug with chrome.  Your best bet is to file a bug with the chromium team:

https://bugs.chromium.org/p/chromium/issues/list

Be as detailed as possible and make it clear the the file works in everything but chrome.
