### ISSUE TITLE
Android app keeps crashing

### ISSUE THREAD

**Issue by aksm** [IrosTheBeggar/mStream#248]
Android 10 on Pixel 3. I can connect to the server, but when I try to browse Artists, Albums, or the File Explorer, it immediately crashes over and over again. No errors in the server logs.

**Comment by IrosTheBeggar** [comment]
The android app is built with flutter and in need of the some updates.  I'm busy with another project right now, so I don't know when I will get around to fixing it.

**Comment by aksm** [comment]
Ok, thanks. I'll close for now then.
