### ISSUE TITLE
recent broken?

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#249]
I see my db is being updated, but the recent option not 

How to debug this to see why the recent shows still older entries from ie. a few weeks back?
could it be due to v1 and v2 database migration?
I see files.loki-v1.db
files.loki-v2.db
user-data.loki-v1.db

Even when starting a new scan I see an initial recent placed, but I expect the recent with every save of the db being updated as well. None of this is happening ..

**Comment by IrosTheBeggar** [comment]
Just to be clear, old files that you have deleted are staying in the database?

**Comment by aroundmyroom** [comment]
nope .. the 'Recent added' function does not work anymore.

I first discovered that with my old database new files were added in the database but where not seen in the recent added function GUI part. I thought that it could be related to the migration of v1 v2 db, therefor I removed my db and indexed all again. But again here: the inital 'recent added' is working I see that there are files but or the sorting is incorrect (oldest first rather than newest first) or there are no additions to the recent added when I add new files 

Ie. 
db is being  created and files indexed
first 500 files indexed, I have certain files in 'recent added'
now the next 500 files needs to be indexed, working fine
now it is expected that recent added is also showing new files, but recent added keeps showing the same numbers.

![image](https://user-images.githubusercontent.com/250108/74100022-436abe00-4b2a-11ea-906b-2b7d66597462.png)

What you see here are the inital first indexed songs and not the latest indexed songs.

**Comment by aroundmyroom** [comment]
@IrosTheBeggar Probably busy with other projects, but can this issue be looked against, its the only issue I have right now .. ;)

**Comment by usineur** [comment]
Commit 4ccc4e3962c5a84269825a27404a5b9295c4ae14
```diff
-    }).simplesort('ts', true).limit(limit).data();
+    }).limit(limit).simplesort('ts', true).eqJoin(userMetadataCollection.chain(), leftFun, rightFunDefault, mapFunDefault).data();
```

Just invert `simplesort` and `limit` again to fix this issue.

**Comment by aroundmyroom** [comment]
@usineur ahhh yeah .. that fixes it again !

**Comment by IrosTheBeggar** [comment]
@usineur thanks for posting the fix

@aroundmyroom the change has been committed.  

Sorry for the delay.  My old job has been terminated due to the lockdown, so I've been busy looking for work

**Comment by aroundmyroom** [comment]
thanks for the fix. Yeah we read the news here about the situation. Terrible. Hope you find work soon
