### ISSUE TITLE
Crash while streaming and updating the database.

### ISSUE THREAD

**Issue by mcdoh** [IrosTheBeggar/mStream#25]
This has happened twice to me so far. I'm not sure if the same bug happened twice or if the behavior is just the same. I'll fire up mStream, the database scan starts running, I'll start streaming music and one of the first few songs will stop mid-stream. The database continues its scan and eventually completes.

```
/home/mcdoh/mStream/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'Count(*)' of undefined
    at Statement.<anonymous> (/home/mcdoh/mStream/modules/db-read/database-public-sqlite.js:15:17)
--> in Database#get('SELECT Count(*) FROM items WHERE user = ?;', [ 'mstream-user' ], [Function])
    at Object.exports.getNumberOfFiles (/home/mcdoh/mStream/modules/db-read/database-public-sqlite.js:14:6)
    at /home/mcdoh/mStream/modules/db-management/database-master.js:112:25
    at Layer.handle [as handle_request] (/home/mcdoh/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/mcdoh/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/mcdoh/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/mcdoh/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/mcdoh/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/mcdoh/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mcdoh/mStream/node_modules/express/lib/router/index.js:275:10)
```

**Comment by IrosTheBeggar** [comment]
It looks like the call to get the number of files in the DB is failing.  The quick fix is to add some additional error checking to that function, but it still doesn't explain why it's failing.  

Can you post your OS and version of Node?

**Comment by mcdoh** [comment]
Sorry, I meant to do this then forgot to do so.
Ubuntu 16.04 Server

```
uname -a
Linux nasty 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
node --version
v6.10.3
```

**Comment by eresonance** [comment]
This is happening to me too:

```
$ node --version
v6.11.0
$ uname -a
Linux server 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

Using a systemd service and alternate db location:
```
$ cat mstream.service
[Unit]
Description=mstream server
Requires=network.target
After=network.target

[Service]
User=mstream
Type=simple
WorkingDirectory=/comb/media/music
ExecStart=/usr/bin/mstream -p 3000 -d /comb/mstream_data/mstream.db
#PrivateTmp=true
#Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by IrosTheBeggar** [comment]
Ok, I'm going to setup a ubuntu server on a spare computer and see if I can get to the bottom of this.

@eresonance What filesystem are you using.  I'm assuming ext4 but I just wan to make sure

**Comment by eresonance** [comment]
Yes, ext4 with lvm. Thanks for looking into this!

**Comment by eresonance** [comment]
It seems this only happens when building the database, after it's built I was playing around on the site and never saw another exception. Works fine once it's all built and up.

**Comment by mcdoh** [comment]
I should have mentioned that I'm also using an alternate database location. My media collection is on a ZFS filesystem with raidz. My database is on ext4.

**Comment by IrosTheBeggar** [comment]
@mcdoh & @eresonance 
I think I found and fixed the problem.  Can you pull the latest changes from the master branch and see if that works?

**Comment by eresonance** [comment]
I hit the rebuild database button but it completes super quickly, so I removed the db file and restarted.

I don't see any strange behaviour now, but I'm not 100% sure what it was that caused the original crash. I can rebuild the db, listen to songs, screw around in the interface, and it just seems to work without issues.

Thanks!

**Comment by IrosTheBeggar** [comment]
Glad to hear it's working!
