### ISSUE TITLE
sharing playlist gives error

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#250]
Tried to share a playlist so that someone can download a song
but when using this link .. and pressing the download button:

vue.js:634 [Vue warn]: Error in v-on handler: "ReferenceError: MSTREAMAPI is not defined"

found in

---> <PlaylistItem>
       <Draggable>
         <Root>
warn @ vue.js:634
logError @ vue.js:1893
globalHandleError @ vue.js:1888
handleError @ vue.js:1848
invokeWithErrorHandling @ vue.js:1871
invoker @ vue.js:2188
original._wrapper @ vue.js:7547
vue.js:1897 ReferenceError: MSTREAMAPI is not defined
    at VueComponent.downloadSong (mstream.vue-player-controls.js:93)
    at click (eval at createFunction (vue.js:11649), <anonymous>:3:770)
    at invokeWithErrorHandling (vue.js:1863)
    at HTMLSpanElement.invoker (vue.js:2188)
    at HTMLSpanElement.original._wrapper (vue.js:7547)

**Comment by IrosTheBeggar** [comment]
This is fixed now

**Comment by aroundmyroom** [comment]
going to next error

vue.js:634 [Vue warn]: Error in v-on handler: "ReferenceError: MSTREAMAPI is not defined"

found in

---> <PlaylistItem>
       <Draggable>
         <Root>
warn @ vue.js:634
logError @ vue.js:1893
globalHandleError @ vue.js:1888
handleError @ vue.js:1848
invokeWithErrorHandling @ vue.js:1871
invoker @ vue.js:2188
original._wrapper @ vue.js:7547
vue.js:1897 ReferenceError: MSTREAMAPI is not defined
    at VueComponent.downloadSong (mstream.vue-player-controls.js:93)
    at click (eval at createFunction (vue.js:11649), <anonymous>:3:770)
    at invokeWithErrorHandling (vue.js:1863)
    at HTMLSpanElement.invoker (vue.js:2188)
    at HTMLSpanElement.original._wrapper (vue.js:7547)
logError @ vue.js:1897
globalHandleError @ vue.js:1888
handleError @ vue.js:1848
invokeWithErrorHandling @ vue.js:1871
invoker @ vue.js:2188
original._wrapper @ vue.js:7547

**Comment by IrosTheBeggar** [comment]
I don't see this error in Firefox, but I know what caused it and fixed it.  I also made a few other updates to the shared page that should speed it up a bit

**Comment by aroundmyroom** [comment]
Im using chrome 
still errors, now it will even not play the song

![image](https://user-images.githubusercontent.com/250108/75221882-24fbf800-57a3-11ea-8f88-cfe37fcd0631.png)


and also trying to download the song does not work

![image](https://user-images.githubusercontent.com/250108/75221938-4361f380-57a3-11ea-8a17-7e37cdcae5f8.png)

**Comment by aroundmyroom** [comment]
Microsoft Edge can play the song but cannot download

![image](https://user-images.githubusercontent.com/250108/75222009-7d32fa00-57a3-11ea-9ff4-565c966b63d8.png)

**Comment by aroundmyroom** [comment]
good old (kuch) iexplore.exe gives this

![image](https://user-images.githubusercontent.com/250108/75222143-d26f0b80-57a3-11ea-8f58-6a70df991fa3.png)

**Comment by jerrycan619** [comment]
For the download bug:
Iros just forgot to add the download link in "shared.html"
So open "mStream/public/shared.html"
and ADD at this point:
```html 
<body>
 ### insert here ###
<!-- Header -->
```
this:
```html
<!-- Download iFrame -->
  <form id="downform" action="" target="frameframe" method="POST"></form>
  <iframe id="downframe" src="" width="0" height="0" tabindex="-1" title="empty" hidden name="frameframe"></iframe>
  <!-- Download iFrame for GET requests -->
  <a  href="#" class="hide" download id="download-file" hidden></a>
```

with this it should work

Note:
```html
<a  href="#" class="hide" download id="download-file" hidden></a> 
```
would be enough to get this working but for consistency just add all from above.
"'clientWidth' of null" I get sometimes too, but I can't see what this is effecting because everything works.. so I'm ignoring this one.

Note to IrosTheBeggar:
I would remove 
```html
<a  href="#" class="hide" download id="download-file" hidden></a> 
```
completely and in mstream.vue-player-controls.js replace the content of the downloadSong function with:
```js
var link = document.createElement('a');
link.download = '';
link.href = `/media/${this.song.filepath}?token=${MSTREAMAPI.currentServer.token}`;
link.dispatchEvent(new MouseEvent('click', {bubbles: true, cancelable: true, view: window}));
```
according to [stackoverflow](https://stackoverflow.com/questions/32225904/programmatical-click-on-a-tag-not-working-in-firefox) as a more "modern" solution.
(Because I've run into this problem too that it sometimes didn't work the way it is now)

**Comment by IrosTheBeggar** [comment]
I updated the shared playlist page. It should fix all download related bugs as well as adding some new features like album art

**Comment by IrosTheBeggar** [comment]
Closing this ticket since these issues have been fixed in the new share page
