### ISSUE TITLE
Add information on supported file formats

### ISSUE THREAD

**Issue by AlexFullmoon** [IrosTheBeggar/mStream#253]
Installed mStream only to find out that it doesn't support ALAC .m4a format. I do understand that adding support for every format and a kitchen sink might not be viable, but I couldn't find any information on supported formats in the docs.

Please add a mention on supported file formats somewhere, possibly on the front page.

**Comment by IrosTheBeggar** [comment]
mStream is limited to whatever formats the browser supports.  Unfortunately no browsers support alac at the moment, so the files are ignored. I added a list of all officially supported formats to the readme

It's possible to add an option for mStream to show unsupported file formats.  They can be downloaded and added to playlists, but you would not be able to stream them in the browser.  Please open another ticket if this is something you're interestd in.
