### ISSUE TITLE
Support mStream in subdirectory of server / reverse proxy

### ISSUE THREAD

**Issue by d10n** [IrosTheBeggar/mStream#254]
Currently, mStream only supports running at the root of the server, like `http://localhost:3000/`.

In order to make mStream deployable on a domain without affecting the rest of the site, mStream should be deployable at `http://localhost:3000/mStream`.

This pattern is supported by various other server software,
like BookStack https://www.bookstackapp.com/docs/admin/subdirectory-setup/
and Gitea https://docs.gitea.io/en-us/reverse-proxies/

**Comment by d10n** [comment]
Looks like this is a duplicate of #223

**Comment by IrosTheBeggar** [comment]
Relative URLs are being worked on and should work on the main page.  I'm closing this ticket and tracking progress in the other ticket.
