### ISSUE TITLE
Huge variation on Volume/Gain (Clipping)

### ISSUE THREAD

**Issue by jerrycan619** [IrosTheBeggar/mStream#257]
Hi, first of all thank you for your great work!
I love this Music Player / Server because of the awesome Folderview and two Pane view!
I tried a lot of other music server but NONE seems to even have a Browse by Folder mode which is essential for me!

But now I have to say that am very sad because all other Music server I tested played my songs in a more or less equal Volume
and on mStream I have big Volume/Gain troubles I never had before.
Some songs are clipping, some are real quiet.
Every 1-2 Songs I have to get to my Computer to adjust the Volume.

To test if it's not me, I set up 3 other Music Server. (mpd,Koozic,Navidrome)
I played the exact same song on all 4 (max. volume) and only mStream does clipping :(

In my 2 screenshots (same song)
![mStream1](https://user-images.githubusercontent.com/63951644/82128634-e3388780-97bc-11ea-86cd-6ed769f09f33.png)
![mStream2](https://user-images.githubusercontent.com/63951644/82128636-e6cc0e80-97bc-11ea-8281-3cc4377e3072.png)

 you can see that all other Music servers are using "Firefox: Audio Stream On"
and only mStream is using "Firefox: AudioCallbackDriver On"..
(and only on this AudioCallbackDriver clipping occurs)
i don't know but maybe this is responsible for the wide range of different volumes on each track?

Sure i can just put the Volume down on mStream, but then I have to do it back up on the next song.. and so on.
I can't leave my Computer because of this :( :(
(and I'm not going to resample ~50k files with same audio level's)

I really really wish this is something that could be fixed because like I said, mStream is the only one out there that is useful because of the Browse by Folder!
(and some other features)

EDIT: after further testing i also noticed that all other Webplayers effect the volume sliders on the screenshot (if i move the volume slider on the Webplayer it also moves there)
But on mStream the Webplayed does NOT effect the volume slider on the system

**Comment by d10n** [comment]
The volume slider issue is separate, but the clipping might be resolved by #256

**Comment by jerrycan619** [comment]
Thank you for your hint and (possible) fix! I now just listen via Chrome and the Volume seems good by now! (further testing now)
I didn't notice that this is not an issue of the tracks, but mStream goes louder and louder by time.

**Comment by jerrycan619** [comment]
After further testing this seems to solve my issue.
I've read this Pull request before I opened this Issue but I don't thought this is related -.-
So now everything works for me and I'm happy :)

Thanks
