### ISSUE TITLE
Themes/Skins (I did some)

### ISSUE THREAD

**Issue by jerrycan619** [IrosTheBeggar/mStream#258]
Since I can't really help on the programming side but wanted to contribute and keep mStream alive
I tried to theme the interface to give it a more modern look and feel (in my opinion).

Anybody who wants to change the look of mStream is welcome to take a look at my repository
https://github.com/jerrycan619/mStream-themes

I hope it's ok for you that i did this and you're welcome to include this link in your readme or use it
anywhere else. If you're disagreeing just give me a small message and I take it down.

**Comment by IrosTheBeggar** [comment]
That's pretty cool. I;m impressed since mStream is not easy to skin

I'm pretty busy right now moving between jobs thanks to the coronavirus. I'll throw a link in the readme in readme soon

**Comment by jerrycan619** [comment]
I'm glad you like it.
In comparison to you I have / had plenty of time thanks to the corona virus.
Since I have high expectations on UI and UX design I decided to do my own approach on designing a new interface.<br/>
So i spend a lot of time to create [this](https://github.com/jerrycan619/mStream/tree/interface). (strongly inspired by big streaming platforms) <br/>
Maybe we can move this part by part to the official mStream in the future, because I think you could attract a lot more people to mStream by a new, modern style. If this happens I also would take care of the "frontend" so you could spend your valuable time on backend programming if you want. (because I don't like this part :) )<br/>

But for now I'm looking for alpha testers who like to use my Interface and give me feedback and improvement suggestions. There is a lot to do.
