### ISSUE TITLE
Special Characters in Filepath (fix for download Playlist included)

### ISSUE THREAD

**Issue by jerrycan619** [IrosTheBeggar/mStream#261]
My Music Collection has special characters in their filepath like /music/#folder1/...
This leads to the problem that the download on download Playlist not get started.

After fiddling around i found a fix for this which is:
On mstream.js

replace: `downloadFiles.push(MSTREAMPLAYER.playlist[i].filepath);`
with: `downloadFiles.push(decodeURIComponent(MSTREAMPLAYER.playlist[i].filepath));`

So the decodeURIComponent replaces in my case "%23" with "#" and the download works again.

However i don't think that's the root of the problem, but i don't know where the root is.
Maybe this could be included to work everywhere on mStream (like the filepath in playlist and player for untagged files)

EDIT: 
Rate song also outputs an error on paths with special chars.
The fix which works for me is in /modules/db-read/database-public-loki.js
```js
const result = fileCollection.findOne({ '$and':[{ 'filepath': decodeURIComponent(pathInfo.relativePath)}, { 'vpath': pathInfo.vpath }] });
```
in  the /db/rate-song function

**Comment by IrosTheBeggar** [comment]
This has finally been fixed in the last commit. The problem was special chars are encoded by the player to be url friendly, but this causes problems with downloads and ratings. I updated the player to also keep track of the unmodified url path.
