### ISSUE TITLE
strange behavior of albumart (+ fix?)

### ISSUE THREAD

**Issue by jerrycan619** [IrosTheBeggar/mStream#264]
I'm noticed a strange behavior of the album art.

For development and testing around I've got several mStream instances in their own folder.
None of them showed the album art to me.
Just for testing this I installed another mStream instance fresh from git. 
Gave it one folder with album art in it.
It worked.. but only for a while?!
After some time the album art was not displayed anymore.

So I tried to trace it back and added some console.log in database-public-loki.js
the `console.log(result[0])` in  `mstream.post('/db/metadata' ...` outputs something like this
```js
{ artist: 'TrackArtist',
  album: 'Albumname',
  hash: 'randomNumber',
  track: 1,
  title: 'Tracktitle',
  year: 20XX,
  'album-art': '29ce91f676d1958c6e897f329757dfe0.jpeg',
  filepath: 'path/to/file',
  rating: undefined,
  vpath: 'media',
  meta: { revision: 0, created: 1591631863297, version: 0 },
  '$loki': 1 }
```
But for the metadata you assign `"album-art": result[0].aaFile ? result[0].aaFile : null`
so..there is no aaFile...

So.. I changed Line 25 in /modules/db-read/database-public-loki.js
from: `"album-art": left.aaFile,`
to: `aaFile: left.aaFile,`

and now there is an result[0].aaFile entry.

The strange thing is, that it worked a period of time for me without touching the code and then suddenly not anymore???

However, with this small code change it's now working on all my mStream installs.
I don't know much about your Database handling so I decided to post it as an issue and not as an pull request because I dont how if this has other effects. 
(there is also a line with  `"album-art": right.aaFile` ..maybe this need to be changed too?)

**Comment by aroundmyroom** [comment]
maybe is this also related to my finding #287

**Comment by IrosTheBeggar** [comment]
@jerrycan619 thanks for finding and reporting this.  It's been fixed in the latest commit

Sorry for the long delay.
