### ISSUE TITLE
Server call failure message when trying to connect from Android App

### ISSUE THREAD

**Issue by l0rddarkf0rce** [IrosTheBeggar/mStream#266]
I have to delete my server and re-add it every time i want to use it. If I do not delete it I get a 'server call error' message, but once i delete the server from the app and re-add it, it works. Connecting to the server via a browser works just fine.

**Comment by jdewoody71** [comment]
I get the "server call error" when trying to access any links in the Android app. It works fine via browser on my PC.

**Comment by rpelissi** [comment]
I got exactly the same issue.

**Comment by IrosTheBeggar** [comment]
I just released a new version of the app that's compatible with mStream v5:

https://github.com/IrosTheBeggar/mstream_music/releases/tag/v0.0.0

It's still early in development, but all the core features are working

**Comment by IrosTheBeggar** [comment]
Closing this ticket since the new app is on Google Play. Please open up a new ticket if you still see any connection issue.
