### ISSUE TITLE
Rescan database

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#269]
How is rescanning of the database handled?

Many songs are replaced and or have new location or are deleted, but the database seems not to remove or change the location. New files are added, but I see when playing in DJ mode songs loaded but turning 'red' because the resource cannot be found. (which is correct) but the data should not be present anymore.

I only have
145.559 files in db

**Comment by jerrycan619** [comment]
I don't know how the rescanning is handled in detail, but if you are finished with moving files around / add or remove you could delete "files.loki-v2.db" (better copy it somewhere else as backup)
in /mStream/save/db folder. 

After restarting mStream (or maybe the build database button is enough... I don't know) it should begin a fresh scan of your entire Collection starting from 0.

I know it's not a solution but a workaround until IrosTheBeggar have time to look at this.

**Comment by aroundmyroom** [comment]
Yeah that this is possible I know, but that takes ' hours '  cause all jpegs are extracted from the files as well.. So in your advise: make sure the image folder is also moved/removed cause otherwise the folder will be getting big with its unique filenames (if they are unique)

and for me its the question if this is behaviour of loki due to large db / many files (+100.000) or something else ..

**Comment by aroundmyroom** [comment]
Just a follow-up. I'm playing with proxmox now and I set up a LXC container to see if I quickly could migrate/setup mStream
what I thought is real.

The DB is not cleaned up correctly
2 mstream instances, same source, the one with lower number is the actual new db indexed without any new files added
the other one is an older instance. 

As my music is almost 3TB worth of data it takes a long time to index the whole dataset. So every week removing the db is no solution ;)

![image](https://user-images.githubusercontent.com/250108/88782032-67c85e80-d18d-11ea-973b-0cddfb104455.png)

**Comment by IrosTheBeggar** [comment]
This should be fixed now.  an Update I made last year caused moved or deleted files to not be removed from the db.  Let me know if it works

**Comment by IrosTheBeggar** [comment]
The scan code has changed a lot since this ticket was opened. Closing it
