### ISSUE TITLE
Can't add items to playlist when shuffle is on

### ISSUE THREAD

**Issue by Dam-Buty** [IrosTheBeggar/mStream#27]
As the title says, i've noticed if shuffle is on i can't add new tracks to a playlist. If i remove shuffle then it works...

**Comment by IrosTheBeggar** [comment]
Holy crap you're right, I'm looking into this now and should have it fixed soon

**Comment by Dam-Buty** [comment]
```
 ReferenceError: song is not defined
    at Object.mstreamModule.addSong (mstream.player.js:29)
    at Object.MSTREAMPLAYER.addSongWizard (api2.js:157)
    at HTMLDivElement.<anonymous> (mstream.js:140)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.r.handle (jquery.min.js:3)
```

This is on Google Chrome on Ubuntu 16.04 :)

**Comment by IrosTheBeggar** [comment]
Looks like I broke this when adding more metadata functionality.  The latest version, v0.3.1 fixes this.  Get it here now.  I'l have it available on mstream.io shortly

https://github.com/IrosTheBeggar/mStream/releases/tag/v3.0.3

**Comment by Dam-Buty** [comment]
:+1: 

i can't test this right now as i don't have remote access to the machine anymore, but i'll be sure to give it a try this weekend :)
