### ISSUE TITLE
Volume Creep

### ISSUE THREAD

**Issue by rocnetBinarian** [IrosTheBeggar/mStream#272]
Here's a weird one.  Running mStream 4.7.0 on an LXC container, Ubuntu 20.04 LTS.  System is fully updated and restarted.  Client is Windows 10 1909, running Firefox Developer Edition v79.0b7.

**Issue:**
No matter what I play or how I navigate to a list of songs (I'm avoiding the term "playlist" here because this is not related to just actual logistical "playlists"), there is volume creep.  The end of the list is much louder than the start.  Some testing shows that the volume increases each time a track starts...which means I can keep restarting the same track over and over, and it will be louder every time.  I have to refresh the tab to reset volume back to where it's supposed to be.

Issue has appeared in past few versions of Firefox.
Issue does NOT appear to occur in Chrome (only minimal testing done here).

**Comment by jerrycan619** [comment]
I've had the same problem. To fix apply #256 by hand or wait until it gets merged.

**Comment by rocnetBinarian** [comment]
Brilliant, thanks!  Sorry for the duplicate issue.  I looked for one and must have completely just glossed over that one.  That does indeed fix the problem quite nicely.

**Comment by IrosTheBeggar** [comment]
I merged this pull request. Sorry for the long wait
