### ISSUE TITLE
Nginx Reverse Proxy breaks zip downloads

### ISSUE THREAD

**Issue by hylianux** [IrosTheBeggar/mStream#273]
It's entirely possible that I have something configured wrong here... but my configuration looks almost identical to yours, so I wanted to see what you had going on.  

I'm using the 4.7.0 version.

Single-file downloads work just fine... it's whenever I try to download a playlist, the download immediately stops.  If I run it purely from the nodejs endpoint, it works just fine (i.e. https://mydomain.com:3000)

it's only when attempting to make it work through nginx's reverse proxy that the problem occurs.  The error I receive is (with some names changed)
`2020/07/18 04:37:43 [crit] 17246#17246: *1 open() "/var/lib/nginx/proxy/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 192.168.1.1, server: mydomain.com, request: "POST /download-directory?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1ZXN0IiwiaWF0IjoxNTk1MDU0MTc4fQ.F0qcUbUSfCE-_do_eh_D1mv6MNTuVrfdfSdTcswnquw HTTP/2.0", upstream: "http://127.0.0.1:3000/download-directory?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1ZXN0IiwiaWF0IjoxNTk1MDU0MTc4fQ.F0qcUbUSfCE-_do_eh_D1mv6MNTuVrfdfSdTcswnquw", host: "mydomain.com", referrer: "https://mydomain.com/"`

My nginx configuration uses certbot, and looks basically like this (with the names changed to protect the innocent)
```
server {
    root /var/www/music;
    index index.html index.htm;

    server_name mydomain.com;
    
    location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_redirect http:// https://;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host  $http_host;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen 80;
    server_name mydomain.com;
    return 404; # managed by Certbot
}
```
Ultimately looks pretty similar to your setup... are you having this problem on your end, by chance?  And if not, then what could I possibly check?  I've for sure changed the permissions so that nginx has access to all the same folders...

**Comment by AlphaJack** [comment]
My setup is working, this is my Nginx location (you want to use "/" instead of "/mstream"):

```nginx
location /mstream {
 proxy_pass http://127.0.0.1:3030/mstream;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
Why are you using HTTPS directives between Nginx and mStream?

**Comment by hylianux** [comment]
> Why are you using HTTPS directives between Nginx and mStream?

In short: because Certbot made me and I'm a server setup noob :)

In long - from what I'm seeing, there isn't any SSL directive between nginx and mstream... that is - the communication of nginx to mstream isn't SSL-encrypted at all, only the communication of the user to the nginx server.  Correct me if I'm wrong.

I'm kinda stupid when it comes to SSL setups, so I've been using the automatic setup of certbot.  Is there a better way to set up ssl for mstream?  I thought if nginx is my entrypoint for a user, then that's where the SSL should happen.

**Comment by AlphaJack** [comment]
> I thought if nginx is my entrypoint for a user, then that's where the SSL should happen

Yes, and if you host your services in the same server (like we both do) there is little to no benefit from setting up https between every service and NginX.

Can you try this configuration? I've just reordered yours and removed some (almost) useless directives

```nginx
server {
 listen 80;
 server_name mydomain.com;
 return 301 https://$host$request_uri;
}

server {
 listen 443 ssl http2 default_server;
 server_name mydomain.com;
 
 root /var/www/music;
 index index.html;

 include /etc/letsencrypt/options-ssl-nginx.conf;
 ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
 ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
 ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
 
 location / {
   proxy_pass http://127.0.0.1:3000;
   proxy_set_header Host $http_host;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 }
}
```

If you really want to setup TLS between mStream and Nginx, you should tell mStream to use a certificate and a private key (a self signed cert should be enough). 
If you can reach your service through https://127.0.0.1:3000 (notice the "s"), and your browser alerts you about the self signed certificate, you can then configure NginX in this way:
```nginx
 location / {
   proxy_pass https://127.0.0.1:3000; # notice the s
   proxy_set_header Host $http_host;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_ssl_session_reuse on;
   proxy_ssl_trusted_certificate /path/to/mstream/selfsigned/cert.crt;
 }
```

**Comment by hylianux** [comment]
To my knowledge, my setup (and the one you mentioned) doesn't have TLS setup between nginx and mstream, The only place SSL is setup is at the Nginx layer... 

To illustrate, my understanding of the full process is: User (browser) -> Nginx -> mstream (reverse-proxied from nginx)

The User -> Nginx part is ssl encrypted, but I'm not seeing what you mean about the Nginx -> mstream part being also SSL encrypted... if I'm wrong, what directive do I have listed that would suggest I have SSL enabled for the communication between nginx and mstream?

In any case, I tried your configuration - same problem.  

> 2020/08/17 10:49:01 [crit] 2954#2954: *4 open() "/var/lib/nginx/proxy/3/00/0000000003" failed (13: Permission denied) while reading upstream, client: 73.171.82.108, server: mydomain.com, request: "POST /download-directory?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1ZXN0IiwiaWF0IjoxNTk1MDU0MTc4fQ.F0qcUbUSfCE-_do_eh_D1mv6MNTuVrfdfSdTcswnquw HTTP/2.0", upstream: "http://127.0.0.1:3000/download-directory?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1ZXN0IiwiaWF0IjoxNTk1MDU0MTc4fQ.F0qcUbUSfCE-_do_eh_D1mv6MNTuVrfdfSdTcswnquw", host: "mydomain.com", referrer: "https://mydomain.com/"

Edit: If it's a permissions issue, I've got my folder permissions set to nginx as the user with full read-write-execute permissions.  I've also tried running mstream as the nginx user.  

Edit 2: And again - it works just fine when directly going to the ip (or local domain name) and port.  It's only when routing through nginx that it causes a problem.  The files (or even single files, not sure when that started happening, but at least it's consistent) start to download for like a couple kbs and then it just stops.

Both the mstream install directory and the media directory are set up with "775" (drwxrwxr-x and -rwxrwxr-x) permissions, with the owner set as nginx.  The nginx user is also the user being engaged to run mstream in the first place.  

The page loads, it can properly browse media directories, and music streams/plays just fine.  I feel like I gotta be close.

**Comment by hylianux** [comment]
I think the issue has something to do with certbot.  I disabled SSL completely, and everything works through nginx.  something's off with the https, so i just turned it off.  i can't really see a need to encrypt any connection to mStream, the point was to put it behind a password wall.

**Comment by IrosTheBeggar** [comment]
@hylianux 

I've been using this NGINX config for my own mstream servers:
```
server {
   listen 80;
   server_name mstream.io *.mstream.io;
   rewrite     ^   https://\$host\$request_uri? permanent;
}
server {
    listen 443 ssl;
    server_name mstream.io *.mstream.io;
    ssl_certificate /etc/ssl/certs/mstream.pem;
    ssl_certificate_key /etc/ssl/private/mstream.key;
    # Turn on OCSP stapling as recommended at
    # https://community.letsencrypt.org/t/integration-guide/13123
    # requires nginx version >= 1.3.7
    ssl_stapling on;
    ssl_stapling_verify on;
    location / {
        proxy_pass http://localhost:4444;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \"upgrade\";
        proxy_set_header Host \$host;
    }
}
```

Also instead of certbot check out acme.sh: https://github.com/acmesh-official/acme.sh

Acme.sh is easier to use and has built in support for a number of DDNS services
