### ISSUE TITLE
Log failed login attempts and bind to localhost only

### ISSUE THREAD

**Issue by AlphaJack** [IrosTheBeggar/mStream#276]
Is it possible to log failed login attempts to mstream.log?
It may also be useful to update this file whenever the database gets updated with new tracks, by default every 250 new files.

---

I noticed that by default mStream binds to 0.0.0.0 and there is no option to restrict the host to 127.0.0.1, I had to modify `mstream.js`
from
```javascript
server.listen(program.port, () => {
```
to
```javascript
server.listen(program.port, '127.0.0.1', () => {
```
Is it possible to add an option in `mstream --wizard`?

**Comment by IrosTheBeggar** [comment]
I merged a pull request from @jmacmahon that adds this functionality. I also updated the default address to 127.0.0.1

I didn't realize the default behavior of express was to bind to 0.0.0.0.  Thanks for pointing this out.

I'll look into better logging as well
