### ISSUE TITLE
Shouldn't tracks be alphabetized?

### ISSUE THREAD

**Issue by Dam-Buty** [IrosTheBeggar/mStream#28]
I find it weird that the tracks are not in alphabetic order in the files view : 

![image](https://cloud.githubusercontent.com/assets/1461760/26545095/a8d4ee7a-4464-11e7-8939-dbe29ae120bd.png)

**Comment by IrosTheBeggar** [comment]
Files are put in the order they are read by the OS. Typically this gives things back in alphabetical order, but obviously this not working in all cases.  

I'll add an option to sort files.  I'm out of town right now, so it will be  a day or two before I get started on this

**Comment by Dam-Buty** [comment]
A super quick fix would be to just sort the filesArray & directories arrays before concatenating them i guess :) I'd offer a PR but i'm at work right now and can't test it properly.

**Comment by IrosTheBeggar** [comment]
Found some time to test the fix.  mStream Express v0.4.1 has this fix

**Comment by Dam-Buty** [comment]
The fix didn't work on my machine. I've submitted a Pull Request that does the compare correctly (i think). I've rigged my install to use this code, and it seems to work right now!

**Comment by Dam-Buty** [comment]
(also i think you forgot to update the version numbers? mine still displays 0.3 in the tray icon, i have no idea where you're supposed to change this in an electron app....)

**Comment by IrosTheBeggar** [comment]
I'm building a release pipeline, but for now I have to update a lot of stuff by hand.  Looks like I missed that one.

v0.4.2 has fixes this and has the latest sort code

**Comment by Dam-Buty** [comment]
Cool :+1:  Let me know what you use for your pipeline, the subject interests me :)

**Comment by IrosTheBeggar** [comment]
@Dam-Buty 
The pipeline is nothing impressive really.  Right now it's literally just a checklist of things to do to push the releases out.  I'm going to write some scripts in either Python or Javascript that automate parts of it.  Over time I think I can get the whole thing down to one script.

Would you be interested in helping out with a project?  There's a few on my plate like last.fm scrobbling, album art lookup, and multi-room sync that I just don't have the time to get to right now.  I'm currently really busy looking into Android dev and building the DDNS/SSL service.  Let me know if you're interested

**Comment by Dam-Buty** [comment]
> I'm going to write some scripts in either Python or Javascript that automate parts of it. Over time I think I can get the whole thing down to one script.

You could always wrap it up in a NPM script, i've found these to be quite practical and they solve a couple of problems if you want to automate things further down the road (like using a CI/CD toolchain, or even building with Docker, etc...).

> Would you be interested in helping out with a project?

Haha i was gonna offer my help, so i'm glad you'd have it :) The problem is right now i'm spinning a ton of plates, but starting in July i should have way more free time and i'd be happy to contribute. mStream is a project i've wanted to do for a long time so i might even have a couple interesting ideas on the subject! In the meantime i'm stress testing it all day at work so i'll keep an eye out for any bug i might encounter.

**Comment by IrosTheBeggar** [comment]
Awesome, I appreciate all the help you can give.  Keep posting any bugs here and I'll fix them as fast as I can.
