### ISSUE TITLE
album art not shown during playback

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#287]
![image](https://user-images.githubusercontent.com/250108/98985677-326d3400-2524-11eb-82aa-a9234973c02b.png)

I expect the image art to be seen. When selecting the album I have the album art (at the right selection menu
but when played the image is not there

Is this a setting I do miss in my config?

I am busy with indexing not my whole collection but only the folders defined, so I can also check if my setup is matching the new json structure (I had still some older definitions in it).

**Comment by IrosTheBeggar** [comment]
this should be fixed now
