### ISSUE TITLE
mStream Android App Search not working?

### ISSUE THREAD

**Issue by count00zero** [IrosTheBeggar/mStream#289]
Is it just me or is the search function within the mstream android app not working?

**Comment by blueping** [comment]
same thing for me

**Comment by nartuber** [comment]
same problem too...

**Comment by IrosTheBeggar** [comment]
The search bar on the android app was never completed.  

The larger problem is this project has grown too large for me to handle by myself.  I am currently busy updating some legacy server and webappp code, so it will be a while before I can get back to mobile development.

The app is written in Flutter. If anyone wants to help with development they can hop in the Discord channel and let me know

**Comment by IrosTheBeggar** [comment]
Search has been added to app
