### ISSUE TITLE
New Sourctree for testing?

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#290]
Paul, would it be wise to create a develop tree where you put your changes?

I like to beta test, but as I see with latest commits the changes are that severe that my working version stops working due to various issues

Like mentioned the config.json will be invalid, Today It became. Not a problem, but not knowing how to solve it will cause a version not be able to use

I started ' clean ' so that the webUI could give me some relief. It did not as none of the configs could be saved

So when you create a new sourcetree we could have the latest 4.x version as Master and work on a version 5.x in the develop.
releasing a version when the setup allows it to do ..  Just an idea .. 

2021-01-01T12:37:23.522Z info: Access mStream locally: http://0.0.0.0:3000
2021-01-01T12:37:26.552Z info: File scan started on /home/mStream
2021-01-01T12:37:36.528Z info: File scan message: database saved
2021-01-01T12:37:36.554Z info: File scan completed with code 0
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at open (internal/fs/promises.js:197:3)
    at Object.readFile (internal/fs/promises.js:484:20)
    at Object.exports.loadFile (/home/mStream/src/util/admin.js:6:30)
    at Object.exports.addDirectory (/home/mStream/src/util/admin.js:27:29)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at open (internal/fs/promises.js:197:3)
    at Object.readFile (internal/fs/promises.js:484:20)
    at Object.exports.loadFile (/home/mStream/src/util/admin.js:6:30)
    at Object.exports.addUser (/home/mStream/src/util/admin.js:58:29)

**Comment by IrosTheBeggar** [comment]
Usually I would do it that way, but my time is limitted right now so I'm taking a few shortcuts.  I promise it will be worth it in the long run. 

I will be pushing some changes soon that helps automate the deployment process.  For now, what command are you using to boot mstream?

**Comment by aroundmyroom** [comment]
my most used command is

mstream -j /home/mStream-Data/config.json

I also used some time the I believe -quiet command
when I used this command (with latest 5.x version, from last week december) it tells me the config is not valid anymore as there are some issues with the password / salt part

my config (partly, as I cut some data away from
 "type": "Buffer",
        "data": [
         
`{
  "scanOptions": {
    "pause": 5,
    "skipImg": false,
    "scanInterval": 24,
    "bootScanDelay": 3,
    "saveInterval": 25,
    "writeLogs": true
  },
  "secret": "xxxxxx",
  "folders": {
    "12-inches": { "root": "/media/music/12 inches A-Z"},
    "Jaarmixen": { "root": "/media/music/Jaarmixen"},
    "BurningtheGround": { "root": "/media/music/Burningtheground.net"},
    "Disco": { "root": "/media/music/Disco"},
    "Albums": { "root": "/media/music/Albums"},
    "Grandmix": { "root": "/media/music/Grandmix"},
    "House": { "root": "/media/music/Housetop1000"},
    "IntheMix": { "root": "/media/music/In the Mix"}
  },
  "users": {
    "xxxxx": {
    "vpaths": ["12-inches", "Jaarmixen", "House", "BurningtheGround", "Disco", "Albums", "Grandmix", "IntheMix"],
      "password": "xxxxxxxxxx",
      "salt": {
        "type": "Buffer",
        "data": [
          214,
          180,
          192,
          174
        ]
      }
    }
  },
  "storage": {
    "albumArtDirectory": "/home/mStream-Data/album-art",
    "dbDirectory": "/home/mStream-Data/db",
    "logsDirectory": "/home/mStream-Data/logs"
  },


  "port": 3000,
  "ssl": {
    "key": "/export/certificate/*.xxxx.key",
    "cert": "/export/certificate/*.xxxx.cer"
  }
}`

**Comment by aroundmyroom** [comment]
update
I have setup an test server vm to use latest code.
I was able to allow a folder to be added and an user. that;s working. Now checking if a database scan is working ;0
