### ISSUE TITLE
Delete user 

### ISSUE THREAD

**Issue by Mikelito91** [IrosTheBeggar/mStream#291]
Hi,

I have created some users to made a few tests.
How can I delete this users ?
They have access to the wrong folder.

**Comment by IrosTheBeggar** [comment]
I am currently working on the admin tools. There will be a delete function coming within the next week.  

For now, you can use the wizard or you can go into the config file and edit it by hand.  You will need to reboot the server after making changes.

```shell
# wizard
mstream --wizard /path/to/config.json
```

**Comment by aroundmyroom** [comment]
when pulling you might also exclude the default.json

Resolving deltas: 100% (66/66), completed with 34 local objects.
From https://github.com/IrosTheBeggar/mStream
   49d58cf..e7d2c74  master     -> origin/master
Updating 49d58cf..e7d2c74
error: Your local changes to the following files would be overwritten by merge:
        save/conf/default.json
Please commit your changes or stash them before you merge.

**Comment by IrosTheBeggar** [comment]
There's now a delete user function.   Let me know how it works for you

**Comment by Mikelito91** [comment]
Hi,
No I still don't have the function for delete user.
Maybe I have to do an apt/update  ?

**Comment by IrosTheBeggar** [comment]
How  did you install mStream?  

You need to be able to pull the latest changes to get the new user. Some installation methods make this task easy while others make it somewhat hard.

**Comment by aroundmyroom** [comment]
although mouse-over could get some rework, (you do not see that you can press it) I can remove the users when I ie. added a 2nd one, so no issue here

**Comment by Mikelito91** [comment]
I've installed mStream like this : 
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get update
sudo apt-get install -y nodejs
sudo-apt-get install git
git clone https://github.com/IrosTheBeggar/mStream.git
cd mStream

npm install --only=production
sudo npm link
git pull

**Comment by IrosTheBeggar** [comment]
@Mikelito91 

Where did you find those instructions for installation?  NodeJS v6 is pretty out of date at this point.

Also to access the admin panel you need to be installing via git.

**Comment by Mikelito91** [comment]
I find the instruction here : https://korben.info/mstream-un-serveur-de-streaming-leger-et-puissant-pour-ecouter-votre-musique-depuis-nimporte-ou.html
If i understand well, I need to reinstall mStream ?

**Comment by IrosTheBeggar** [comment]
Sorry I lost track of that ticket.

Those instructions are outdated.  You should follow these instructions: https://github.com/IrosTheBeggar/mStream

Also make sure to get the latest version of nodeJS with the command

```
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
```
