### ISSUE TITLE
How to add first user on initial setup?

### ISSUE THREAD

**Issue by elhenro** [IrosTheBeggar/mStream#293]
I saw that the --wizard option was removed, so my workaround was to go back to the previous commit, generate my user and then go back to the latest version.

What would be the new way to setup an admin account?
The docs could be updated with this info.

**Comment by IrosTheBeggar** [comment]
I removed the wizard and replaced it with the Admin UI/API.  I also removed the ability to boot mStream with CLI flags.  Now you have to boot mStream with a config file.  If you don't provide a config file, mStream will attempt to create one in the /save folder.

The current workflow is this:

- If your config file has no users, authentication is disabled and anyone can access the server
- In the admin panel you can add users.  Once your first user is added, authentication is automatically enabled and you will need to log in

I'll be adding a new feature soon that will disable the admin API.  This way you can leave your server open to the public without giving them access to the admin features.

**Comment by elhenro** [comment]
Thanks for the quick reply, I understand the background now.
I was just a bit confused when initially setting up users. Would I need to manually create a salted password and add this salt and
password to the `config.json`? I could not access the admin interface without having a user.
Let me know if you want me to open a MR to update the docs for that (also remove the `--wizard` option from docs).
Solid work btw!

**Comment by IrosTheBeggar** [comment]
There was a bug the admin UI would kick you to the login screen even if you had no users registered.  That was fixed yesterday, so things should be working now.

And yes, any help would be appreciated.  I'm making a lot of changes to the fronted right now (there's a new shared page) and the dos are falling behind as a result
