### ISSUE TITLE
Shared playlist issue when having large number of songs

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#295]
![image](https://user-images.githubusercontent.com/250108/106000774-7f868e00-60af-11eb-90ff-c2bb385db1ec.png)

no song can be found .. 
when I have a shared playlist with +99 songs

when selecting from my main folder (with 100 songs) only 20 and not all, than the shared playlist is played

**Comment by aroundmyroom** [comment]
issue must be related to wrong and too long token

with 1 song: the token is this

xxxxciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkRmlsZXMiOlsiaG91c2V0b3AxMDAwLzAwMS0xMDAvMDAxIC0gSmF5ZGVlIC0gUGxhc3RpYyBEcmVhbXMgKExvbxxxxxxx2VybmFtZSI6ImRlbm5pcyIsImlhdCI6MTYxMjA4NTg2OCwiZXhwIjoxNjEzMjk1NDY4fQ.S8dpKlJwa-jej_phTyoHcgax_dTUNclZcHEN9OKV4Ck

but when I add 100 songs, I see this  ... 

![image](https://user-images.githubusercontent.com/250108/106380177-c5459e00-63b0-11eb-9e12-84d622c4e386.png)

if every song needs its own token, the way the URL is created is wrong

**Comment by IrosTheBeggar** [comment]
Yea the token is getting to long because the code is trying to be clever and encode the entire playlist in the token.

Will fix it soon

**Comment by IrosTheBeggar** [comment]
This should be fixed in the latest release. Let me know how it works..

You're old shared playlists will no longer work on this update btw

**Comment by aroundmyroom** [comment]
working perfectly !
