### ISSUE TITLE
/db/album-songs returns "null" for album-art

### ISSUE THREAD

**Issue by ggalt** [IrosTheBeggar/mStream#297]
I'm trying to figure out how to retrieve album art for songs from an album.  The directory containing each album contains a .jpg file for the cover art for the album (it is not embedded in the MP3 file).  The /db/album-songs call returns "null" in the album-art field as seen here: 

`[{"filepath":"main/Modest Mouse/The Moon and Antarctica/01-3rd Planet.mp3","metadata":{"artist":"Modest Mouse","hash":"7edba733386bc89d86654dafbb3d4999","album":"The Moon and Antarctica","track":1,"title":"3rd Planet","year":2000,"album-art":null,"filename":"01-3rd Planet.mp3","rating":null}},{"filepath":"main/Modest Mouse/The Moon and Antarctica/02-Gravity Rides Everything.mp3","metadata":{"artist":"Modest Mouse","hash":"c4b81d7e043ad967d2a91b2360bd6c02","album":"The Moon and Antarctica","track":2,"title":"Gravity Rides Everything","year":2000,"album-art":null,"filename":"02-Gravity Rides Everything.mp3","rating":null}},`

Even though the /db/artists-albums call will return the album-art for the album:

`[{"name":"The Moon and Antarctica","album_art_file":"343762a4fd77f4c7821ea0a883265f49.jpg"}]`

Is this an issue with how the database scan works or with the single .jpg file in the album directory?

FYI, all cover art files are labeled either "folder.jpg" or "cover.jpg" and should be found by the code in the scanner @ line 340.

**Comment by aroundmyroom** [comment]
afaik there is no support for folder.jpg or cover.jpg yet. If it would I would like it as I have a lot of songs in separate maps with some ' art ' 
Right now the coverart is extracted from the file and saved with as a jpg hash file.

I have ie. back.jpg, cover.jpg, folder.jpg, disck,jpg, front.jpg
It would be nice to have something like

if exist cover.jpg than use cover.jpg if not than use ie. folder.jpg
 or the admin could define the order

**Comment by ggalt** [comment]
Certainly it is supported at the "album" level.  Just glancing at the code, it looks like those types are supported to some extent in lines 332-346 of scanner.js (function checkDirectoryForAlbumArt()):

```

// Only one image, assume it's album art
  if (imageArray.length === 1) {
    imageBuffer = fs.readFileSync(path.join(directory, imageArray[0]));
    picFormat = getFileType(imageArray[0]);
  }else {
    // If there are multiple images, choose the first one with name cover, album, folder, etc
    for (var i = 0; i < imageArray.length; i++) {
      const imgMod = imageArray[i].toLowerCase();
      if (imgMod === 'folder.jpg' || imgMod === 'cover.jpg' || imgMod === 'album.jpg' || imgMod === 'folder.png' || imgMod === 'cover.png' || imgMod === 'album.png') {
        imageBuffer = fs.readFileSync(path.join(directory, imageArray[i]));
        picFormat = getFileType(imageArray[i]);
        break;
      }
    }
  }

```

**Comment by IrosTheBeggar** [comment]
The scanner does attempt to pull files from the folder. It's not perfect though and could use some work.

The fact the ` /db/artists-albums` call returns album art means the scanner picked up something. You can check your database file to see if some songs have the correct album art.  If it turns out some songs have the album art file and others don't, it means the scanner isn't caching the information correctly.  Let me know so I know where to start looking for the bug.

You can also add the album your your playing queue and look at the metadata API calls to check if any songs have the album art and get the album art back.

**Comment by ggalt** [comment]
I took a look through the database and didn't see any album art associated with any individual song title.  Almost all of the "albums" however, have art associated with them.  Most of my album directories have multiple album art files (in the forms "folder.jpg", "cover.jpg", "back-cover.jpg" as well as in forms similar to " AlbumArt_{3988CE22-11D7-415C-AD0E-E25BFD9EDB8F}_Large.jpg".

I thought it might be the multiple-file-issue, so I removed all by a single "cover.jpg" file from a directory, deleted the entire database and rescanned.  No dice. :-(

I haven't updated for a while so I pulled from the repository (spent some time replacing my old config.json file!) and rescanned.  Still no luck!

On a separate note, where is the config.json file now being stored?

**Comment by aroundmyroom** [comment]
new location is /save/conf and if used default.conf

But you can still use your own config file if needed. I start still from my own

mstream -j /home/mStream-Data/config.json

**Comment by IrosTheBeggar** [comment]
I pushed some updates to the scanner that should fix this. Let me know if it works

**Comment by ggalt** [comment]
It looks like it is working now.  Thanks!!
