### ISSUE TITLE
UI obstructed by playback bar

### ISSUE THREAD

**Issue by HappyWheels** [IrosTheBeggar/mStream#3]
The file explorer extends behind the playback bar making parts hidden.  Using Firefox 45.3.0 

![mstream-screenshot](https://cloud.githubusercontent.com/assets/7735144/18356810/b7d81f84-7631-11e6-9e12-ee684b0998b4.png)

**Comment by IrosTheBeggar** [comment]
Thanks for reporting this.  I'll look into it

**Comment by HappyWheels** [comment]
The problem seems to be a Firefox only thing, i tried on a Firefox 48.0.1 browser and it had the same problem, but not when accessed  with chrome or safari. Thanks for your time & effort .

**Comment by IrosTheBeggar** [comment]
Yea its just a Firefox thing.  It looks like the way Firefox handles padding+scrolling in a div is different from how every other browser handles it.

The good news is I found a solution that works on all browsers.  I should have it here in a day or two

**Comment by IrosTheBeggar** [comment]
The latest version has a few css improvements and should fix this.  Let me know if it works for you

**Comment by HappyWheels** [comment]
Thank you Iros, the latest version is working on Firefox for me now, much appreciated.

**Comment by IrosTheBeggar** [comment]
Glad it's working now.  If you run into any other problems let me know.  I'll try to get them fixed as fast as possible.

And  if you like the project let others know about it!
