### ISSUE TITLE
Android app can not connect to server

### ISSUE THREAD

**Issue by strogg1987** [IrosTheBeggar/mStream#300]
Web UI is working, https enabled. Server behind NAT with port forwarding. v5.0-alpha
![wBft2yWElIs](https://user-images.githubusercontent.com/15184192/108587790-52fd2380-7388-11eb-984b-471ad60539d5.jpg)

**Comment by IrosTheBeggar** [comment]
v5 updated a lot of the API endpoints.  The app hasn't been updated yet.

**Comment by strogg1987** [comment]
Ok, I`ll wait =)
