### ISSUE TITLE
Recently Added: if there is no id3tag: filename should be used

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#301]
![image](https://user-images.githubusercontent.com/250108/109418575-6b44f200-79c9-11eb-8f48-c6c19b742d4a.png)

here a lot of undefined songs ,but when added to the playlist we see the filename with the song
that behaviour should recently added have as well.

**Comment by IrosTheBeggar** [comment]
This is fixed now
