### ISSUE TITLE
scanning new songs does not update GUI with scanned songs in DB

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#302]
![image](https://user-images.githubusercontent.com/250108/109429506-533a9600-79fc-11eb-8cb9-1a36726a1dee.png)

database keeps telling that there are 1000 songs in the db, but as I am adding 3 folders with MANY new files for testing it should add more songs to that counter which is does not

The scan is started from the admin gui rather than restarting the application

update
database is not being updated cq refreshed after the scan has been finished
 (as well as recently added songs, also not updated)

the application needs to be restarted to show the new files and also reload the recently added files

**Comment by IrosTheBeggar** [comment]
Is this still an issue?

**Comment by aroundmyroom** [comment]
just did a small test .. and it is now ok.
