### ISSUE TITLE
mStream live ?

### ISSUE THREAD

**Issue by Jekeru** [IrosTheBeggar/mStream#303]
install repo on server ?

**Comment by IrosTheBeggar** [comment]
Thi is the simplest installation method

```bash
# Install From Git
git clone https://github.com/IrosTheBeggar/mStream.git
cd mStream
npm install

node cli-boot-wrapper.js
```
```

**Comment by Jekeru** [comment]
I mean on a live server, not localy

**Comment by aroundmyroom** [comment]
why should that be different Jekeru? what are you trying to achieve?

**Comment by Jekeru** [comment]
I'm trying to have the same that https://demo.mstream.io/
and maybe make it private

**Comment by IrosTheBeggar** [comment]
@Jekeru 

Deployment is a complex topic.  I'm going to be adding more documentation about it soon.

For now you can join the Discord and we can try to figure out how to get it working on your setup:

https://discord.gg/AM896Rr
