### ISSUE TITLE
new error message when scanning system error -116

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#305]
2021-03-05T13:16:46.146Z info: File scan completed with code 0
Error: Unknown system error -116: Unknown system error -116, read

**Comment by IrosTheBeggar** [comment]
I'm working on a new version of the scanner that should fix some of the memory problems. The first version will be available in a few days

**Comment by aroundmyroom** [comment]
do you want to test my whole db or piece by piece more folders added?

**Comment by aroundmyroom** [comment]
New scan is looking promising quickly scanning 10 albums and than even taken album-art
now busy scanning whole 4.3TB 

What I noticed is that if you want to remove folders the server needs a restart, but the restart is not working.

**Comment by IrosTheBeggar** [comment]
@aroundmyroom the new scan update has been pushed. Let me know how it works

Can you describe the error that happens when rebooting?

**Comment by aroundmyroom** [comment]
not really a error in my shell I see ' server rebooting' or similar message and than nothing. the server is not responsive anymore,
but .. i have to check if I was not too impatience but 30 seconds is really a long time.

Cannot test right now as my whole db is being indexed again 4.3TB and right now all going ok .. almost 12 hours scanning now, save interval on ' 5 '   and +45000 song in db (and counting), must become +100.000 I believe .. 
loki db is around 23MB at this time

**Comment by aroundmyroom** [comment]
just noticed I was not having latest commits

will restart test

**Comment by IrosTheBeggar** [comment]
@aroundmyroom have you seen this since the scan update?

**Comment by aroundmyroom** [comment]
Nope, not yet :-)

**Comment by aroundmyroom** [comment]
I will close this now, Will re-check  when I am making a new DB if you release v5 l;)
