### ISSUE TITLE
[Feature Request] Add a single song to a playlist

### ISSUE THREAD

**Issue by rickmills** [IrosTheBeggar/mStream#311]
I'm not sure if I'm just not using this right or if its a missing feature.

Lets say you've browsed your files, or used search to narrow it down and you want to add 1 of those songs to an existing playlist - this doesnt seem to be possible. Instead you have to add it to the queue on the right, and then once its on the queue on the right you have to re-save everything.

I think a better option would be a something like a simple button next to each item (regardless of where you're looking at it) called 'Add to Playlist' which shows a dropdown or modal to pick the playlist.

**Comment by IrosTheBeggar** [comment]
Currently there's a button for songs in  the Now Playing queue to add them to a playlist. You're right, this button should be added to any song file

**Comment by IrosTheBeggar** [comment]
I added an add to playlist dropdown in the latest commit.
