### ISSUE TITLE
[Feature Request] Save folder preference for Auto-DJ

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#312]
I would like to see that I can preserve the chosen folder(s) for Auto-DJ
Now I have to enable/disable the folders I do not want to have being played by Auto-DJ

**Comment by IrosTheBeggar** [comment]
This is working in the latest commit

**Comment by aroundmyroom** [comment]
How should I be able to test this? 
![image](https://user-images.githubusercontent.com/250108/135054331-29521537-c214-45c7-a463-08184aef3b30.png)

I have 2 main folders, 
music
12-inches
but I do only want to play auto-dj from 12-inches and music must be neglected 
but no go so it looks like .. also under the utilities of AutoDJ I do not see a function to ie. select the folder. It's empty. (the above error is generated by the auto DJ utilities page I see now.

So probably I am doing something wrong ;)

**Comment by IrosTheBeggar** [comment]
This was a bug on my end. Its fixed now

**Comment by aroundmyroom** [comment]
yup I see it ! .. thanks .. it looks like it is working now but will further test it, but no error anymore
