### ISSUE TITLE
How run it in a html file ?

### ISSUE THREAD

**Issue by shortymc** [IrosTheBeggar/mStream#314]
Hi !
Thanks for your great work !
mStream works great but i need help for open from browser.
because it run only on http://mywebsite:3000 but how make it work http://mywebsite/mstream.html

 thanks by advance for your support
Best regards

**Comment by IrosTheBeggar** [comment]
Look into using NGINX as a reverse proxy.  A reverse proxy lets you access muultiple services on the same domain & port.

**Comment by shortymc** [comment]
I had no experience with nginx, i will take a look, 
Do you thinks it's possible with apache ?
also, 
but i can run it in a frame.
But how run it permanently ? Because if it's permanently run i can do something like `<iframe src="mplstreamwebsite:3000"></iframe>`
It's working perfectly when i lauch it with ssh but it's stopping after some times, i'm not sure maybe when ssh connexion is closed
Also i trying to changes images but the original images stay even if change the pictures inside the folder, i ready don't  know why.
Look like in some idontknowhere javascript cache. It's my first step with javascript and i don't know how reload apps file.

 Thanks for your response and support
Best Regards

**Comment by shortymc** [comment]
Hi :)
I try to make it persistent.
first i change port to 3001
I was working well with :
forever start cli-boot-wrapper.js
 after i've configured the apache port to listen 3001 for make a proxy reverse
But don't want to reboot because a process runnind on 3001
i make > node killall
After i modify apache and reboot with success
I connect mywebsite:3001 with success.
Go to mstream admin and change the port to 3002
and it's crashed
Mstream don't want to restart anymore

i modify apache ports.conf
------------------------------------------------
Listen 80
Listen 3002

<IfModule ssl_module>
        Listen 443
        Listen 3002
</IfModule>

<IfModule mod_gnutls.c>
        Listen 443
</IfModule>
------------------------------------------ 

mywebsite.conf
-----------------------------------------
i <VirtualHost *:3002>

    ProxyPass / http://127.0.0.1:3002/
    ProxyPassReverse / http://127.0.0.1:3002/

  SetEnv force-proxy-request-1.0 1
  SetEnv proxy-nokeepalive 1
</VirtualHost>
----------------------------------------------------------

The mStream error


events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:3002
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at doListen (net.js:1501:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (events.js:314:20)
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3002
}
[nodemon] app crashed - waiting for file changes before starting...

Thanks for your help
Best regards

**Comment by shortymc** [comment]
Its solved by :  
killall node
+
kill $(lsof -t -i:3002)
After it's restart.
But for the proxy it's not working a this point.
The iframe working well, but not the proxy.

Thanks for your help
Best regards

**Comment by IrosTheBeggar** [comment]
@shortymc hop in the Discord if you want help with Nginx reverse proxy scripts.  I also update the install instructions to run mstream in the background
