### ISSUE TITLE
How connect a mysql database ?

### ISSUE THREAD

**Issue by shortymc** [IrosTheBeggar/mStream#315]
Hello !
Thanks for your very good work and support.
I want the users of my website to be connected to mstream.
Like this they can register to mStream.
Is it possible ?

 Best Regards

**Comment by aroundmyroom** [comment]
that could be possible if you create users, but how is this relevant to a mysql database?

**Comment by shortymc** [comment]
My online website already got registered users.
There logins/keys are stored inside an mysql database.
 I want mStream connect to mysql database for know if user is already registered and connect it or redirect to a subscription page if not.

**Comment by IrosTheBeggar** [comment]
mStream doesn't use SQL, so you'll need to figure out another way to put your user system in front of mStream

You can setup a custom registration script to add users to mStream.  It will take some work.  You'll need to:

- add an admin user to mstream
- have your registration script user your admin credentials to add users and folders to mStream (there's an admin API that can do all that)

This is really outside the scope of mStream, so I'm closing this ticket. You can check out the Discord server to ask more advice about hosting mStream
