### ISSUE TITLE
[api] Docker Deployment: No login possible

### ISSUE THREAD

**Issue by md-dev-lab** [IrosTheBeggar/mStream#319]
Dear all,

thank you so much for sharing this cool project. It is exactly what I have been searching for.

When I deploy mStream via Docker [https://github.com/linuxserver/docker-mstream], set up a user and subsequently tried to use the Android App / API Login failed with {"error":"Access Denied"}. Also rebuilding the image did not help. No errors in the logs.

Steps to reproduce:
1) Deploy mstream via Docker:
    docker run -d \
      --name=mstream \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ=Europe/London \
      -p 3000:3000 \
      -v /path/to/data:/config \
      -v /path/to/music:/music \
      --restart unless-stopped \
      ghcr.io/linuxserver/mstream
2) Create new Admin User in UI (http://localhost:3000)
3) Login attempt via curl:
curl -X POST -H "Content-Type: application/json" -d '{"username":"admin","password":"admin"}' 'http://127.0.0.1:3000/login'

Cheers,
Michael

**Comment by martadinata666** [comment]
yes, that's expected.
https://github.com/IrosTheBeggar/mStream/releases/tag/v5.1.0

**Comment by IrosTheBeggar** [comment]
As of v5 the Android App will no longer work. The good news is there is a new android app under development.

The bad news is this is going to take some time.  Mobile code ages like milk, and certain chunks have to be re-written from scratch. Dart (the language the mobile app is written with) doesn't have backwards compatibility between versions, which is why the rewrite is necessary.

**Comment by IrosTheBeggar** [comment]
I've got some good news, there's a initial release of the Android App for v5 here: 

https://github.com/IrosTheBeggar/mstream_music/releases/tag/v0.0.0

It's still early in devlopment, but the core features are working.  I will be posting regular releases of this app, and eventually will get it on Google Play
