### ISSUE TITLE
Generated share playlist link can't be selected/copied on firefox

### ISSUE THREAD

**Issue by eresonance** [IrosTheBeggar/mStream#32]
Firefox 53.0.3
mStream via git master

When I use the dialog to share a playlist the text in the textbox can't be selected or copied. When I edited the HTML, removing the "disabled" property seemed to fix it:
```html
<textarea class="share-textarea" rows="8" cols="60" placeholder="Your URL will be put here"></textarea>
```

Which works fine, but the default does not. I'm guessing this is specific to firefox, I don't know HTML enough to say whether this is the intended behaviour of that property or not.

**Comment by IrosTheBeggar** [comment]
Looks like firefox treats the disabled property slightly differently from other browsers

I changed it a readonly property that has the correct behavior.
