### ISSUE TITLE
[Feature Request] Please let mStream support lyries

### ISSUE THREAD

**Issue by giteRdroid** [IrosTheBeggar/mStream#320]
Hi, IrosTheBeggar.
I am very like this music server. I deployed mStream into my server 1 year. mStream is too easy to use.
I like sing songs at home, or learn to sing a song, but mStream can't support display lyrics on web or app.
Hope mStream can support display lyrics in the future.
Thank you very much.

**Comment by IrosTheBeggar** [comment]
Closing this ticket because its a duplicate of https://github.com/IrosTheBeggar/mStream/issues/228
