### ISSUE TITLE
boot error : "ssl.key" must be a string

### ISSUE THREAD

**Issue by Cathgao** [IrosTheBeggar/mStream#321]
I'm running mStream Express Server in Winodws10 LTSC with Nginx. But when I add the SSL key and cert for mStream, it just can't boot up.
![image](https://user-images.githubusercontent.com/21031564/123029426-aef9b680-d413-11eb-884b-e7d7a5fb2626.png)

My chain certs and private key are automatic renew by acme. 
![image](https://user-images.githubusercontent.com/21031564/123029769-39dab100-d414-11eb-83ef-f8e76505b6c2.png)

**Comment by IrosTheBeggar** [comment]
What version of mStream Express are you on?

**Comment by Cathgao** [comment]
> What version of mStream Express are you on?

5.1.18
the newest in release

**Comment by IrosTheBeggar** [comment]
Ok, can you post your config file?

**Comment by Cathgao** [comment]
> Ok, can you post your config file?

Could you tell me how to find the config file?

**Comment by IrosTheBeggar** [comment]
The config file is named server-config-v3.json and would be in your applications data folder.  

How are you adding certs to mStream?  I haven't added that to the admin panel, so the only way to do it is to add the certs directly to your config file.

**Comment by Cathgao** [comment]
I add the certs and key files in Security→DIY:
![QQ截图20210626163512](https://user-images.githubusercontent.com/21031564/123507566-ba134780-d69c-11eb-9f14-a7f779cafee5.png)

I can't find server-config-v3.json in the install path
![QQ截图20210626163612](https://user-images.githubusercontent.com/21031564/123507580-d3b48f00-d69c-11eb-8c3c-f5e640c90f99.png)

**Comment by IrosTheBeggar** [comment]
Ahh that's actually an old version of mStream. Looks like v4.

V5 can be found here

https://github.com/IrosTheBeggar/mStream/releases

You will need to add the paths for your ssl certs to yoir config. The new version as an option in the menu bar to open the server storage folder where the  onfig can be found

**Comment by IrosTheBeggar** [comment]
I added a form in the admin panel for adding and removing certs. It also checks if certs are valid before applying them
