### ISSUE TITLE
[feature request] Be able to filter Recently Added based on the folders to filter duplicates

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#322]
I have 1 main music folder for all my music files
I also have 1 sub folder with a specific genre

When the database is scanned sources from that sub folder are indexed twice. So recently added shows also 2 times the same file

The scanner is not that smart to see that the file is already indexed on another mountpoint ;) 
So quickest is to filter the recently added based on the various mount points /  (server path aliases)

Parts affected
- Recent
- Search

**Comment by pes7** [comment]
yes, please we need it ;)

**Comment by IrosTheBeggar** [comment]
I added the ability for all DB endpoints to filter results based on vpaths.  It's working in the latest commit.

Right now it's tied to the UI in the Auto DJ panel. The vpath filter for auto dj is now applied to all DB endpoints. I will be adding a separate UI for it soon

**Comment by aroundmyroom** [comment]
looks like it works in the search / recent I do not see any dupes anymore .. now does this relate to the number of songs in de db?
