### ISSUE TITLE
playlist error

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#327]
![image](https://user-images.githubusercontent.com/250108/131246412-4c2adeaa-4983-4441-8ddb-d09e189b55b2.png)

I do not use it a lot, but I have 1 playlist, but no songs can be played .. (latest version after the jquery removals)

**Comment by IrosTheBeggar** [comment]
Should be fixed now.  You might see a few bugs like this over the next few days as I continue to remove jQuery from the project

**Comment by aroundmyroom** [comment]
> Should be fixed now. You might see a few bugs like this over the next few days as I continue to remove jQuery from the project

ok, than I will wait for new reports until I see a new version and see something ;)

**Comment by IrosTheBeggar** [comment]
I pushed the last set of jquery removal updates. I also updated all the webapp libraries as well.  This update was bigger than expected.

Let me know if you hit any problems

**Comment by aroundmyroom** [comment]
playing from search does not work anymore. I see the results but pressing a result does not playback a song
But no error in de design window
only when pressing the 'add all songs to playlist' will work from the search, but that is not what you want ;)

**Comment by aroundmyroom** [comment]
fixed with #80f11c2
