### ISSUE TITLE
User Admin Webapp

### ISSUE THREAD

**Issue by anhgraphy9779** [IrosTheBeggar/mStream#329]
I have it on web, but it redirects to the admin login page.
i need login to admin page. thank you

**Comment by IrosTheBeggar** [comment]
I'm not sure what you mean

**Comment by anhgraphy9779** [comment]
> Tôi không chắc bạn muốn nói gì

https://tieuha.team/

**Comment by IrosTheBeggar** [comment]
https://tieuha.team/login/?redirect=%2Fadmin%2F

Will redirect you to the admin page after login
