### ISSUE TITLE
Struggle with .mp3 in the Android App

### ISSUE THREAD

**Issue by l-33ter** [IrosTheBeggar/mStream#334]
I don't know what your music collection consists of. However, the android app certainly takes 2-3 minutes to play an .mp3 file (`.opus` or `.m4a`) files are played immediately.

Does anyone else have problems with .mp3 files through the app?

Everything is accepted in the browser, no problems.

**Comment by IrosTheBeggar** [comment]
That's bizarre, what phone are you using? Also can you send me one of the mp3 files your using?

I've had no problem and I've played at least a few hundred mp3 files on my phone

**Comment by l-33ter** [comment]
My phone is a 'Huawei P20 Pro' with Android 10. Sure, I will send the mp3 files!
First, I thought it's my 'shitty' 4G but at work or at home I've got 1Gbit/s and the App struggled ONLY with .mp3 files.

Will try to use another phone, to look if there were any differences.

**Comment by IrosTheBeggar** [comment]
Hey, any updates on this?

**Comment by IrosTheBeggar** [comment]
I'm closing this for now since the app has changed a bit since then. If you still have any problems you can open another ticket
