### ISSUE TITLE
start on raspberry pi lite failed

### ISSUE THREAD

**Issue by winglq** [IrosTheBeggar/mStream#337]
Hi,
I failed to start mstream on raspberry pi lite, due to unable to open X display. Is there a way to start it without X? Thanks.

./mStream-Server-5.7.2-armv7l.AppImage
[24203:1025/111642.036029:ERROR:browser_main_loop.cc(1400)] Unable to open X display.

**Comment by IrosTheBeggar** [comment]
For headless servers you need to install mStream from source: https://github.com/IrosTheBeggar/mStream/blob/master/docs/install.md

You can also use the Docker image:

https://github.com/linuxserver/docker-mstream

**Comment by winglq** [comment]
Thanks, docker image works great.
