### ISSUE TITLE
App replication?

### ISSUE THREAD

**Issue by deletethisbenji** [IrosTheBeggar/mStream#34]
I'm building an app similar to this for my final project at school. Essentially, it's a podcast application with music integration and I'd like to pull music from my database and play those files on my deployed app.

Any idea how I should approach it - in terms of the tech stack, etc?

I keep on reaching dead ends and keep getting stuck finding efficient NPM dependencies that'll allow me to upload my files locally and play them.

Ideally, I'd like to create something that emulates yours - efficiency-wise.

Thanks for reading this!

*Forgot to mention that I'm a beginner, aha*

**Comment by IrosTheBeggar** [comment]
You're not going to be able to get a project like mStream done in time for a final project using javascript.  NodeJS is a good language, but using is as a file server like mStream does is not intuitive.

What you might want to look into is the LAMP stack.  Apache + MySQL will give you an easy fileserver + DB that works right out of the box.  And PHP is a good language to code webpages with.  

Good luck with your project
