### ISSUE TITLE
Setting music directory with cli?

### ISSUE THREAD

**Issue by FoxxMD** [IrosTheBeggar/mStream#35]
Screenshots from the express app show that setting a directory to search for music is possible but the docs don't mention any cli arguments or configuration file where I can specify what directory to search for music. (I'm running this from ubuntu on commandline).

When I start mstream all I can see is the root of the cloned directory and can't navigate up at all. Am I missing something?
![screen shot 2017-06-16 at 3 50 48 pm](https://user-images.githubusercontent.com/4663766/27242528-aa3a70b4-52ab-11e7-95c2-78e5edce52e6.png)

**Comment by IrosTheBeggar** [comment]
Right now mStream for cli uses whatever directory you run the program in.  So just `cd` to your music directory and run it there.

I'll add an option to change the directory via the cli

**Comment by FoxxMD** [comment]
Thanks!

**Comment by IrosTheBeggar** [comment]
I added  the `-m` option that allows you to set the music directory.   Check out the docs for more info

**Comment by FoxxMD** [comment]
Thanks for being so responsive on this! And also thanks for making a fantastic media server <3 

I've set up a cloud instance that rips my favorite radio show on the weekend and I have mStream running in the dir of the rip. It was super easy to setup and performance is superb 👌 you rock
