### ISSUE TITLE
filescan throws error and stops scanning

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#353]
folder 
/media/music/12-inches A-Z/A/Attitude (1983) We Got The Juice 12'' Promo/  files .. 
Meanwhile I have renamed the folder, but would love to get be noticed about such isssues by the program ;)

Jan 26 07:30:58 music node[8656]: 2022-01-26T06:30:58.223Z info: File scan started on /media/music/12 inches A-Z
Jan 26 07:32:28 music node[8656]: 2022-01-26T06:32:28.740Z error: File scan error: Warning: metadata parse error on /media/music/12 inches A-Z/A/Attitude (1983
Jan 26 07:32:28 music node[8656]: 2022-01-26T06:32:28.744Z error: File scan error: events.js:174
Jan 26 07:32:28 music node[8656]:       throw er; // Unhandled 'error' event
Jan 26 07:32:28 music node[8656]:       ^
Jan 26 07:32:28 music node[8656]: Error: EACCES: permission denied, open '/media/music/12 inches A-Z/A/Attitude (1983) We Got The Juice 12'' Promo/04 (Attitude
Jan 26 07:32:28 music node[8656]: Emitted 'error' event at:
Jan 26 07:32:28 music node[8656]:     at lazyFs.open (internal/fs/streams.js:115:12)
Jan 26 07:32:28 music node[8656]:     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
Jan 26 07:32:28 music node[8656]: 2022-01-26T06:32:28.752Z info: File scan completed with code 1

**Comment by aroundmyroom** [comment]
ugh .. issue related not to name but related to file attributes

drwxrwsrwx+ 547 nobody users    49152 Jan 26 08:55  ..
-rwxrwx---+   1 nobody users 36857159 Jul  2  2015 '01-We Got The Juice (Vocal).flac'
-rwxrwx---+   1 nobody users 38239710 Jul  2  2015 '02-We Got The Juice (Dub Version).flac'
-rwxrwx---+   1 nobody users 17956994 Jul  2  2015 '03-We Got The Juice (A Capella Glimmer).flac'
-rw-rwx---+   1 xxxx users 40037088 Jan 24 19:33 '04 (Attitude) We Got The Juice.flac'
-rw-rwx---+   1 xxxx users 42015491 Jan 24 19:33 '09 (Attitude) We Got The Juice (Dub Version).flac'

looks like that if the x is not there it is not indexed..

**Comment by IrosTheBeggar** [comment]
this should be fixed in the latest commit

**Comment by aroundmyroom** [comment]
Than we will close this for now as I fixed it already on user-level ;) Will report when I see another scan issue
