### ISSUE TITLE
[request] change filename when there is no id3tag in playlist

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#354]
![image](https://user-images.githubusercontent.com/250108/151945101-c8b54d2e-b3be-4e5a-8d8c-5312f00514a8.png)

when there is no id3tag it would be preferred to see the filename of the file being played
now all is empty but in the file-list it is seen / shown that the file is ie. mp3. if there is an id3tag the id3tag is displayed. So i would request to do the othterway around as well ;)

**Comment by IrosTheBeggar** [comment]
This has been added in the latest commit, along with some additional metadata tools

**Comment by aroundmyroom** [comment]
Yep .. working nice !
