### ISSUE TITLE
Guest account(s)

### ISSUE THREAD

**Issue by kuriot** [IrosTheBeggar/mStream#36]
Hello.

I see in help that I can launch mStream with guest account. I've tried it but it doesn't work. My normal account works but guest account sais "Login failed". Does it work? Can I create 2-3 guest accounts?

**Comment by IrosTheBeggar** [comment]
I found the bug and fixed it.  The latest version has working guest accounts

mStream can handle multiple guest accounts, but not through cli arguments.  I'm working on a feature to config mStream via a JSON file that would allow multiple accounts and guest accounts.  You can see the code in `modules/configure-json-file.js`  It's not done yet so I haven't documented it
