### ISSUE TITLE
[Feature Request] Repeat one song

### ISSUE THREAD

**Issue by vsey** [IrosTheBeggar/mStream#362]
It would be nice to have a function to play a song on repeat by for example pressing the repeat button twice

**Comment by aroundmyroom** [comment]
Ah you mean that in a playlist you want to listen to a song a 2nd time the GUI should give you an option to listen to the song another time before the next song in the playlist is played .. 

correct?

**Comment by IrosTheBeggar** [comment]
I added this in the latest commit

**Comment by yananet** [comment]
Hello, thanks for this enhancement.
I can see this in the web interface, but I cannot see this in Android app...
is it required to be reported in a separate place?
