### ISSUE TITLE
[Feature Request] Song name in title

### ISSUE THREAD

**Issue by viktor02** [IrosTheBeggar/mStream#383]
Hello. I'd like to see what song is currently playing without going to the mStream tab. Page title is perfect for this.

*This is what it looks like now*
![image](https://user-images.githubusercontent.com/19672960/182483220-e283c73d-0ba3-4d6d-97f7-39589f333e75.png)

*How it should look*
![image](https://user-images.githubusercontent.com/19672960/182483149-1eeac890-f240-4782-b879-226f1dd62fea.png)

**Comment by aroundmyroom** [comment]
Nice .. I like that !

**Comment by viktor02** [comment]
merged in #384
