### ISSUE TITLE
[Feature Request] Support symlinks on Unix-like systems

### ISSUE THREAD

**Issue by maxim-kukushkin** [IrosTheBeggar/mStream#392]
My music collection which I want to stream contains symlinks + when running mStream in Docker, there's only one host folder that can be provided. Thus I need to link my multiple folders with the one provided to mStream.

However, mStream seems to ignore the symlinks completely.

Can it be enabled to follow symlinks? If not by default, then may be through the config?

**Comment by tdammers** [comment]
Not sure if it's a Docker thing, but symlinks work exactly as they should on my install.

I have one big bucket of music in `/mnt/data/media/music`, and then a subdirectory `/mnt/data/media/music/categorized` containing relative symlinks, grouped into subfolders by genre/category, and the mStream server is then pointed to `/mnt/data/media/music/categorized`; it plays songs through the symlinks just fine.

**Comment by maxim-kukushkin** [comment]
@tdammers , you're absolutely right, thanks! I really overlooked this part. Symbolic links are not handled by the OS, it's just a pointer to a path. And the path will be the same string both in the host OS and in a Docker container. So, if a symlink points to `/foo/bar`, Docker will also read it as `/foo/bar`, but will try to access it inside the container, which obviously will result in broken links

After figuring this out I managed to resolve this by `bind` mounts (on Linux):
`/my/music/files /srv/mstream/music/Music none bind 0 2` (/etc/fstab)
