### ISSUE TITLE
playlists delete

### ISSUE THREAD

**Issue by HappyWheels** [IrosTheBeggar/mStream#4]
Hello Iros, I am wondering if there is a way to delete a saved playlist from the mstream database? 
Forgive me if i have missed something, but i cannot find a way to remove stored playlists that wouldn't involve modifying the mstreamdb directly.  
On the Playlists page the 'Add Directory to Playlist' button is still present above the Playlists panel, i think a feature/enhancement would be to replace this with a playlist delete function to remove previously saved playlists, restricted to the user account. 
This is observed running the master branch using a beets library database and accessed with Firefox 45.3.0

![selection_001](https://cloud.githubusercontent.com/assets/7735144/18757383/140ee142-8137-11e6-9d05-a6ef8aae556b.png)

**Comment by IrosTheBeggar** [comment]
Good catch.  I'm making a fix for this now

**Comment by IrosTheBeggar** [comment]
I pushed a fix. Each playlist in the view now has a button next to it to delete it.

Guest users will see the button but will not be able to access the delete function.  Currently all users get identical frontends.  V2.0 will have a feature to change the frontend depending on the user's permissions

**Comment by HappyWheels** [comment]
Thank you, the changes work great. Yeah i thought it would behave like the other non user  elements, excited to test out V2.0. It is just what i want for remote library access, and the user account for when i want access read only is a great feature, will be pleased to see the changes.
