### ISSUE TITLE
Keep Folder Structure

### ISSUE THREAD

**Issue by Riajyuu** [IrosTheBeggar/mStream#53]
If the target folder contains multiple sub-folders in which there are valid files, please keep & display the structure as a tree view.
Perhaps we need an option entry to toggle this.

**Comment by IrosTheBeggar** [comment]
When you say tree view, I assume you mean something like this:

![image](https://user-images.githubusercontent.com/1396994/30866820-46c2e262-a2a8-11e7-8ff9-4c178f321a01.png)

This would be a lot of work.  I'm not opposed to the idea, but I've got bigger problems to fix first.

**Comment by Riajyuu** [comment]
Yes. That is it exactly. Take my personal example I have CDs from different animation and I put CDs into different subfolders.
And I totally understand you're loaded up now.

**Comment by IrosTheBeggar** [comment]
Moved to this ticket: https://github.com/IrosTheBeggar/mStream/issues/92
