### ISSUE TITLE
/lib/trace.js:27                     throw err;

### ISSUE THREAD

**Issue by gerroon** [IrosTheBeggar/mStream#57]
HI

I got it up and running using node6. I can serve the server and open the page but the server crashes with the log below when I click on a folder inside the -m PATH

Using it on Debian Testing 
node -v 6.11.4

npm 3.10.10

USER SYSTEM NOT ENABLED!
SSL DISABLED
Access mStream locally: http://localhost:9111
Access mStream on your local network: http://192.168.4.106:9111
/media/REPOC/BUILD/mStream/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'Count(*)' of undefined
    at Statement.<anonymous> (/media/REPOC/BUILD/mStream/modules/db-read/database-public-sqlite.js:14:17)
--> in Database#get('SELECT Count(*) FROM items WHERE user = ?;', [ 'mstream-user' ], [Function])
    at Object.exports.getNumberOfFiles (/media/REPOC/BUILD/mStream/modules/db-read/database-public-sqlite.js:13:6)
    at /media/REPOC/BUILD/mStream/modules/db-management/database-master.js:112:25
    at Layer.handle [as handle_request] (/media/REPOC/BUILD/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/media/REPOC/BUILD/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/media/REPOC/BUILD/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/media/REPOC/BUILD/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /media/REPOC/BUILD/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/media/REPOC/BUILD/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/media/REPOC/BUILD/mStream/node_modules/express/lib/router/index.js:275:10)

**Comment by IrosTheBeggar** [comment]
This looks like it's a problem with the SQLite plugin.  Did you make sure to delete the node_moduels folder and re-run `npm install` after changing from node 8 to v6?
 
The SQLite plugin has to be compiled against the current node version.  So SQLIte for node 8 won't work for node v6.  I'm looking into moving away from SQLite to avoid complications like this: https://github.com/IrosTheBeggar/mStream/issues/55

**Comment by gerroon** [comment]
@IrosTheBeggar 
I reinstalled everything from scratch after removing node8 including cloning the git copy of this repo.

**Comment by IrosTheBeggar** [comment]
What version of Debian are you on?  I'll try setting up a VM later to see what the problem is

**Comment by gerroon** [comment]
debian testing

**Comment by IrosTheBeggar** [comment]
Ok I'm downloading a copy of Buster Alpha 1 for testing now

**Comment by IrosTheBeggar** [comment]
Ok I was able to get this working on Debian.  I pushed a commit that will dump SQL errors on that problem line to the console.  Try running it again and paste the error here so I can get a better idea of what's going on

**Comment by IrosTheBeggar** [comment]
@gerroon 

The latest version of mStream should fix this problem. I swapped out SQLite for LokiJS, an in-memory document store.  It's faster and doesn't rely on node-gyp, which I believe is what is causing all these problems.

I'm still tweaking the new DB. So if you see any bugs let me know

**Comment by gerroon** [comment]
ok thanks, I will try it tonight
