### ISSUE TITLE
Could do with a volume Slider.

### ISSUE THREAD

**Issue by madman2021** [IrosTheBeggar/mStream#61]
First thanks for all your work.
Could a Volume slider be added to the Todo list 👍 
MSTREAMPLAYER.changeVolume(15) is tedious 😢

**Comment by IrosTheBeggar** [comment]
I'm working on it now

**Comment by IrosTheBeggar** [comment]
The latest commit to master has a volume bar

**Comment by madman2021** [comment]
Awesome thank you 👍
