### ISSUE TITLE
Reverse Proxy with nginx

### ISSUE THREAD

**Issue by Mootch** [IrosTheBeggar/mStream#64]
I am trying to set up a reverse proxy with nginx on an mstream build for raspberry pi. I have nginx set up to serve everything through https. The following code gets me a 404 not found.

```
upstream mstream_app {
        server 127.0.0.1:3000;
}
```
and
```
location /mstream {
        proxy_pass http://mstream_app;
}
```
If I put a '/' at the end of the proxy pass line, a page will load, but the formatting is messed up. What do I need to do to get a proper reverse proxy that doesn't lose the app formatting?

**Comment by IrosTheBeggar** [comment]
Here's how I handle the NGINX reverse proxy for https://darncoyotes.mstream.io/

```
server {
       listen 80;
       server_name darncoyotes.mstream.io;
       rewrite     ^   https://$host$request_uri? permanent;
}

server {
    listen 443 ssl;
    server_name darncoyotes.mstream.io;

    ssl_certificate /etc/letsencrypt/live/darncoyotes.mstream.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/darncoyotes.mstream.io/privkey.pem;

    # Turn on OCSP stapling as recommended at
    # https://community.letsencrypt.org/t/integration-guide/13123
    # requires nginx version >= 1.3.7
    ssl_stapling on;
    ssl_stapling_verify on;

    location / {
            proxy_pass http://localhost:3030;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
    }
}

```

I believe your problem is that you are mapping mStream to a specific URL path.  mStream makes extensive use of URL paths to handle everything from album-art, streaming, and serving the webapp.  

In my configs I map the mStream app to the whole subdomain.   This assures there are no URL path conflicts

**Comment by Mootch** [comment]
Yeah, mStream will work correctly if I map it to the base of the subdomain, but it gets messed up if I try to map it to a URL path and then drop the tail end through the reverse proxy. The page will partially load, but with messed up formatting and no graphics.

I would like to use a /mstream path so that I can run this in parallel with my other services and not take over the base directory. I will keep digging into nginx configurations to see if there's a way to capture the missing resources in my reverse proxy set up.

**Comment by Mootch** [comment]
Additional note: some of the other services I use have the option for a reverse proxy prefix to allow for a set-up like I noted above. That could be a feature request for mStream.

**Comment by IrosTheBeggar** [comment]
I've never tried this approach to a reverse proxy before.  I'll have to setup my own to really debug what's going on.  I have an idea why it's breaking and I'm hoping the fix will be simple.

In the meantime, can you post your NGINX config for this setup?

**Comment by Mootch** [comment]
Here is my current set-up.

```
upstream reader_app {
	server 127.0.0.1:2202;
}

upstream btsync_app {
	server 127.0.0.1:8888;
}

upstream mstream_app {
	server 127.0.0.1:3000;
}

server {
	listen 80 default_server;
	listen 443 ssl;
	server_name "";
	ssl_certificate /path/to/certificate;
	ssl_certificate_key /path/to/key;
	return 444;
}

server {
	listen 80;
	server_name example.net;
	return 301 https://$server_name$request_uri;
}

server {
	listen 443 ssl;
	server_name example.net;
	root /var/www/html;
	index index.html index.htm;
	ssl_certificate /path/to/certificate;
	ssl_certificate_key /path/to/key;

	location / {
		try_files $uri $uri/ =404;
	}

	location /reader {
		proxy_pass http://reader_app;
	}

	location /gui {
		proxy_pass http://btsync_app;
	}

	location /mstream {
		proxy_pass http://mstream_app;
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}
```

**Comment by IrosTheBeggar** [comment]
@Mootch Thanks, having that will make it easier to test.

I've been pretty busy this week.  I'll take some time out this weekend to get this done
