### ISSUE TITLE
Forward http to https automatically

### ISSUE THREAD

**Issue by IrosTheBeggar** [IrosTheBeggar/mStream#70]
If the user has enabled SSL, the mStream server should forward all http to https traffic.

**Comment by IrosTheBeggar** [comment]
As far as I can tell, this isn't possible.  If anyone has any suggestions let me know

**Comment by ehea617** [comment]
Should be possible. When the user adds an SSL certificate, have the server send a 301 redirect from any accessed insecure URL to the secure URL. For the Android app, make sure that you can specify the protocol when adding the server.

**Comment by aroundmyroom** [comment]
is this an option?
https://www.npmjs.com/package/express-http-to-https
or this
https://www.npmjs.com/package/redirect-https

**Comment by IrosTheBeggar** [comment]
The goal is to serve http & https requests over the same port.  This SO post has some ideas: https://stackoverflow.com/questions/22453782/nodejs-http-and-https-over-same-port
