### ISSUE TITLE
Built-in Let's Encrypt SSL

### ISSUE THREAD

**Issue by Riajyuu** [IrosTheBeggar/mStream#73]
Since it can be renewed by automatic scripting, it's the best choice here.

**Comment by Riajyuu** [comment]
Perhaps a plausible solution to #70 ?

**Comment by Riajyuu** [comment]
hey, let's Encrypt has started wildcard cert. It may bring convenience here somehow

**Comment by rubenwardy** [comment]
No need for this. Users should utilise SSL termination and a reverse proxy like nginx

**Comment by IrosTheBeggar** [comment]
SSL management is really outside the scope of the mStream project.  There's no way I would be able to build something that even compares to certbot.  I will work on writing some guides on DIY SSL for mStream
