### ISSUE TITLE
lokijs

### ISSUE THREAD

**Issue by ricardocjca** [IrosTheBeggar/mStream#76]
Hello, I'm using lokijs in an application when I run in dev mode and I update data in the database works fine.

more when I create the executable and install it on the computer and do the update of the data to record in the bank I do not succeed, can you tell me why?

**Comment by IrosTheBeggar** [comment]
I need some clarification, is this a problem with mStream or a problem with an app you are building?

**Comment by IrosTheBeggar** [comment]
Your application as an exe has limited access to the filesystem.  `app.getPath('userData')` will return a file a folder your program has access to
