### ISSUE TITLE
Automatically detect filesystem changes and update DB

### ISSUE THREAD

**Issue by IrosTheBeggar** [IrosTheBeggar/mStream#77]
Look into using this:

https://github.com/atom/watcher

**Comment by IrosTheBeggar** [comment]
Or this
https://github.com/Axosoft/nsfw

**Comment by IrosTheBeggar** [comment]
Or this
https://github.com/paulmillr/chokidar

**Comment by aroundmyroom** [comment]
4TB of data can be scanned for updates once an hour, even shorter. The rescan on my nas is really quick,
for me there is no direct need for an 'direct' scan of the db. Really happy with the performance right now. Almost no load after the initial scan, rescan is without pain .. !

**Comment by IrosTheBeggar** [comment]
Moved to the projects Ice Box
