### ISSUE TITLE
Database Management not working

### ISSUE THREAD

**Issue by pbtrung** [IrosTheBeggar/mStream#8]
Hi,

I am using beets db and it shows in Database Management "Error undefined files".
Integration with beets is super duper awesome.

Thanks for the new version.

**Comment by IrosTheBeggar** [comment]
The DB Management panel needs some work to bring it up to speed with the rest of the upgraded.  Does searching by album/artist work?

**Comment by pbtrung** [comment]
Yep, searching works.
I do know it'll take time. Just to report a bug.

I am running beets to index a large music collection (820k tracks) to use with mstream. 
Hope it will work well.

**Comment by IrosTheBeggar** [comment]
Should be fixed now.  Check it out

**Comment by pbtrung** [comment]
Fixed. Thanks.
