### ISSUE TITLE
Slight error

### ISSUE THREAD

**Issue by madman2021** [IrosTheBeggar/mStream#83]
https://github.com/IrosTheBeggar/mStream/blob/f66319d608194c7c989dbe0672a6a694ecb42592/modules/configure-commander.js#L36

**Comment by IrosTheBeggar** [comment]
That is slight. And it's fixed now

**Comment by madman2021** [comment]
I was going to send a PR but be more work merging it in that just changing it for next commit haha, Thanks for the great work.
