### ISSUE TITLE
Kodi Plugin

### ISSUE THREAD

**Issue by IrosTheBeggar** [IrosTheBeggar/mStream#90]

**Comment by jugendhacker** [comment]
@IrosTheBeggar Do you need someone who programs this plugin?

**Comment by IrosTheBeggar** [comment]
@jugendhacker 

Yea, I'm looking for someone to program this

**Comment by jugendhacker** [comment]
@IrosTheBeggar I haven't programmed a plugin by myself but it is python and it would be a challange for me to try this...

**Comment by IrosTheBeggar** [comment]
Challenging yourself is a good way to learn

**Comment by jugendhacker** [comment]
Yes I will download Kodi to my maschine and start... I hope I'll finde some good tutorial...

**Comment by IrosTheBeggar** [comment]
@jugendhacker 

Awesome!

**Comment by jugendhacker** [comment]
Short update what I am doing: At the moment I can browse the files and folders on the Server and I can play music from there, also with metadata. At the moment I don't fetch the album cover, but rest of metadata! I can't publish it in a repo at the moment because my credentials and the Server are still harcoded, but the next thing would be to implement this as setting and after that I can publish it!

**Comment by jugendhacker** [comment]
@IrosTheBeggar now I have a version with no private information hardcoded, should I open a repo here on github and publish the code I have made until now?

**Comment by IrosTheBeggar** [comment]
Yea, create a repo and post it here.  Looking forward to checking it out

**Comment by jugendhacker** [comment]
I will do it after 2 PM UTC, because I have to go to school

**Comment by jugendhacker** [comment]
So now I created [this repo](https://github.com/jugendhacker/plugin.audio.mstream/) and pushed there all work I made until now

**Comment by jugendhacker** [comment]
But I'm not sure to handle a server with no credentials, where I have to request the token?

**Comment by IrosTheBeggar** [comment]
A server with no credentials doesn't need a token.  You can just start calling the API

**Comment by jugendhacker** [comment]
Ok I will go to bed now and will implement it tomorrow

**Comment by IrosTheBeggar** [comment]
@jugendhacker how's progress on the kodi app going?  I'll add it to the Readme and website when you think it's ready

**Comment by jugendhacker** [comment]
@IrosTheBeggar sorry I was really bussy in the last days so almost no forward, but now I have holidays so I can invest more time...
Have you tried what I have done sofar?

**Comment by IrosTheBeggar** [comment]
I haven't tried it yet.  I moved recently and my Kodi box has been sitting in the corner collecting dust ever since.  Will set it up this weekend

**Comment by IrosTheBeggar** [comment]
I'm going to be starting work on a headless streaming client soon.  The goal is to just have one library that will work on most platforms instead of trying to write a million various clients.
