### ISSUE TITLE
Webapp Improvements

### ISSUE THREAD

**Issue by IrosTheBeggar** [IrosTheBeggar/mStream#92]
This ticket will be used to track all tasks for the webapp.  Currently the webapp is stable, but there are some small improvements that could be made

## Fix These Bugs
- Redo the explorer with VueJS.  Right now it's a mess of jQuery
- Handle expired token
- ~~Fix CSS for jukebox and shared pages.  Some recent work appears to have caused some bugs~~
- Optimize the caching algorithm.  There's some edge cases when re-arranging the playlist that causes the cache to become invalid
- ~~File explorer gets gets incorrect path when a request fails~~

## Add These Views
- Recently added songs
- Recently played songs

## Add these features
- ~~Upload songs into folders with drag&drop~~
- File Explorer with tree style view
- Fade in/out (and other audio effects by moving the code to use Web Audio)

**Comment by IrosTheBeggar** [comment]
This might be useful for creating a tree view: https://www.jstree.com/docs/html/

**Comment by IrosTheBeggar** [comment]
The webapp could also use a panel to manage users and server settings

**Comment by panigrc** [comment]
Is it possible to reduce the load on the client?

For example I am seeing a steady 1-2% cpu usage on Firefox in Ubuntu, but tested with same results in Windows 10 too and i have an i7-5500u .

I don't know what it's causing that, but the WebApp it could have for example a background mode, where fewer things where loaded.

**Comment by IrosTheBeggar** [comment]
@panigrc 

I'm on a macbook right now and Firefox is running at less than .5% when idle.  That being said, there is some room for improvements. I just pushed a change that gets rid of lodash and cookiesJS.  There's room to get rid of foundation and modernizr as well.

Can you see if you have the same problem with Chrome?  Firefox's audio system has been having some problems lately with howler (the audio management library).  These problems are new and were not happening a year ago though

**Comment by jugendhacker** [comment]
I don't think that 1-2% load are so much... that load could Firefox be self for example update checking or syncing the settings with your Firefox account...

**Comment by panigrc** [comment]
So I tried a chromium incognito window without any extensions and got the same 2%.
I know it's not big, but I would like to test it on older machines.

**Comment by jugendhacker** [comment]
As I wrote, I think it could be the browser it self that consumes this CPU... have you looked into the chrome internal task manager what window/tab uses the CPU how much?

**Comment by panigrc** [comment]
![selection_001](https://user-images.githubusercontent.com/645895/48448105-397ad380-e79e-11e8-8535-27f53fdd0a12.jpg)

**Comment by IrosTheBeggar** [comment]
@panigrc 

What version of Firefox are you on?

**Comment by panigrc** [comment]
FF: 63.0 (64-bit)
Chromium: Version 65.0.3325.181 (Official Build) Built on Ubuntu 
System:  Ubuntu 14.04 (64-bit)

**Comment by IrosTheBeggar** [comment]
@panigrc 

I'm working on the v4 branch that has some webapp updates.  I removed foundation and modernizer which should help. The webapp was using foundation v4 which was bloated and really outdated

**Comment by IrosTheBeggar** [comment]
@panigrc I merged the v4 branch into master.  Check it out and let me know if that helps

**Comment by panigrc** [comment]
@IrosTheBeggar I did see a small improvement. And a whole new interface :+1:

**Comment by IrosTheBeggar** [comment]
@panigrc 

One thing you can do is manually remove these lines from the mstream.html file:

```
  <script src="/public/js/lib/butterchurn.min.js"></script>
  <script src="/public/js/lib/butterchurn-presets.min.js"></script>
  <script src="/public/js/lib/butterchurn-presets-extra.js"></script>
```

Those files are for the visualizer and are not needed for the webapp to work

**Comment by G-Michel** [comment]
hi ! 
First thanks for your work its awesome !! 
i have a question , when you refers to keep folder structure, do you mean keep the structure of the folder you upload one into the webapp ?

**Comment by IrosTheBeggar** [comment]
Moving this to the project board:
https://github.com/IrosTheBeggar/mStream/projects/5

@G-Michel I added it to the todo list there
