### ISSUE TITLE
Music in folders with # cannot be played

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#94]
/media/media/abort.fm/%233rd%20Release%20Abort%20
from the google console log: error 404
http://10.1.1.159:3000/media/media/abort.fm/%233rd%20Release%20Abort%20#/01%20-%20FGTH%20-%20Welcome_to_the_pleasuredome_-_nalin_and_kane_remix.mp3

Cannot GET /media/media/abort.fm/%233rd%20Release%20Abort%20

**Comment by IrosTheBeggar** [comment]
Thanks for reporting this. The latest commit fixes this issue.

**Comment by aroundmyroom** [comment]
fix is working fine !
