### ISSUE TITLE
High Load, stop playing, unresponsive

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#95]
I have
143033 files in DB (around 4TB)
after latest git pull and restart of the mstream program I see various messages in my console

1 and 2

[code]
stdout: Warning: failed to parse file '/media/music/Only 12 inches 7/Shooting Party ‎– Let's Hang On/03.) Shooting party - Show me the way to your heart.wav': FourCC contains invalid characters

stdout: Warning: failed to parse file '/media/music/Only 12 inches 7/Tamiko Jones - Can't Live Without Your Love (Full Length Version).wav': expected file identifier 'ID3' not found

this might be normal behaviour, but during the play just after the web-gui became responsive the music was suddenly stopped. I believe that ID3 is not available at all in WAVs .. and I wonder why  FourCC tells that there are invalid characters

After that
in my console I see a lot of messages:

Somewhere in the initialisation or background the very fast UI (compliments) became unresponsive and it took around 1 or 2 minutes before the UI was accessible again

[code]
Error: ENOENT: no such file or directory, stat '/media/music/12 inch alfabet/12 inches/12 inches/12 inches'
    at Object.fs.statSync (fs.js:948:11)
    at /home/mStream/modules/file-explorer.js:38:13
    at Layer.handle [as handle_request] (/home/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mStream/node_modules/express/lib/router/index.js:275:10)
    at /home/mStream/mstream.js:155:7
Error: ENOENT: no such file or directory, stat '/media/music/12 inch alfabet/12 inches/12 inches/12 inches/abort.fm'
    at Object.fs.statSync (fs.js:948:11)
    at /home/mStream/modules/file-explorer.js:38:13
    at Layer.handle [as handle_request] (/home/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mStream/node_modules/express/lib/router/index.js:275:10)
    at /home/mStream/mstream.js:155:7
[/code]

Also be noticed that the mentioned no such file or directory is true: this folder does not exist in my environment.

After the restart it seems not happen again (yet), but it might need more testing.

**Comment by IrosTheBeggar** [comment]
Can you email me the two songs that failed caused errors?  I'm going to test them on my machine to get a better idea of what went wrong.  My email is paul.sori@gmail.com

**Comment by IrosTheBeggar** [comment]
The `Error: ENOENT: no such file or directory, stat '/media/music/12 inch alfabet/12 inches/12 inches/12 inches'` is a UI bug.  If a request times out (which is what happened when your server became unresponsive) the UI will update the file explorer path even though the request didn't work. Refreshing the UI fixes this problem.

I updated https://github.com/IrosTheBeggar/mStream/issues/92 with this problem

**Comment by aroundmyroom** [comment]
1. you will receive a wetransfer link soon [meanwhile, sent!]
2. Just can confirm this issue as UI issue. I was pressing 2 times quick behind each other 
and I see same info in my shell window.

**Comment by IrosTheBeggar** [comment]
I fixed the file explorer bug in the latest commit.  Still looking into the wav files.

**Comment by aroundmyroom** [comment]
seems to fixed that file explorer issue .. btw I also like the DJ option, I wondered what it would do and than I saw a random song appear in the playlist.. kewl ;)  and I am really surprised this tool is soo quick in playing songs. Almost instantly in my VM (1024MB / 16GB (where the images is around 2GB ugh) ;)  and the json db around 78MB (running in Debian 9). Will test tomorrow through VPN at my work ;)

**Comment by IrosTheBeggar** [comment]
Glad you like it.  

How much memory does mStream use on your setup?  mStream uses an in-memory DB (which is what makes it so fast) but I want to make sure it's not using to much memory with a large collection.

**Comment by IrosTheBeggar** [comment]
I got some help with those files and it looks like the metadata is incorrect in both of them.  

```
The first file has a strange RIFF/EXIF tag 'GNR\u0001':

------[exif]------
{ IART: [ 'Shooting party' ],
  'GNR\u0001': [ '' ],
  INAM: [ 'Show me the way to your heart' ],
  ICRD: [ '1990' ] }

The '\u0001' is considered to be illegal (for good or bad reasons), causing the exception

The second file has an ID3 chunk defined, which is normally used for ID3v2 header. The header identifier is set to TAG instead usual ID3. 
```

Unfortunately there's not much I can do if the tag info is correct

**Comment by aroundmyroom** [comment]
memory usage
scanning
mStream/modules/db-management/database-default-manager.js {"directo
                      Kbytes     RSS   Dirty Mode 
total kB         1502004  153480    8920
total kB         1508340  164780    3968
total kB         1510596  164844    4340
total kB         1536372   68656    7576


slowly consuming more memory

idle application just after a restart
total kB         1311468    1832       0

pmap -x used

**Comment by aroundmyroom** [comment]
I will try to update / scan my database for id3tag failures in the files, no idea what tool can fix that the best for such amount of files
the errors thrown in the console is not my issue, the issue is that it takes around x minutes that the UI becomes responsive again after being restarted. (will not happen that much, but when testing its irritating ;)

**Comment by IrosTheBeggar** [comment]
Beet is a good tool for managing ID3 information: https://github.com/beetbox/beets

I've also heard god things about Picard: https://picard.musicbrainz.org/

I imagine the process is being hogged by the database load process.  Right now the DB module is in the same thread as the API.  So when loading the DB, the entire thread is being utilized for that one purpose, and the API calls won't be processed until that's over.  The UI will not receive any API responses during this time.  For most collections (like my 500GB), the load time is so short it's unnoticeable. 

The best solution would move all database operations to their own thread.  This would including loading the DB, so the API would be responsive during this time.  This kind of work requires a lot of extra code, so it's going to take some time.
