### ISSUE TITLE
improve search: within folders through db

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#96]
Extend the search funtion to be able to search within all your files.
Now search is only available within the folder you are. 

please add also wildcards etc. Dunno what is being saved in the db about the id3tag if exist but that should be added as well if possible.

oeff .. I see db is a json kind of file .. I thought it was sqlite or something ;)

**Comment by IrosTheBeggar** [comment]
mStream actually switched from SQLite to LokiJS a few months ago https://github.com/techfort/LokiJS

**Comment by IrosTheBeggar** [comment]
It's been a while, but this feature is finally in the latest commit

It uses regex, so you can use a wildcard with a period character

**Comment by aroundmyroom** [comment]
<s>do you have example? I have a song like 'When in Rome' there are multiple folders above like
this structure
Songs --A ~ Z -- W ~ When in Rome --Songs
So where can I find 'when in rome' with the . period ?

does it work in the file explorer or only in artists / album?</s>

Stupid me. I now see the menu option.. thats even better ! .. great!
