### ISSUE TITLE
Album-Art not loaded: {"error":"Access Denied"}

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#97]
When using Username - Password and you authenticate yourself you are able to stream music
but album-art is not loaded
when trying to access the URL  y'll see:
{"error":"Access Denied"}

when mstream is started without username and password, all is well.

**Comment by IrosTheBeggar** [comment]
I made a push recently to improve security on all API endpoints.  Looks like I forgot to update the album art calls.  This should be fixed in the latest commit

**Comment by aroundmyroom** [comment]
I see one issue left when accessing the page with username and password

![image](https://user-images.githubusercontent.com/250108/40041513-8616e068-581e-11e8-8fc9-30c3d27c5fb1.png)

the .js seems accessible

**Comment by aroundmyroom** [comment]
send | @ | jquery-2.2.4.min.js:4
-- | -- | --
  | ajax | @ | jquery-2.2.4.min.js:4
  | makeRequest | @ | api2.js:30
  | makeGETRequest | @ | api2.js:54
  | mstreamModule.ping | @ | api2.js:143
  | testIt | @ | mstream.js:74
  | (anonymous) | @ | mstream.js:97
  | i | @ | jquery-2.2.4.min.js:2
  | fireWith | @ | jquery-2.2.4.min.js:2
  | ready | @ | jquery-2.2.4.min.js:2
  | J | @ | jquery-2.2.4.min.js:2

**Comment by IrosTheBeggar** [comment]
That's totally normal.  The frontend makes a request to /ping on load to check if login is enabled.  If the request get's routed to /access-denied the frontend then displays the logins screen.
