### ISSUE TITLE
Missing file stops DJ service

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#98]
http://mstream:3000/media/media/TOP40-65-2009/2008/Nick%20&%20Simon%20-%20Hoe%20Lang.mp3?token=xxx 404 (Not Found)

this file generates an error 404 as it was removed last night.
When I press Build Database is it rescanning all content and all what is missing is being removed?

Right now the DJ function stops cause the error 404 is not followed by another attempt to play the next song queued.

**Comment by IrosTheBeggar** [comment]
Thanks for taking the time to report all these.  Will fix this one tonight

**Comment by aroundmyroom** [comment]
Thanks. I have long searched for a tool this quick and like to help testingIt is simple and does not 100% need id3tags as I do  zero maintenance on that ;) Can you give me some guidelines how to handle removed files from disk and the adding of new files? for the database? I just removed 150GB of music and replaced it with same but that one has embedded album art.

**Comment by IrosTheBeggar** [comment]
This one has finally been fixed!
