### ISSUE TITLE
switched to json

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#99]
Just switched to the json configuration so that I could use features more easily. 
Will also update the db to a new fresh one (+80MB)

notices for json
use ie.  python -m json.tool config.json to validate the json, I fixed 3 issues in my json using the example (duh) ;) starting mStream will only say the json fails but you do not know why or where.

ssl is working. I had a wildcard letsencrypt from another VM used for apache2 and it worked directly adding it to the json (yeah!)

getting more exited ;)

**Comment by IrosTheBeggar** [comment]
Yea, handwrittin JSON is a pain.  I want to add a library that can help construct/validate JSON config files.  Even made a ticket for it:  https://github.com/IrosTheBeggar/mStream/issues/71

**Comment by IrosTheBeggar** [comment]
Closing ticket since it's covered by #71
